### ISSUE TITLE
Problems using NUnit3 TestAdapter.

### ISSUE THREAD

**Issue by basilfx** [tonerdo/coverlet#101]
Using the workaround mentioned in #40, I was able to at least run using the NUnit3 test adapter. However, I still have to blacklist/exclude inserting instrumentation code into the test adapter code, otherwise it cannot find the tests.

Now that 2.0 is available, I can call it like this: `dotnet test /p:CollectCoverage=true /p:Exclude=[NUnit3.TestAdapter]*`, which lets me run the tests (and after disassembling the DLLs, I see that they have been modified). However, the coverage remains 0%.

I can imagine that Coverlet wants to be test adapter agnostic, but any help/tips/idea's to get it up and running?

**Comment by MaartenX** [comment]
The reason the results are not found is that the CoverageTracker.CurrentDomain_ProcessExit is never called when using the test adapter. I'm looking into other ways to detect the tests have finished, currently I have a workaround, I just call the method after my tests are finish using reflection.

Add the following class to your test project:

```csharp
using System;
using System.Linq;
using NUnit.Framework;

namespace NUnitCoverletFix
{
    /// <summary>
    /// Fixes coverage for the NUnit3 TestAdapter by reporting the 'end of process' to Coverlet.
    /// </summary>
    [SetUpFixture]
    public class NUnitCoverageFix
    {
        /// <summary>
        /// Called when the NUnit tests are done. Tries to call Coverlet.Core.CoverageTracker.CurrentDomain_ProcessExit
        /// by using reflection. This DLL is only loaded when we're using coverlet, and this method is
        /// only called when using NUnit, so this is for a very specific case.
        /// </summary>
        [OneTimeTearDown]
        public void GlobalTeardown()
        {
            var coverageTracker = AppDomain.CurrentDomain.GetAssemblies()
                .FirstOrDefault(
                    ga => ga.GetName().Name.Equals("Coverlet.Core", StringComparison.InvariantCultureIgnoreCase))
                ?.ExportedTypes
                .FirstOrDefault(
                    t => t.FullName == "Coverlet.Core.CoverageTracker");

            coverageTracker
                ?.GetMethod("CurrentDomain_ProcessExit")
                ?.Invoke(null, new object[] { AppDomain.CurrentDomain, EventArgs.Empty });
        }
    }
}
```

**Comment by basilfx** [comment]
Thanks @MaartenX, I’ll check of this works for me as well.

**Comment by basilfx** [comment]
I also think #24 is related.

**Comment by basilfx** [comment]
This works for me, but I have to add it to every test project (teardown doesn’t seem to be called when it’s in a sub project).
