### ISSUE TITLE
Migrating to 2.0.0

### ISSUE THREAD

**Issue by Razzeee** [tonerdo/coverlet#107]
Hey there,

just a quick heads up. When I update our sources to 2.0.0, it still runs the tests and works fine locally. But if I run it on our gitlab-ci the tests run and coverage gets reported as zero percent on the commandline.

**Comment by xtiancapil** [comment]
I'm seeing this also when I run on our jenkins-ci

**Comment by dlkay0** [comment]
Same results in this environment from command-line  (1.2.0 works; 2.0.0 reports zero hits)

Linux 904f5451827d 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

Command-line: 
dotnet restore && dotnet build --no-restore && dotnet test netcore2Hello.Test/ --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

using a different output format has no effect

**Comment by tonerdo** [comment]
Hi @Razzeee @xtiancapil @dlkay0 did #110 fix this?

**Comment by Razzeee** [comment]
#110 is an issue and thus doesn't fix stuff ;)

So you're saying I should try https://github.com/tonerdo/coverlet/issues/110#issuecomment-392688542 excluding the test adapter?

**Comment by tonerdo** [comment]
@Razzeee yes that's what I meant. Sorry for not being more specific

**Comment by Razzeee** [comment]
SO I did run `dotnet test /p:CollectCoverage=true /p:Exclude=[NUnit3.TestAdapter]*` on our linux CI server and it still reports 0% with version 2.0

**Comment by tonerdo** [comment]
Thanks for the update @melih154, I'm still unable to reproduce this in Linux

**Comment by dlkay0** [comment]
@aburgett87 
I switched from 2.0.5 based on ubuntu to 2.0.7 based on official [dotnet-docker:2.0.7-sdk-2.1.200](https://github.com/dotnet/dotnet-docker/blob/master/2.0/sdk/stretch/amd64/Dockerfile) and excluded NUnit3.TestAdapter (/p:Exclude=[NUnit3.TestAdapter]*) and the combination yielded a valid coverage report using coverlet 2.0.0. 

I've also managed to get colored source to display.

**My issue is resolved.**

**Comment by Razzeee** [comment]
It's working for us again. Using the latest version in combination with dotnet core 2.1
