### ISSUE TITLE
Test full .NET Framework class lib using Sdk style csproj

### ISSUE THREAD

**Issue by sgwatgit** [tonerdo/coverlet#115]
Hello,

Thanks for the project, I tested it out on a .net standard 2.0 class lib and it worked great out of the box.

I was wondering if my unique scenario is potentially supported.

I have converted my .NET framework class libraries, which target .NET 4.6.1 to use the Sdk `.csproj` format.

Example
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    <PackageReference Include="RestSharp" Version="106.1.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
```

So this project uses `PackageReference`, targets .net 4.6.1 and builds / runs just fine.
I reference it in my Test project which uses the traditional csproj and doesn't use `PackageReference`.

When I run the tests (using xUnit) in Visual Studio 2017 or at the command line using `dotnet test` the tests are run and the results are displayed.

Example
```
$ dotnet test
Build started, please wait...
Build completed.

Test run for D:\dev\company\company\Company.Tests\bin\Debug\Company.Tests.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 7. Passed: 7. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.2361 Seconds
```

When I run `$ dotnet test //p:CollectCoverage=true //p:CoverletOutputFormat=opencover` (`//` escapes `/` in git bash) I get this response.

```
Starting test execution, please wait...
[xUnit.net 00:00:00.2213043] Skipping: Company.Tests (could not find dependent assembly 'xunit.core, Version=2.0.0')
No test is available in D:\dev\company\company\Company.Tests\bin\Debug\Company.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

More can be read about using the Sdk project format with .NET full framework
https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/
https://github.com/hvanbakel/CsprojToVs2017
https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md

**Comment by RockfordSP** [comment]
Also having issues with a .Net Core application targeting net461, though in my case all tests run and complete successfully but no code coverage is calculated.

```
Starting test execution, please wait...

Total tests: 77. Passed: 77. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.4099 Minutes

Calculating coverage result...
  Generating report 'D:\...\coverage.json'

+--------+--------+--------+--------+
| Module | Line   | Branch | Method |
+--------+--------+--------+--------+
```

**Comment by tonerdo** [comment]
Hi @RockfordSP and @sgwatgit at this moment Coverlet has been tested with only .NET Core applications that target `netcoreapp` and `netstandard`. It should work with the full .NET framework with only minor adjustments but it's currently not on my immediate radar

**Comment by jessekingf** [comment]
@tonerdo - I assume it is still the case that .net framework is still not supported?

**Comment by tonerdo** [comment]
@jessekingf the latest release now does
