### ISSUE TITLE
Coverage is 0% even thou tests are run - Adding more tests alleviates the problem

### ISSUE THREAD

**Issue by TLogik** [tonerdo/coverlet#118]
I have a codebase with a lot of integration tests but only very few Unit tests.
If i run the Unit tests only i see unexpected behaviour.

**Scenario 1:**
Running only a single Unittest yields:
`
Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.6818 Seconds
`

| Module                 | Line | Branch | Method |
|------------------------|------|--------|--------|
| ApplicationLogging.Dal | 0%   | 0%     | 0%     |

I would expect a very low coverage but not zero since one test is passing and is actually testing a CTOR for ArgumentException.

Expectation: A very low coverage.
Unexpected: No coverage at all.

**Scenario 2:**
I add another simple CTOR test that validates setting a field property.
`
Total tests: 2. Passed: 2. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.6821 Seconds
`

| Module                 | Line | Branch | Method |
|------------------------|------|--------|--------|
| ApplicationLogging.Dal | 2.3% | 2.2%   | 3.9%   |

Expectation. A low coverage.
Unexpected: The bump from 0% in Scenario 1 to the results in Scenario 2:

**Scenario 3:**
I add another test to check for CTOR ArgumentException:
`
Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.6821 Seconds
`

| Module                 | Line | Branch | Method |
|------------------------|------|--------|--------|
| ApplicationLogging.Dal | 2.3% | 2.7%   | 3.9%   |

Expectation:
Slightly increased Branch coverage.
Unexpected: None.

**Project Info**
Net core/standard 2.0
Coverlet 2.0
Microsoft.NET.Test.Sdk 15.7.2

**Comment by tonerdo** [comment]
HI @TLogik, are you saying the coverage results you're getting aren't accurate?

**Comment by TLogik** [comment]
Hi @tonerdo 
> are you saying the coverage results you're getting aren't accurate?

Well that is what i am implying at least:-)
**Scenario 1** has a coverage of 0% even thou the Unittest does in fact test an input parameter. The test Asserts an exception is thrown.
I would expect some kind of decimal value, especially because **Scenario 2** that is testing if a property is set increases the coverage significantly.

**Comment by tonerdo** [comment]
@TLogik try out the latest release https://www.nuget.org/packages/coverlet.msbuild/2.1.0, it contains performance improvements to ensure that all data is captured

**Comment by SlowLogicBoy** [comment]
I'm having similar issue. I'm using 2.2.1 coverlet.msbuild, it show that my class constructor is on 0% line coverage even though it's fully covered, and opencover shows 100% of line coverage.

**Comment by tonerdo** [comment]
@SlowLogicBoy please try the new releases:

Coverlet Global Tool: https://www.nuget.org/packages/coverlet.console/1.2.0
Coverlet MSBuild: https://www.nuget.org/packages/coverlet.msbuild/2.3.0

**Comment by SlowLogicBoy** [comment]
@tonerdo It works now. Thanks.
