### ISSUE TITLE
System.IO.FileNotFoundException: No test is available in <myassembly.dll> when run from TFS

### ISSUE THREAD

**Issue by DominicBurford** [tonerdo/coverlet#12]
I am getting the error 

"System.IO.FileNotFoundException: No test is available in <myassembly.dll>. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again." 

...when running a batch script from TFS that executes coverlet.

I have added a reference to the "Microsoft.NET.Test.Sdk" assembly to my project (it is added by default by Visual Studio). 

My project is ASP.NET Core 2.0 Razor Pages
Visual Studio 2017 15.3
MSBUILD 15
Team Foundation Services 2015

It runs without any errors when executed directly from the build server from the command-line. The error only occurs when executed from our TFS build.

**Comment by tonerdo** [comment]
Can you try executing the tests from TFS build with coverage disabled? I ask because this doesn't seem like a coverlet issue

**Comment by DominicBurford** [comment]
I don't have code coverage enabled as we don't have the Enterprise version. I'm not using any of the TFS test tasks as I'm using **dotnet test** for all our .NET Core testing requirements including code coverage.

**Comment by DominicBurford** [comment]
I have managed to get this working. 

If running coverlet from inside TFS you need to explicitly specify the project and suppress it from doing a build and restore.

For example

dotnet test "Project.Tests.csproj" --no-build --no-restore /p:CollectCoverage=true

**Comment by tonerdo** [comment]
Hmmm...that's very weird. @OneCyrus seemed to have gotten it working without any hassles. See #5

**Comment by DominicBurford** [comment]
Possibly TFS doesn't have access to the same environment as when executed from the command-line.
