### ISSUE TITLE
2.0.1 Confusion

### ISSUE THREAD

**Issue by mcblair** [tonerdo/coverlet#121]
2.0.1 was available via nuget the other day, upgraded and it broke some of our scripts. coverage.xml is now opencover.coverage.xml.

In addition, there isn't a github release or tag - or any documentation.

I see 2.0.1 also changed coverage output (in good ways) to consider ExcludeFromCodeCoverage - this is documented in the README edit 3 days ago but not the xml file name change...

Just wondering what's up, thanks!

**Comment by tonerdo** [comment]
Hiya @mcblair, thanks for calling my attention to this and apologies for the confusion. Here are the release notes: https://github.com/tonerdo/coverlet/releases/tag/v2.0.1
