### ISSUE TITLE
Powershell with /p:ExcludeByFile do not works

### ISSUE THREAD

**Issue by hack2root** [tonerdo/coverlet#122]
Powershell script
By adding command `/p:ExcludeByFile=\"**/MyFun*.cs,**/*Test*.cs,**/*Exception*.cs,**/*Attribute*.cs\"` to 

`& dotnet test --configuration Release --no-build Build.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover`

I manage to break generation of the report file, if I removes `/p:ExcludeByFile=\"...\"` everything works
I tried with no success:
```

/p:ExcludeByFile=\"**/MyFun*.cs,**/*Test*.cs,**/*Exception*.cs,**/*Attribute*.cs\"
/p:ExcludeByFile="**/MyFun*.cs,**/*Test*.cs,**/*Exception*.cs,**/*Attribute*.cs"
/p:ExcludeByFile=\"**\/MyFun*.cs,**\/*Test*.cs,**\/*Exception*.cs,**\/*Attribute*.cs\"
/p:ExcludeByFile=\"**\MyFun*.cs,**\*Test*.cs,**\*Exception*.cs,**\*Attribute*.cs\"
/p:ExcludeByFile="**\MyFun*.cs,**\*Test*.cs,**\*Exception*.cs,**\*Attribute*.cs"
```

`/p:ExcludeByFile` just not works

https://ci.appveyor.com/project/hack2root/build/build/1.0.0.222-master
https://ci.appveyor.com/project/hack2root/build/build/1.0.0.223-master

Why not to use SonarScanner format 

`/d:sonar.coverage.exclusions="**/MyFun*.cs,**/*Test*.cs,**/*Exception*.cs,**/*Attribute*.cs" `

for `/p:ExcludeByFile`, for example:

`/p:ExcludeByFile="**/MyFun*.cs,**/*Test*.cs,**/*Exception*.cs,**/*Attribute*.cs"`

My build script:

```
& packages/dotnet-sonarscanner begin /d:sonar.login="$env:SONARCLOUDTOKEN" /k:"build-core" /d:sonar.host.url="https://sonarcloud.io" /n:"build" /v:"1.0" /d:sonar.cs.opencover.reportsPaths="Build.Tests/coverage.opencover.xml" /d:sonar.coverage.exclusions="**/MyFun*.cs,**/*Test*.cs,**/*Exception*.cs,**/*Attribute*.cs" /d:sonar.organization="hack2root-github" /d:sonar.sourceEncoding="UTF-8"
& dotnet build --configuration Release
& dotnet test --configuration Release --no-build Build.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
& packages/dotnet-sonarscanner end /d:sonar.login="$env:SONARCLOUDTOKEN"
& packages/csmacnz.Coveralls --opencover -i Build.Tests/coverage.opencover.xml
```

**Comment by tonerdo** [comment]
I'd expect this to just work since you're using a regular globbing pattern. @ido-namely can you please take a look? Thanks

**Comment by tonerdo** [comment]
Hi @hack2root, do you get an error or does it just not work? Is your issue similar to #182?

**Comment by SlowLogicBoy** [comment]
I'm having same issue. Also I use `test.targets` file for test properties:
```xml
    <PropertyGroup>
        <!-- Properties for code coverage -->
        <CollectCoverage>true</CollectCoverage>
        <CoverletOutputFormat>opencover</CoverletOutputFormat>
        <ExcludeByFile>**/*.Designer.cs</ExcludeByFile>
    </PropertyGroup>
```
and this doesn't work too. I've tried solutions in #182 too, in powershell, cmd and bash. (in bash instead of using `/p:` I have to use `-p:`)

**Comment by tonerdo** [comment]
@SlowLogicBoy I'll like to know if you get an error or if you just notice that the files don't get excluded

**Comment by SlowLogicBoy** [comment]
@tonerdo Files didn't get excluded, tried various patterns for these. Exclude doesn't work also.

**Comment by orkenstein** [comment]
` /p:ExcludeByFile` definitely doesn't work in shell.

**Comment by psfinaki** [comment]
So what am I supposed to do if I want to exclude some Migrations folder? 

Something like
`dotnet test Code /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="**/Migrations/**"`

**Comment by yowl** [comment]
I'm a bit confused with the state of this. Does this also affect coverlet.exe and is the workaround to use absolute paths?

**Comment by yowl** [comment]
I aslo note I think, that with absolute paths on windows its funny about the case of the drive letter and I need to exclude both d:\ and D:\

**Comment by stanislav-trifan** [comment]
still not working on .net  3.1.411
