### ISSUE TITLE
GeneratedCodeAttribute

### ISSUE THREAD

**Issue by kimbell** [tonerdo/coverlet#125]
Tried out this functionality and love the approach. 

When running the coverage through coverlet, I noticed a significant drop compared to when running under Resharper. 

My project has a lot of auto-generated code for WCF and Swagger clients. These are marked with the GeneratedCodeAttribute. It would be a good idea to add this to the list of attributes that excludes code.

**Comment by tonerdo** [comment]
Hi @kimbell, take a look at this https://github.com/tonerdo/coverlet#excluding-from-coverage to get an idea how to ignore your generated code. Let me know if you need any help

**Comment by kimbell** [comment]
We have multiple projects and we use cake as the build system. One of our goals is to keep the cake file the same across each project so that it's easy to update things. 

If we need to exclude namespaces, we would need some way of keeping that configuration external to the cake file. It's possible, but seems like a bit of a hassle. This would also mean that you would have to ensure that the code is generating code into namespaces you don't use for your custom code. This is also possible, but not very intuitive. 

Would it be possible to provide as list of attributes that should be used for exclusion on the command line? 

What is the argument for not excluding generated code?

**Comment by tonerdo** [comment]
Why not just exclude the generated files using the `ExcludeByFile` property? https://github.com/tonerdo/coverlet#source-files

**Comment by kimbell** [comment]
ExcludeByFile is an option, but I would still have to maintain a list for each project if I am to share the build configuration. Doable, but nice to avoid if possible.

**Comment by MarcoRossignoli** [comment]
You can now use `p:ExcludeByAttribute` feature https://github.com/tonerdo/coverlet/blob/589e210e740bbf243cb0e57acbff7bf4e1ea8a66/Documentation/MSBuildIntegration.md#attributes
