### ISSUE TITLE
Only .dll references are being covered

### ISSUE THREAD

**Issue by laurynasr** [tonerdo/coverlet#126]
When targeting .net framework (i.e. net471), the output type of an asp.net core application is .exe, which is then referenced by tests. Coverlet ignores everything except for .dll references: https://github.com/tonerdo/coverlet/blob/3d86243d272e92b96e04d3eaa5942c0c25d85001/src/coverlet.core/Helpers/InstrumentationHelper.cs#L18

**Comment by tonerdo** [comment]
Hi @laurynasr thanks for reporting this. Will have it looked into
