### ISSUE TITLE
Cyclomatic Complexity

### ISSUE THREAD

**Issue by yuyixg** [tonerdo/coverlet#132]
ReportGenerator Cyclomatic Complexity not involve

**Comment by Thomathan** [comment]
I assume what the OP is asking for is if cyclomatic complexity is on the road map.

I looked at the the OpenCoverReporter and CoberturaReporter and both hard code complexity to 0.

So are there any plans to add this into coverlet? NPath complexity for OpenCover too?

**Comment by tonerdo** [comment]
@Thomathan, there are plans to add it. However, more serious bug fixes and crucial feature additions get more priority

**Comment by NorekZ** [comment]
@yuyixg works in 1.2.2, issue can be closed
