### ISSUE TITLE
Cake Build Addin Contribution

### ISSUE THREAD

**Issue by Romanx** [tonerdo/coverlet#136]
Hey there,

Thanks for the great project and all the hard work. I've been using it for my project and wanted to integrate it neatly with my exiting [cake build](https://cakebuild.net) script so I wrote an addin to do just that. You can find it here [Cake.Coverlet](https://github.com/Romanx/Cake.Coverlet)

It'd be great if you could add it to your readme so others could find it.

Thanks

**Comment by tonerdo** [comment]
Awesome, thanks @Romanx. Feel free to send in a PR for that
