### ISSUE TITLE
Unable to get started with coverlet with xUnit in a .NET Core 2.0 console application

### ISSUE THREAD

**Issue by ivansams** [tonerdo/coverlet#138]
I would like to make use of coverlet to check unit test coverage in our .NET Core 2.0 projects, which already have a great number of xUnit unit tests.

I am following the readme carefully but the `coverage.json` file is not generated and I'm not sure why as setup is mostly automatic and there are no error messages. I apologise for getting stuck at the most basic of levels, but there must be an issue with the coverlet documentation, at least.

To reproduce:

1. Create a new .NET Core console application project using Visual Studio 2017.

2. Create a new class under test, such as:

```
    public class TruthTeller
    {
        public bool TellTruth()
        {
            return true;
        }
    }
```

3. Create an xUnit test project within the solution and give it a reference to the first project.

4. Create a test for the method created in (2) such as:

```
    public class TruthTellerTests
    {
        [Fact]
        public void TellTruth_MethodCall_ReturnsTrue()
        {
            var truthTeller = new TruthTeller();
            var result = truthTeller.TellTruth();
            Assert.True(result);
        }
    }
```

5. Following coverlet readme, open package manager, select the xUnit project as the Default Project and run:

```
    Install-Package coverlet.msbuild
```

6. From a command prompt at the directory of the xUnit project, run the following command:

```
    dotnet test /p:CollectCoverage=true
```

7. Search for the `coverage.json` file - it's nowhere to be found. 

The source of the above unsuccessful experiment is in the following repository:

https://github.com/ivansams/CoverletCheck

**Comment by tonerdo** [comment]
Hi @ivansams, I took a look at your repro project and noticed that your test project `CoverletCheckTests` does not have a project reference to `CoverletCheck`. This is necessary for Coverlet to be able to find the assembly to instrument

**Comment by ivansams** [comment]
Sorry @tonerdo I must not have committed the code. In Step 3 I do add a reference in the xUnit project to the project under test. I have updated the repo to reflect this - could you see if it works for you now?

**Comment by andre-castro-garcia** [comment]
@ivansams I have passed for this problem, in that case i have forgot to add 'coverlet.msbuild' package in my .csproj

I think that's the problem, add a new reference to your .csproj and run coverage again:

**Reference**
`<PackageReference Include="coverlet.msbuild" Version="2.0.1" />`

**Project File**
https://github.com/ivansams/CoverletCheck/blob/master/CoverletCheckTests/CoverletCheckTests.csproj

Andre Garcia

**Comment by janaka** [comment]
I'm having a similar experience on macOS. .NET Core runtime 1.1 + .NET Core SDK v2.x.

**Comment by janaka** [comment]
Interesting, just cloned @ivansams repo linked above, added the coverlet ref, ran the dotnet test ... command and it seems to have done more. Showing me

`Calculating coverage result...
  Generating report '/Users/janaka.abeywardhana/code-projects/CoverletCheck/CoverletCheckTests/coverage.json'`

**Comment by tonerdo** [comment]
@janaka @ivansams as @andre-castro-garcia rightly noted, coverlet isn't directly built into the `dotnet test` pipeline, you'll have to manually include it by referencing the `coverlet.msbuild` NuGet package

**Comment by janaka** [comment]
@tonerdo fwiw in the real project I was testing in, I did have the package referenced.

**Comment by janaka** [comment]
In @ivansams project for me it seems to hang on that report generation message. Is this known to work on macOS?

**Comment by ivansams** [comment]
Not sure how I missed that reference add. All working for me now. Thanks for your help all, especially @andre-castro-garcia . I'm afraid I don't know about MacOS @janaka , this is probably a different issue.

**Comment by tonerdo** [comment]
@janaka how large is the project you're trying to get coverage for?

**Comment by paratroid** [comment]
Apologises to revive this old thread but I appear to be getting the same thing happening, and this thread is the best match for what I've found vs anything else available online. I'm hoping it's just me missing something really simple in the set-up:

**Reproduction steps:**

- Install coverlet 2.6.0 (latest version as of 02/04/19) using `dotnet add package coverlet.msbuild`
- In the root of the solution run `dotnet test .\path-to-test.csproj /p:CollectCoverage=true`

This appears to run ok in Powershell however there is no coverage report that is generated from this in the root of the directory (have checked in other folders too - no coverage report). Additionally there is no coverage output in the Powershell console window either; unsure if it does output to the console however. 

**Additional information**
- .NET core tests are all using xunit
- .NET core version is 2.2
- OS: Windows
- Coverlet version: 2.6.0

I can confirm that my .\path-to-test.csproj file has a reference to coverlet in it's package references. I have also trying installing coverlet console using `dotnet tool install --global coverlet.console` and run `coverlet .\path-to-test.csproj --target "dotnet" --targetargs "test"`. Interestingly this does produce an output coverage file and console coverage output, however both are empty. 

I have a suspicion that my issue could be to do with the way in which my project directories are set up. The format is:

Root
--Folder/Logic1.csproj
--Folder/Tests1.csproj
--Folder/Logic2.csproj
--Folder/Tests2.csproj
MySolution.sln

I run the `dotnet test .\Folder\TestsX.csproj /p:CollectCoverage=true` when performing tests. Hope this is enough information, can anyone advise on how to produce code coverage? I've also attached what I'm seeing as output in Powershell.

![image](https://user-images.githubusercontent.com/49206034/55423430-ca97ee80-5575-11e9-826e-10020505cb73.png)

![image](https://user-images.githubusercontent.com/49206034/55423630-35e1c080-5576-11e9-8a29-bef004cdc587.png)

**Comment by leelaprasadv** [comment]
@paratroid

Faced the same issue while using coverlet version 2.6.0 with .net core 2.0.

Just use the previous version of coverlet 2.5.1 with an additional parameter 

```
/p:Exclude="[xunit*]*"
```

Hope this helps!

**Comment by Flash619** [comment]
Just ran into this same issue today an @leelaprasadv comment fixed it for me. Is there a more up to date solution?

**Comment by MarcoRossignoli** [comment]
> Just ran into this same issue today an @leelaprasadv comment fixed it for me. Is there a more up to date solution?

If you upgrade to last version 2.7.0 should fix without any filter.
