### ISSUE TITLE
Not finding coverageresults

### ISSUE THREAD

**Issue by arunprasathv** [tonerdo/coverlet#139]
@tonerdo 

After running the command, I got this message and I don't see any coverage results json file. I would expect to see the coverage results even when Test Run Failed. 

dotnet test /p:CollectCoverage=true

Total tests: 32. Passed: 28. Failed: 4. Skipped: 0.
Test Run Failed.
Test execution time: 16.6057 Seconds

**Comment by tonerdo** [comment]
Hi @arunprasathv, because of msbuild limitations the coverage task will not be executed if your tests fail and as a result no coverage result file will be generated

**Comment by andre-castro-garcia** [comment]
Hi @arunprasathv,

Try this format
`/p:Exclude="[NUnit3.*]*"`

In my case I would like to exclude NUnit3TestAdapter assembly and all types.

See here:
https://bitbucket.org/andre-castro-garcia/ducktales/src

Andre Garcia

**Comment by arunprasathv** [comment]
@andre-castro-garcia In my case its a dependency and generates assembly under \bin\Debug\netcoreapp2.0,i tried this option as well but it still takes the assembly, at least i see in the report.

**Comment by arunprasathv** [comment]
It works, just changed the pattern instead of NUnit3.* changed to NUnit*

**Comment by andre-castro-garcia** [comment]
Hi @arunprasathv,

My test project generates an assembly **Nunit3.TestAdapter.dll** to the same folder as your project (bin\Debug\netcoreapp2.0). 

If i run the coverage **without a 'Exclude'** param he instrument a NUnit3 assembly as well, see:

```
Iniciando execução de teste, espere...
NUnit Adapter 3.10.0.21: Test execution started
Running all tests in C:\temp\ducktales\test\ducktales.tests\bin\Debug\netcoreapp2.0\ducktales.tests.dll
NUnit3TestExecutor converted 7 of 7 NUnit test cases
NUnit Adapter 3.10.0.21: Test execution complete

Total de testes: 7. Aprovados: 7. Com falha: 0. Ignorados: 0.
Execução de Teste Bem-sucedida.
Tempo de execução de teste: 22,1852 Segundos

Calculating coverage result...
  Generating report 'C:\temp\ducktales\test\ducktales.tests\coverage.json'

+--------------------+--------+--------+--------+
| Module             | Line   | Branch | Method |
+--------------------+--------+--------+--------+
| ducktales.api      | 100%   | 75%    | 100%   |
+--------------------+--------+--------+--------+
| ducktales.data     | 100%   | 100%   | 100%   |
+--------------------+--------+--------+--------+
| ducktales.models   | 98,1%  | 88,9%  | 100%   |
+--------------------+--------+--------+--------+
| NUnit3.TestAdapter | 41,9%  | 35%    | 56,4%  |
+--------------------+--------+--------+--------+

+---------+--------+---------+--------+
|         | Line   | Branch  | Method |
+---------+--------+---------+--------+
| Average | 85%    | 74,725% | 89,1%  |
+---------+--------+---------+--------+
```

Run coverage **with 'Exclude'** param he ignores NUnit3 assembly, see:

```
Iniciando execução de teste, espere...
NUnit Adapter 3.10.0.21: Test execution started
Running all tests in C:\temp\ducktales\test\ducktales.tests\bin\Debug\netcoreapp2.0\ducktales.tests.dll
NUnit3TestExecutor converted 7 of 7 NUnit test cases
NUnit Adapter 3.10.0.21: Test execution complete

Total de testes: 7. Aprovados: 7. Com falha: 0. Ignorados: 0.
Execução de Teste Bem-sucedida.
Tempo de execução de teste: 1,4433 Segundos

Calculating coverage result...
  Generating report 'C:\temp\ducktales\test\ducktales.tests\coverage.json'

+------------------+--------+--------+--------+
| Module           | Line   | Branch | Method |
+------------------+--------+--------+--------+
| ducktales.api    | 100%   | 75%    | 100%   |
+------------------+--------+--------+--------+
| ducktales.data   | 100%   | 100%   | 100%   |
+------------------+--------+--------+--------+
| ducktales.models | 98,1%  | 88,9%  | 100%   |
+------------------+--------+--------+--------+

+---------+-------------------+-------------------+--------+
|         | Line              | Branch            | Method |
+---------+-------------------+-------------------+--------+
| Average | 99,3666666666667% | 87,9666666666667% | 100%   |
+---------+-------------------+-------------------+--------+
```

Another interestelly thing, i run these commands with a Git Bash, the format of command changes to:

`$ dotnet test test/ducktales.tests/ducktales.tests.csproj -p:CollectCoverage=true -p:Exclude="[NUnit3.*]*"`

I think that's occurs because Git Bash simulates a unix terminal. :)

Andre Garcia

**Comment by arunprasathv** [comment]
@andre-castro-garcia This issue has been resolved.
