### ISSUE TITLE
Class constructor not covered

### ISSUE THREAD

**Issue by latop2604** [tonerdo/coverlet#142]
I use coverlet with opencover format and generate html with reportgenerator (as global-tool on linux 🥇 ).

But it seem no one of my constructor was reported as covered. See screenshot below.

![image](https://user-images.githubusercontent.com/2058133/42404933-7128f9d6-818e-11e8-80ab-4c6e148318ab.png)

This point aside, everything worked as expected on the first try (on osx and docker)

**Comment by andre-castro-garcia** [comment]
I have noted this on my project, the "opencover" file  format (and others) do not show the coveraged constructor lines, but he still counting these lines in the calculated report.

@latop2604 you can see this behavior on these projects:
https://sonarcloud.io/code?id=ducktales
https://bitbucket.org/andre-castro-garcia/ducktales

Coverage report:
![image](https://user-images.githubusercontent.com/35741698/42576887-c36509ec-84f9-11e8-9911-e252a81deb2a.png)

Lines coverage:
![image](https://user-images.githubusercontent.com/35741698/42576992-0b3fa984-84fa-11e8-9efc-8a67e6dd229c.png)


Andre Garcia

**Comment by latop2604** [comment]
Did you try to add more line in your constructor ? I think that the line of code number will not increase.
