### ISSUE TITLE
/p:CoverletOutputDirectory= not working

### ISSUE THREAD

**Issue by SahinOzdemir** [tonerdo/coverlet#144]
the param /p:CoverletOutputDirectory= is still outputting the data into the root of the project.
It's regarding version 2.10 and I was wondering if this could be fixed

**Comment by jp7677** [comment]
Try this one:
`/p:CoverletOutput=path/reportfile.xml`

See the last sentence in this paragraph: https://github.com/tonerdo/coverlet/blob/master/README.md#coverage-output

**Comment by SahinOzdemir** [comment]
Thnx! Abny idea when it will be possible to merge all coverage files from different projects into 1 file?

**Comment by tonerdo** [comment]
That's currently being worked on in #123
