### ISSUE TITLE
2.1.0 output path change causes issues with Cake.Coverlet

### ISSUE THREAD

**Issue by Romanx** [tonerdo/coverlet#146]
Hi there,

The recent update changed `CoverletOutputName` and `CoverletOutputDirectory` to be one property `CoverletOutput` which broke Cake.Coverlet which is no big problem. However the change has caused some inadvertent problems with one of the features which is transforming the filename before passing the settings to coverlet.

If you share the same coverlet settings between two distinct test runs then you have to have distinct filenames so they don't overwrite each other. To support this we added an OutputNameTransformer which gets called before running dotnet test and so can transform the filename at the time. We provide a default transformer to add the current utc datetime to the filename for example. This worked great in the old world as when a filename was provided you automatically added the format and extension to the end of it. 

Now when a path is provided the filename is taken as is and the format and extension is not added. Would you be opposed to a PR adding a check for if an extension exists on the filepath and if it doesn't then adding the format + extension back again?

I would add the extension to the Cake.Coverlet side but this wouldn't work when requesting mutliple output formats with different extensions like opencover and json.

Hopefully this makes sense!

**Comment by tonerdo** [comment]
Hi @Romanx, simply end the path you provide `CoverletOuput` with `/` to specify a directory. Apologies for not documenting this, will fix in a bit

**Comment by Romanx** [comment]
Hi @tonerdo,

I think i was a bit muddled in my post. It's less about the directory as we want to provide a name for example `coverlet-2018-07-12-15-06-07` but since we're providing a name we don't get the extension added by coverlet. It'd be nice if there was an option for coverlet to add the extension if one wasn't provided.
