### ISSUE TITLE
Regex to get coverage results

### ISSUE THREAD

**Issue by gach87** [tonerdo/coverlet#148]
Hello. I'm  having trouble trying to get a regex to get coverage results from the terminal output. Can you help me with some example?.

Thanks for the wonderful project.

**Comment by maheshpr** [comment]
Hi @ithepunisher ,
I am using Gitlab.com CI. The regex is not working for me.

**Comment by kwentinn** [comment]
Have you tried removing the forward slashes in the regex in gitlab ? Try `ProjectName.*?(\d+(?:\.\d+)?)%`. It should work!

**Comment by cRUSHER-HLG** [comment]
Guys are you sure? Im also using gitlab. I use these command for my (xUnit) unit tests: 
dotnet test /p:CollectCoverage=true /p:Exclude='[xunit*]*' 

This is my full output of the command above:
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 7. Passed: 7. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.4534 Seconds

Calculating coverage result...
  Generating report '/builds/private-projects/prolearnplatform/onlincecps/Applications/server/compilerendpoint/Tests/coverage.json'

+----------------------+-------+--------+--------+
| Module               | Line  | Branch | Method |
+----------------------+-------+--------+--------+
| CompilerEndpoint     | 6.3%  | 18%    | 11.6%  |
+----------------------+-------+--------+--------+
| CompilerEndpointTest | 97.8% | 100%   | 87.5%  |
+----------------------+-------+--------+--------+

+---------+-------+--------+--------+
|         | Line  | Branch | Method |
+---------+-------+--------+--------+
| Total   | 7.9%  | 18%    | 13.9%  |
+---------+-------+--------+--------+
| Average | 3.95% | 9%     | 6.95%  |
+---------+-------+--------+--------+

Job succeeded

**Comment by MarcoRossignoli** [comment]
can you try with the tips here https://github.com/tonerdo/coverlet/issues/284?
I've open a issue for this problem if you want say something https://github.com/tonerdo/coverlet/issues/542

Feel free to close if solved.

**Comment by MarcoRossignoli** [comment]
Close for stale.
Feel free to re-open if needed.
