### ISSUE TITLE
NUnit integration issue.

### ISSUE THREAD

**Issue by AlexanderButs** [tonerdo/coverlet#15]
Hi.

First of all thanks a lot for Your initiative to write cross platform coverage library :) I've been using OpenCover and been dreaming about cross platform analogue :)  

I have NUnit test project and try to integrate coverlet, but get an error:
...
Total tests: 13. Passed: 13. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.4340 Seconds

Calculating coverage result...
C:\Users\Alexander\.nuget\packages\coverlet.msbuild\1.0.0\build\netstandard2.0\coverlet.msbuild.targets(19,5): error : Could not find file 'C:\Users\Alexander\AppData\Local\Temp\TicTacToe_1a57e94d-46ac-44ce-9320-99f8c74d6267'. [C:\Work\TicTacToe\test\TicTacToe.Test\TicTacToe.Test.csproj]

I tried Hanselman's project and it works well.
You can find my project here https://github.com/AlexanderButs/TicTacToe
Thoughts?
Thanks one more time for great job.

**Comment by tonerdo** [comment]
@AlexanderButs thanks for opening this up. #11 fixes this issue and a new NuGet package will go out within 24 hours

**Comment by AlexanderButs** [comment]
Thanks. It works now.
