### ISSUE TITLE
Fix MSBuild property names

### ISSUE THREAD

**Issue by alexanderkozlenko** [tonerdo/coverlet#151]
MSBuild properties declared in the NuGet package should have unique names to ensure they will not intersect with the common or custom project-level properties. Here is an example of possible naming for all the used properties:

| Current | Suggested |
| --- | --- |
| `CollectCoverage` | `CoverletEnableCoverage` |
| `CoverletOutput` | `CoverletOutputPath` |
| `CoverletOutputFormat` | `CoverletOutputFormat` |
| `Exclude` | `CoverletExclude` |
| `ExcludeByAttribute` | `CoverletExcludeByAttribute` |
| `ExcludeByFile` | `CoverletExcludeByFile` |
| `Include` | `CoverletInclude` |
| `IncludeDirectory` | `CoverletIncludeDirectory` |
| `MergeWith` | `CoverletMergeWith` |
| `SingleHit` | `CoverletSingleHit` |
| `Threshold` | `CoverletThreshold` |
| `ThresholdType` | `CoverletThresholdType` |
| `ThresholdStat` | `CoverletThresholdStat` |
| `UseSourceLink` | `CoverletUseSourceLink` |

**Comment by tonerdo** [comment]
This is massively backward incompatible. How do you propose we transition users?

**Comment by alexanderkozlenko** [comment]
I would suggest considering this not as a backward incompatible enhancement, but as a fix for initial design issue, which should be addressed ASAP. The transition could be done in the following way:

1. In 5.1.0 release add new properties with the same default values, redirect the previous properties to new in `InstrumentationTask` and `CoverageResultTask` tasks.
2. In 5.2.0 release start logging a build warning if one of the previous properties is initialized (i.e. used) or one of the required new properties is not initialized (a default value for the corresponding previous property is assumed).
3. In 6.0.0 release remove support for the previous properties completely.

**Comment by tonerdo** [comment]
I'm not quite sure I wanna change this for the sake of changing it. It doesn't seem to be causing any troubles and I don't want people to have to upgrade when they absolutely don't have to. I'll mark this as `as-designed` until enough people ask for it.

**Comment by MarcoRossignoli** [comment]
Close as-designed.
