### ISSUE TITLE
Is there any way to execute coverlet using dotnet vstest?

### ISSUE THREAD

**Issue by lira92** [tonerdo/coverlet#156]
The project that I am working has multiples assemblies with tests, I saw that is only possible to execute tests in multiples assemblies with dotnet vstest command. I want to execute the tests in multiples assemblies and generate an unified code coverage file.

**Comment by tonerdo** [comment]
@lira92 there's currently no way to generate a single result for multiple test assemblies

**Comment by tonerdo** [comment]
#36 tracks the progress on merging coverage results

**Comment by lira92** [comment]
@tonerdo thanks.
