### ISSUE TITLE
Is there a way to visualize what sections of the code are covered?

### ISSUE THREAD

**Issue by harindaka** [tonerdo/coverlet#160]
How can I visualize which code lines are covered and which are not? Something similar to what you see in the link below
https://github.com/inorton/XR.Baboon

**Comment by latop2604** [comment]
For vscode see https://www.hanselman.com/blog/AutomaticUnitTestingInNETCorePlusCodeCoverageInVisualStudioCode.aspx

You can use [ReportGenerator](https://github.com/danielpalme/ReportGenerator) for Html report (and other formats)
