### ISSUE TITLE
I there a way to output multiple formats

### ISSUE THREAD

**Issue by minuz** [tonerdo/coverlet#161]
Is there any way to output multiple formats? 
For instance, I would like to output in cobertura and open cover formats at the same time for integration on build server.

**Comment by tonerdo** [comment]
@minuz yes there is. If you're using the MSBuild package separate the formats using a comma (`,`), with the global tool specify the `--format` (or `-f`) option multiple times

**Comment by minuz** [comment]
@tonerdo thanks for the quick response. However, I've tried the following:

`λ dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura,opencover                                                                                                              `

But this is not working. If I duplicate the /p:CoverletOutputFormat, it only generates the later.

**Comment by rycornell** [comment]
I'm seeing the same behavior when running the tests on VSTS build server, using coverlet.msbuild version 2.0.1:

![image](https://user-images.githubusercontent.com/3660285/43519135-3e65e4e6-955c-11e8-8301-5133f2104e60.png)

**Comment by tonerdo** [comment]
@minuz @rycornell  the error is as a result of a limitation with MSBuild command line parsing. You have to escape comma separated property values.

```bash
dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\"
```

**Comment by minuz** [comment]
@tonerdo thanks!! I wasn't aware of that! It works now!

**Comment by raphaelquati** [comment]
I'm trying to run in VSTS, but no success.

I have used: 
```"/p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\""``` 
It doesn't work.

![image](https://user-images.githubusercontent.com/815086/44118248-df0f1fc2-9feb-11e8-81fe-ece0a36da088.png)

Checking my private agent logs:

C:\agent\_diag\Worker_20180814-210029-utc.log
```
{
      "inputs": {
        "command": "test",
        "publishWebProjects": "true",
        "projects": "**/*.Tests.csproj",
        "custom": "",
        "arguments": "-v diag \"/p:CollectCoverage=true /p:CoverletOutputFormat=\\\"cobertura,opencover\\\"\"",
        "publishTestResults": "true",
        "zipAfterPublish": "true",
        "modifyOutputPath": "true",
        "selectOrConfig": "select",
        "feedRestore": "",
        "includeNuGetOrg": "true",
        "nugetConfigPath": "",
        "externalEndpoints": "",
        "noCache": "false",
        "packagesDirectory": "",
        "verbosityRestore": "Detailed",
        "searchPatternPush": "$(Build.ArtifactStagingDirectory)/*.nupkg",
        "nuGetFeedType": "internal",
        "feedPublish": "",
        "externalEndpoint": "",
        "searchPatternPack": "**/*.csproj",
        "configurationToPack": "$(BuildConfiguration)",
        "outputDir": "$(Build.ArtifactStagingDirectory)",
        "nobuild": "false",
        "versioningScheme": "off",
        "versionEnvVar": "",
        "requestedMajorVersion": "1",
        "requestedMinorVersion": "0",
        "requestedPatchVersion": "0",
        "buildProperties": "",
        "verbosityPack": "Detailed",
        "workingDirectory": ""
      },
      "type": "task",
      "reference": {
        "id": "5541a522-603c-47ad-91fc-a4b1d163081b",
        "name": "DotNetCoreCLI",
        "version": "2.137.4"
      },
      "condition": "succeeded()",
      "continueOnError": true,
      "id": "26c6dddb-4a82-50b8-6720-1739ac4bd89c",
      "name": "DotNetCoreCLI3",
      "displayName": "dotnet test"
    },
```

In dotnet test log (diagnostic on)
![image](https://user-images.githubusercontent.com/815086/44118518-ccc7e302-9fec-11e8-9b06-13a643cae417.png)

**Comment by raphaelquati** [comment]
Now it's working, with a little modification:

``` /p:CollectCoverage=true "/p:CoverletOutputFormat=\"cobertura,opencover\"" ```

**Comment by leandroribeiro** [comment]
For someone that this information can be useful, on Windows =( do you need do this:
`"/p:CoverletOutputFormat=OUTPUT-TYPE-1**%2c**OUTPU-TYPE-2"`
Do you need replace comma [,] by [%2c]
