### ISSUE TITLE
Coverage file missing if >0 tests fail

### ISSUE THREAD

**Issue by danielthompson** [tonerdo/coverlet#162]
Thanks for your hard work; this is a great project!

I'm using this project to collect code coverage in a TFS 2018 CI build definition, using the dotnet test 2.0 task.

The behavior I'm seeing is that if all tests succeed, the coverage output file is generated. If at least one test fails, the coverage output file is not generated. 

Arguments passed to the task are:

--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

Is this the expected behavior given those arguments? If so, is there a way to generate the output file regardless of the number of tests failing?

Thanks,
Daniel

**Comment by tonerdo** [comment]
Hi @danielthompson this is expected behaviour. It's an MSBuild limitation that prevents the `Coverage` task from running when the previous unit test task fails. Unfortunately, I haven't found a way around it. However, you can use the global tool option which does not have this limitation

**Comment by danielthompson** [comment]
I see. That's a bummer, but thanks for the explanation.
