### ISSUE TITLE
Add support for executing coverage via SLN

### ISSUE THREAD

**Issue by mbenua-mparticle** [tonerdo/coverlet#165]
It's possible to construct a SLN that contains only test csproj files and then use that to execute all of those csprojs at once. When you then run `dotnet test all_my_tests.sln`, it will execute your test csprojs in parallel - which is an order of magnitude faster than iterating through, say, a list of all the test projects individually.

I would love to be able to collect coverage this way as well, using the stand-alone tool. Ideally something like:
`coverlet \tests.sln --target "dotnet" --targetargs "test tests.sln --no-build"`

It SORT of works now in that tests start executing. However, it has hiccups when it tries to generate the coverage.json files - probably because they do not have a unique nomenclature. The run abruptly ends with 
```
Calculating coverage result...
  Generating report 'C:\Users\mbenua\Documents\GitHub\server\coverage.json'

+--------+--------+--------+--------+
| Module | Line   | Branch | Method |
+--------+--------+--------+--------+
```

I suspect there's not a lot of work to get this scenario working, which would be an ENORMOUS perf improvement. Perhaps only as much as having the option to generate unique coverage filenames?

**Comment by tonerdo** [comment]
Hi @mbenua-mparticle, thanks for reporting this and I do agree it's will be a good improvement. Currently focusing on merging coverage results and will look into this once I get that out the door

**Comment by nishantkagrawal** [comment]
Is there any update on this yet? 

Can I run tests against multiple projects and create a combined result?

**Comment by ardalis** [comment]
Merging results seems to have been done 10 months ago. Now would like to be able to specify a single output file for a .sln so that I can run this from solution root:
```
dotnet test /p:CollectCoverage=true /p:MergeWith=CoverageResult.json
```
This would:
- Discover all tests
- Run all tests
- Collect coverage for all tests (and maybe drop the results into their respective folders as it does today)
- **New** Merge all test results into `CoverageResult.json` specified.

**Comment by MarcoRossignoli** [comment]
close because dup of https://github.com/tonerdo/coverlet/issues/357
For merge there is new sample in documentation https://github.com/tonerdo/coverlet/blob/master/Documentation/Examples.md
