### ISSUE TITLE
Coverage report is empty when working in single assembly

### ISSUE THREAD

**Issue by goldytech** [tonerdo/coverlet#168]
Hi,
As I'm following TDD, I had created .net core library project and reference the required the dlls like xunit and coverlet.msbuild 

In the same project I added a subfolder "Logic" where my actual code to be tested, is written. Also I have used
`ExcludeFromCoverage` attribute in my unit tests class.

Now when I run `dotnet test /p CollectCoverage=true` the unit tests are run but the coverage.json is empty. I don't understand why it is not picking up my Logic folder code. Is it mandatory I need to have a src folder and put my entire code to be tested in separate assembly and then reference it in my unit tests, I believe that should not be case. Correct me if I'm wrong.

Thanks

**Comment by tonerdo** [comment]
Hi @goldytech, at this time your code under test should reside in a project different from your test project
