### ISSUE TITLE
CoverletOutputFormat only accepts one format

### ISSUE THREAD

**Issue by FrankyBoy** [tonerdo/coverlet#170]
Hi!

Running as part of the `dotnet test` command ... as the documentation claims multiple output formats I wanted to try it out, added `/p:CoverletOutputFormat=json,lcov,opencover,cobertura`.

Result:

    MSBUILD : error MSB1006: Property is not valid.
    Switch: lcov

Removed, `lcov`, same result for `opencover`, removed that, same result for `cobertura`. So in short, no other format than `json` actually works here.

Cheers!

**Comment by FrankyBoy** [comment]
Further tests show: the problem is that only one format works at a time. so ` /p:CoverletOutputFormat=opencover` is fine,  `/p:CoverletOutputFormat=json,opencover` is not.

**Comment by FrankyBoy** [comment]
Looking further this is a result of [how /p separates parameters](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference):

> Specify each property separately, or __use a semicolon or comma__ to separate multiple properties

So msbuild interprets this as multiple properties. It appears to me that we got two solutions: escape the comma somehow, or use a different character to separate the values.

**Comment by tonerdo** [comment]
Take a look at the README, this is how you escape the comma

```csharp
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\"
```

**Comment by FrankyBoy** [comment]
That should really be mentioned in line 215 as well. The first mention is waaaay further down. Maybe there could be a generic sentence like "if you need to comma-separate stuff use escaped quotes" or so close to the top of the MSBuild paragraph (basically just moving the last paragraph up to the top).

**Comment by gforceg** [comment]
Powershell doesn't like all these msbuild /p args. To get comma separation to work I had to use the verbatim argument marker `--%`

dotnet test --% /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\"

**Comment by ardalis** [comment]
@gforceg Thanks! That verbatim operator for powershell needs to be prominent in the docs for this, @tonerdo, please!

**Comment by yanpitangui** [comment]
Omg, wasted so much time looking for this. Thank you @gforceg!

**Comment by AlbertoMonteiro** [comment]
@ardalis PR sent #1283
@gforceg Thanks so much for that bro!!!!

**Comment by Wind010** [comment]
What worked for me was using URL encoding:
```
/p:Threshold=99%2c99%2c99
```
