### ISSUE TITLE
Error MSB4057: The target "GenerateRestoreGraphFile" does not exist

### ISSUE THREAD

**Issue by losbaltica** [tonerdo/coverlet#173]
When I am trying to run inside latest coverlet folder

`dotnet add package coverlet.msbuild`

 I am getting the following error:

```
C:\coverlet-master\coverlet\build.proj : error MSB4057: The target "GenerateRestoreGraphFile" does not exist in the project.
Unable to create dependency graph file for project 'C:\coverlet-master\coverlet\build.proj'. Cannot add package reference.
```

I am not sure how to resolve it as coverlet is building and testing without any issue. However, I cannot add packages to dotnet as the file GenerateRestoreGraphFile is not existing.

**Comment by tonerdo** [comment]
Hi @losbaltica I'm not familiar with what `GenerateRestoreGraphFile ` refers to or what exactly you're trying to achieve. Are you having trouble using coverlet in your unit test project?

**Comment by losbaltica** [comment]
Hi @tonerdo, no I am just trying to add package coverlet.msbuild to dotnet. All I have done was installing coverlet to dotnet and based on readme add package. However at this step is failing and throw me "GenerateRestoreGraphFile" error.

**Comment by tonerdo** [comment]
@losbaltica this sounds like a NuGet restore error. Try deleting your `obj` and `bin` directories and perform another restore operation

**Comment by losbaltica** [comment]
@tonerdo  ok that fixes the issue! Cheers 👍

**Comment by tonerdo** [comment]
Awesome, glad to hear that
