### ISSUE TITLE
An option to ignore deprecated types/methods

### ISSUE THREAD

**Issue by safakgur** [tonerdo/coverlet#175]
Hi there, amazing project!

I was wondering if you would consider adding an option to ignore types/methods that are marked with `ObsoleteAttribute`. This way the functionality that is no longer maintained and is already discouraged to use wouldn't affect the coverage results.

**Comment by amweiss** [comment]
I was just about to create a pull request to exclude them by default. Always doing it will be a quick change, but you're probably right that an option is a good idea. If I did that, would it be merged?

https://github.com/tonerdo/coverlet/blob/47206b0ec9cf1a561756c441e44b8eeda7d2dace/src/coverlet.core/Instrumentation/Instrumenter.cs#L384 is the easy part from a quick look.

**Comment by amweiss** [comment]
See #195

**Comment by safakgur** [comment]
#233 and #477 resolved this, thank you @amweiss.
