### ISSUE TITLE
Coverage results are incorrect.

### ISSUE THREAD

**Issue by StillLearnin** [tonerdo/coverlet#18]
I have 3 projects and 21 tests all written against `Candle.Services`
```
Candle.DbContext
   |
   +--(References) Candle.Services
   |    |
   +----+--(References) Candle.Services.Tests

Calculating coverage result...
  Generating report 'C:\..\Candle.Services.Tests\coverage.json'

+------------------+----------+
| Module           | Coverage |
+------------------+----------+
| Candle.DbContext | 21%      |
+------------------+----------+
| Candle.Services  | 0%       |
+------------------+----------+
```

**Comment by StillLearnin** [comment]
Here's a sample:

For what it's worth, the `Get()` method is in a base class.

## Actual code being tested:
![image](https://user-images.githubusercontent.com/2912263/37909222-56b56924-30d8-11e8-8cbb-611f33eb3fb1.png)

## coverage.json relevant portion:
```
   "Candle.Services.SubjectsService/<ListAsync>d__3": {
    "System.Void Candle.Services.SubjectsService/<ListAsync>d__3::MoveNext()": {
     "33": 0,
     "34": 0,
     "35": 0,
     "36": 0,
     "37": 0
    }
   }
```

## Test with ListAsync() highlighted:
![image](https://user-images.githubusercontent.com/2912263/37909303-84c77fa0-30d8-11e8-8a27-93d07241aeb1.png)

**Comment by StillLearnin** [comment]
See #7 also. I started this new issue because I thought #7 might have been fixed with the previous pull requests or might be a different issue.

**Comment by tonerdo** [comment]
This doesn't look like much of a #7 issue. I'm thinking it might have something to do with all async methods. Although, one of Coverlet's users did mention that it works well with async tests. Is this project open source?

**Comment by StillLearnin** [comment]
Not open source but I trimmed the project down to about 1/10th its size and can still reproduce the issue. You can get the trimmed down version [here](https://github.com/StillLearnin/coverlet.troubleshooting)

**Comment by StillLearnin** [comment]
I think it may be an issue with timing or memory usage because if you comment out line 16 in [Main](https://github.com/StillLearnin/coverlet.troubleshooting/blob/master/coverlet.fails/Candle.DbContext/Extensions/SeedData/Main.cs) so as to not seed postal codes, coverlet seems to work.

The other option that fixes the issue is to trim down [PostalCodesUSA.csv](https://github.com/StillLearnin/coverlet.troubleshooting/blob/master/coverlet.fails/Candle.DbContext/Extensions/SeedData/PostalCodesUSA.csv) until the total number of lines doesn't exceed ~2000. It doesn't matter which lines you take out, just that the total number of lines is sufficiently small.

**Comment by tonerdo** [comment]
Thanks for providing the repro project. I'll clone it and check things out

**Comment by tonerdo** [comment]
@StillLearnin I figured out the problem. The `CoverageTracker` class writes to the hits file when the `ProcessExit` event is thrown, however, because there's so many hits to write it's unable to finish within the ~200ms window. There are a lot less hits when you comment out that line that's why it's able to finish successfully.

**Comment by tonerdo** [comment]
I'm gonna look for a more efficient way to write to the hits result file

**Comment by StillLearnin** [comment]
I'd be glad to take a look at this and open a pull request
