### ISSUE TITLE
Exclude argument doesn't seem to be working

### ISSUE THREAD

**Issue by vikasillumina** [tonerdo/coverlet#184]
Hi @tonerdo,

Please accept my sincere thanks for building and sharing coverlet tool to community. It helped a lot to get the code coverage for our .NET core application on linux/mac/windows.
It was very easy to set up and use.

I just ran into issue where I am trying to exclude few of the assemblies from coverage report but the exclude argument doesn't seem to honored.

Here is my command:
`dotnet test build.proj /p:CollectCoverage=true /p:CoverletOutput='./resultsZZ/' /p:CoverletOutputFormat=opencover --logger 'trx;LogFileName=ci_tests.trx' /p:Exclude="MyTest.FlowService.UnitTestHelpers*"`

I tried including wild cards like:

`dotnet test build.proj /p:CollectCoverage=true /p:CoverletOutput='./resultsAA/' /p:CoverletOutputFormat=opencover --logger 'trx;LogFileName=ci_tests.trx' /p:Exclude="MyTest.*.UnitTestHelpers*"`

`dotnet test build.proj /p:CollectCoverage=true /p:CoverletOutput='./resultsAA/' /p:CoverletOutputFormat=opencover --logger 'trx;LogFileName=ci_tests.trx' /p:Exclude="MyTest.*.*TestHelpers"`

Name of the assembly which I am trying to exclude is
`MyTest.FlowService.UnitTestHelpers.dll`

Please note build.proj is msbuild style file which gives me list of project files inside the solution folder and test command maps to VSTest target.

The coverage report output is generated as expected, just having difficulty in excluding the assembly that is not required.

I am using coverlet.msbuild 2.2.1. Not sure if there is something wrong in my syntax. Please can you suggest what I am missing?

**Comment by latop2604** [comment]
The filter format is like `[Assembly-Filter]Type-Filter`

So in your case it's more like `[MyTest.*.*TestHelpers]*`

And think you should escape `"`

**Comment by vikasillumina** [comment]
Thanks @latop2604 for the example, I tested it locally and it worked. 👍 
Sorry my bad I didn't follow the pattern as exactly its mentioned in the documentation.
Not an issue, user issue. 👍 
I will try more filters on my CI. I will close this issue.
