### ISSUE TITLE
Attempted to divide by zero

### ISSUE THREAD

**Issue by josephearl** [tonerdo/coverlet#19]
I get an error (warning?) printed when running coverlet - it looks like coverage results are still generated though:

```
/Users/user/.nuget/packages/coverlet.msbuild/1.0.1/build/netstandard2.0/coverlet.msbuild.targets(19,5): error : Attempted to divide by zero. [/Users/user/sln/tests/UnitTests/UnitTests.csproj]
```

**Comment by tonerdo** [comment]
This has been fixed and will be available via a new NuGet package next Monday. See here: https://github.com/tonerdo/coverlet/issues/6#issuecomment-376134752

**Comment by tonerdo** [comment]
Fix contained in new release: https://www.nuget.org/packages/coverlet.msbuild/1.0.2
