### ISSUE TITLE
Is there any way to execute coverlet using dotnet vstest

### ISSUE THREAD

**Issue by vikasillumina** [tonerdo/coverlet#190]
Hi @tonerdo,

I had success with using coverlet to get the coverage report for each of the test project using the dotnet test command as I described here:
https://github.com/tonerdo/coverlet/issues/184

However to save time on builds, I want to run the tests in parallel by testassemblies or xunit collection. Unfortunately dotnet test doesn't allow to run the tests in parallel however it seems we can do that with dotnet vstest command. But I need the test coverage too, so I was wondering if coverlet will work with dotnet vstest command.

Regards,
Vikas

**Comment by ppumkin** [comment]
I am working on this with my VS Extension to do that from within VS IDE 
(the feature should be available in v1.14)

https://marketplace.visualstudio.com/items?itemName=PiotrKula.prestocoverage

Otherwise you can do it using powershell scripts. run your tests then run coverlet?

**Comment by MarcoRossignoli** [comment]
> I want to run the tests in parallel by testassemblies or xunit collection.

I think that this doesn't work...coverlet instrumet dll injecting a static class with embedded tmp hits file(where we collect covered line/branch) if you run in "parallel" there is a chance that hit file will be accessed concurrently, this will lead to exception for concurrent access.
I think that we resolve this issue when we'll tackle https://github.com/tonerdo/coverlet/issues/357

As @ppumkin adviced you could create a script that launch different test process, but you need to be sure to run one test(one session, so one process) for every target output folder, to avoid overlapping in file access.

I'll close for now, feel free to reopen if we want go on with discussion.
