### ISSUE TITLE
Coverage is 0 when testing only const fields

### ISSUE THREAD

**Issue by LogikBlitz** [tonerdo/coverlet#193]
I have a project with only a lot of const strings.
We are testing that the const strings are of course correct so there are a lot of tests.
I am using Coverlet.MsBuild 2.3.0

So every line is essentially covered but coverlet reports zero all over.
I have created a small test solution in net standard/core2.1 using xunit2 that has that exact impact.
https://gitlab.com/LogikBlitz/coverletfieldtesting/

For this specific project i would expect a coverage at 100% since every line is covered.
I would also expect Branch to be 100% - since there is no branches in my code it is all covered - but i am not sure how Coverlet handles branching.
```
Test run for REDACTED/CoverletTest01/CoverletTesting_ConstFields.Test/bin/Debug/netcoreapp2.1/CoverletTesting_ConstFields.Test.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 6. Passed: 6. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.6792 Seconds

Calculating coverage result...
  Generating report 'REDACTED/CoverletTest01/CoverletTesting_ConstFields.Test/coverage.json'

+-----------------------------+--------+--------+--------+
| Module                      | Line   | Branch | Method |
+-----------------------------+--------+--------+--------+
| CoverletTesting_ConstFields | 0%     | 0%     | 0%     |
+-----------------------------+--------+--------+--------+
```

**Comment by LogikBlitz** [comment]
Update.
Added a single method and tested it fully.
Now coverage is 100%.
It seems like the const field testing is not evaluated by coverlet.
See commit:
https://gitlab.com/LogikBlitz/coverletfieldtesting/tree/feature/addMethodTesting

```
Test run for /REDACTED/CoverletTest01/CoverletTesting_ConstFields.Test/bin/Debug/netcoreapp2.1/CoverletTesting_ConstFields.Test.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 10. Passed: 10. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.0599 Seconds

Calculating coverage result...
  Generating report '/REDACTED/CoverletTest01/CoverletTesting_ConstFields.Test/coverage.json'

+-----------------------------+--------+--------+--------+
| Module                      | Line   | Branch | Method |
+-----------------------------+--------+--------+--------+
| CoverletTesting_ConstFields | 100%   | 100%   | 100%   |
+-----------------------------+--------+--------+--------+
```

**Comment by tonerdo** [comment]
@LogikBlitz glad to see you were able to get it working. Coverlet doesn't evaluate your tests, it's not even aware of them. It simply instruments your assembly under test and leaves it at that

**Comment by SteveGilham** [comment]
C# `const` values are in-lined into the consuming assembly at compile time; so in the original case, where only such values are being examined, there will be nothing executed in the assembly under test.

**Comment by MarcoRossignoli** [comment]
Close because solved.
