### ISSUE TITLE
Wrong source path in cobertura report with similar project name starts

### ISSUE THREAD

**Issue by zabomate** [tonerdo/coverlet#197]
Hi there,

I have 3 project in my solution:

- DAL
- DAL.MySql
- DAL.MsSql

When I generate a cobertura report I get a report with the following `sources` part.

```
<sources>
    <source>{Path to my solution}\DAL</source>
</sources>
```

I think this is a mistake since this is not a common parent folder for each 3 project. I think the following line of code is responsible for that because it is checking that every modules' path  starting with the same string even though in this case it is true it is not a common parent folder for the modules.

https://github.com/tonerdo/coverlet/blob/5217033c744f27f63db3fd1339ed3d8faa5fb34d/src/coverlet.core/Reporters/CoberturaReporter.cs#L149

**Comment by daveMueller** [comment]
@MarcoRossignoli is it ok when I analyze this and create a pr?

**Comment by MarcoRossignoli** [comment]
Yes Dave when you're working on it take a look if it's related to other Cobertura similar issues 
https://github.com/tonerdo/coverlet/issues/408
https://github.com/tonerdo/coverlet/issues/413

maybe we can fix those togheter, seem related to same report elements.

**Comment by daveMueller** [comment]
Ok this could take a while. I have to figure out what was the sourcelink related problem and why @tonerdo removed/emptied the ```<source>``` tag here (#260, #356) . Also I have to set up a jenkins build server to see what the problem is here (#408). Just for reference.

**Comment by MarcoRossignoli** [comment]
No worries Dave take your time and let us know...at the moment I don't have experience with Jenkins too.

**Comment by daveMueller** [comment]
This isn't a problem anymore because now with #614 the source only contains the root directories. Also before it wasn't a problem anymore because in #260 the source tag was emptied and absolute paths in the filename attribute were introduced.

**Comment by MarcoRossignoli** [comment]
thank's Dave for analysis
