### ISSUE TITLE
Code Coverage report not generated with command dotnet test /p:CollectCoverage=true /p:CoverletOutput='./results/'

### ISSUE THREAD

**Issue by kallam9** [tonerdo/coverlet#201]
Tried generating Code coverage report, But not able to generate the report 
After running the command line
dotnet test /p:CollectCoverage=true /p:CoverletOutput='./results.json'

Checking in the complete project
Please let me know if I am doing anything wrong.

**Comment by pape77** [comment]
Silly question but did you add your project's .csproj's path to that command line?  otherwise dotnet doesn't know what to test :P 

Also asuming you included the pkg in your test .csproj

**Comment by cternes** [comment]
Had the same issue and in my case the problem was that the package reference "coverlet.msbuild" was not properly added by Visual Studio to the *.csproj file. 

I was able to solve it by manually running "dotnet add package coverlet.msbuild" in the project folder and running "dotnet test" again after it.

**Comment by danielpalme** [comment]
I have a similar problem. `coverlet.msbuild` is added to project.

When I execute `dotnet test /p:CollectCoverage=true XUnitTestProject\XUnitTestProject.csproj` the test(s) are executed successfully but no coverage is available:

```
Calculating coverage result...
  Generating report 'coverage.json'

+--------+--------+--------+--------+
| Module | Line   | Branch | Method |
+--------+--------+--------+--------+

Total Line: 0%
Total Branch: 0%
Total Method: 0%
```

Here is a minimum sample project:
[XUnitTestProject.zip](https://github.com/tonerdo/coverlet/files/2486383/XUnitTestProject.zip)

**Comment by tonerdo** [comment]
@danielpalme your unit test project has no project/assembly dependencies so there's nothing for Coverlet to instrument

**Comment by danielpalme** [comment]
@tonerdo Thanks for the explanation. Wasn't aware of that.

**Comment by mmigala** [comment]
I didn't build the project before running dotnet test /p:CollectCoverage=true. After build everything started working.

**Comment by MarcoRossignoli** [comment]
@kallam9  any news?
Feel free to close please if solved.

**Comment by MarcoRossignoli** [comment]
Close for stale, feel free to re-open if needed.

**Comment by nZeus** [comment]
In our caseafter the upgrade of dontet core sdk to 3.1.301 it stopped working.

Upgrade of `coverlet.msbuild` from version `2.4.*` to `2.9.*` solved the issue

**Comment by chixuroblox** [comment]
> Had the same issue and in my case the problem was that the package reference "coverlet.msbuild" was not properly added by Visual Studio to the *.csproj file.
> 
> I was able to solve it by manually running "dotnet add package coverlet.msbuild" in the project folder and running "dotnet test" again after it.

You saved my life bro
