### ISSUE TITLE
coverlet.console isn't at 2.3.0 on nuget?

### ISSUE THREAD

**Issue by Nysosis** [tonerdo/coverlet#202]
Possibly a misunderstanding on my part on how you're versioning the two packages, but `coverlet.console` is only at 1.2.0, where as `coverlet.msbuild` is at 2.3.0.

**Comment by mihasic** [comment]
I think now it's even more fun:

| component | version |
| --- | --- |
| coverlet.msbuild | 2.5.1 |
| coverlet.console | 1.4.1 |
| GitHub Release | v4.1.1 |

@tonerdo , can you please align the versions?
It's a little bit difficult to match the package with the changeset.
I've heard of one tool to help with that: https://github.com/adamralph/minver

**Comment by tonerdo** [comment]
@Nysosis @mihasic `coverlet.console` had its first release several months after `coverlet.msbuild` so it couldn't miraculously start at v2.1.0. The Github releases are for the core library `coverlet.core` which both packages simply wrap. I know it might be confusing but be rest assured that the latest release of each contains the same functionality

**Comment by MarcoRossignoli** [comment]
I agree with @tonerdo and I'll add some though, it's also possible that the features(i.e. new switch) will be supported on different "drivers"(msbuild/console/collectors) in different version due to technical/dev time reasons. Core fix are aligned btw.

Close because answered.
