### ISSUE TITLE
cobertura output does not match expected in jenkins plugin for method signature

### ISSUE THREAD

**Issue by Nysosis** [tonerdo/coverlet#207]
Similar to #49, the current output from cobertura format does not quite match what the jenkins plugin expects (now I'm no Java/cobertura guy, so it's possible that you're emitting correctly and the plugin is wrong, but starting here as my point of investigation).

Currently my `.ctor` signature is coming out in the XML as something like: `(MyLib.CoreLib._Core.ICachingService,MyLib.CoreLib.TaskRunner.ITaskRunner)`

Which gives me a method name of:
`.ctor(char,char,int,char,short,char,int)`.

Which isn't right. However if the signature emitted was: `(TMyLib.CoreLib._Core.ICachingService;TMyLib.CoreLib.TaskRunner.ITaskRunner;)`

Then I'd get a more correct looking:
`.ctor(MyLib.CoreLib._Core.ICachingService,MyLib.CoreLib.TaskRunner.ITaskRunner)`

The method the plugin uses to parse the signature is [here](https://github.com/jenkinsci/cobertura-plugin/blob/4a62ab33c31276a7820ee65e78908cf6a112cccd/src/main/java/hudson/plugins/cobertura/CoberturaCoverageParser.java#L269), and it looks like depending on the Type of each parameter it's expecting a different prefix character to drive what the type is.

**Comment by MarcoRossignoli** [comment]
Close for stale, feel free to re-open if needed.
