### ISSUE TITLE
`coverlet.msbuild.targets(16,5)` Failed to resolve assembly

### ISSUE THREAD

**Issue by fcallejon** [tonerdo/coverlet#208]
Hi, 

Using version: `2.3.0`.

I'm running ` dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov .Project.csproj`.
And suddenly started getting: 
```
\.nuget\packages\coverlet.msbuild\2.3.0\build\netstandard2.0\coverlet.msbuild.targets(16,5): error : Failed to resove assembly: 'RestSharp, Version=106.3.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
```

And as result:
```
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 347. Passed: 347. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 9.4563 Seconds

Calculating coverage result...
  Generating report '.\Project\lcov.info'

+--------+--------+--------+--------+
| Module | Line   | Branch | Method |
+--------+--------+--------+--------+
```

Originally I was using 2.0.1 and started getting the same issue, but the output is:

```
+--------+--------+--------+--------+
| Module | Line   | Branch | Method |
+--------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Average | NaN%   | NaN%   | NaN%   |
+---------+--------+--------+--------+
```

**Comment by tonerdo** [comment]
Hi @fcallejon, this seems like an assembly resolve error on the part of coverlet. Try specifying `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in your csproj

**Comment by fcallejon** [comment]
Hi @tonerdo, that did the trick.

Any idea why it started failing?

**Comment by Cyberboss** [comment]
For me it was a really weird types within Microsoft.Logging.Abstractions that triggered it when I added LogLevel as a constant: https://github.com/tgstation/tgstation-server/commit/1a50a65a2678ad8ea0a2fc9aa2d3c00a6c3c4fe4

Fixed it by following the advice here: https://github.com/tonerdo/coverlet/issues/33#issuecomment-412489223

https://github.com/tgstation/tgstation-server/commit/ded9287f4e5a851719fbde992474204b522f8b59

**Comment by fcallejon** [comment]
Hi @Cyberboss, thanks for pointing that out.
I'm using the solution proposed by [ @tonerdo ](https://github.com/tonerdo/coverlet/issues/208#issuecomment-426985341) which does the same as `/p:CopyLocalLockFileAssemblies=true`.

I'm closing the issue now, but I'm still curious about what caused the issue in first place.
