### ISSUE TITLE
Question about reporting on json output

### ISSUE THREAD

**Issue by joeharrison714** [tonerdo/coverlet#216]
Hello,
Just trying to switch to coverlet fron dotcover so we can do our build fully in linux (We have a windows agent now just for code coverage). As part of the build script I am looping through each test project and outputting a coverlet json report to the artifacts folder. I then have a process that runs after the build that pulls the json files and deserializes them and I am attempting to calculate the percentage of code coverage for a certain module. However, because the module name appears in multiple files with no coverage the average is including a bunch of zeros and coming out very low. I also trued merging all the reports into 1 with the same result. So I had 2 questions:

1. Am I doing this right? I feel like I might be missing something.
2. I've had to copy a bunch of code from the coverlet source to be able to deserialize the report and calculate the percentage.  Should I need to do this?

**Comment by tonerdo** [comment]
@joeharrison714 there are two alternatives I see here:

1. grep the per module coverage summary that coverlet outputs to the terminal
2. Use a different output format like opencover that already contains per module summaries. You'll need to us an XML reader for this but it should be fairly straightforward

**Comment by vlef** [comment]
Maybe #203 is the fix the issue you are experiencing with merging?

**Comment by joeharrison714** [comment]
Yes I believe it was

**Comment by MarcoRossignoli** [comment]
Close because solved by merge with...new sample section if you're in throuble https://github.com/tonerdo/coverlet/blob/master/Documentation/Examples.md
