### ISSUE TITLE
Coverlet fails to resolve assembly when method signature uses default parameter

### ISSUE THREAD

**Issue by SamerAdra** [tonerdo/coverlet#217]
Coverlet MSBuild 2.3.0/2.3.1 fail on running with the following exception:

{userdir}\.nuget\packages\coverlet.msbuild\2.3.1\build\netstandard2.0\coverlet.msbuild.targets(7,5): error : Failed to resolve assembly: 'System.Data.SqlClient, Version=4.2.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I had no idea why until I rolled back my changes one by one and tracked it down to the following method signature that specifies a default value:
internal static SqlBulkCopy Build(string connectionString, SqlBulkCopyOptions options = SqlBulkCopyOptions.Default)

When I remove the default value from the signature then Coverlet works fine.

Doubt any of the following matters, but environment details:
.NET Core 2.0 on Windows 7.
SqlClient assembly is coming transitively by way of Microsoft.AspNetCore.All 2.0.8.

**Comment by tonerdo** [comment]
@SamerAdra that's definitely a weird problem. Try adding the following to your csproj:

```<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>```

**Comment by sfmskywalker** [comment]
I was running into the exact same problem. Adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to my project files resolved it.
