### ISSUE TITLE
Different behavior on OS X from Windows/Linux in ModuleTrackerTemplate.cs->UnloadModule()

### ISSUE THREAD

**Issue by Looking-at-the-ballpark** [tonerdo/coverlet#222]
After fighting the differences between OS X and Windows, I have found why the hits file is never generated on Windows. The AppDomain's DomainUnload event or the ProcesExit event are not triggered. 

By simply adding a division by zero inside this method, I can cause the Process instance created in line 51 of Program.cs (coverlet.console) to return ExitCode = 1 on OS X. But in Windows it returns ExitCode = 0. 

AppDomain's DomainUnload will not fire for the default domain. It may be that CLR on OS X does things differently. 

I do not think these event handlers (in ModuleTrackerTemplate ctor) are the shared. The docs state that these ca not be shared. 

Not sure how the tests were launched before the commit from 7 days ago in app->onExecute(..)

**Comment by Looking-at-the-ballpark** [comment]
I am using commit 34c4e505d31570ba523d6209514a62b7c9806ee8 (head on friday)

**Comment by Looking-at-the-ballpark** [comment]
Instrumenter -> ReplaceInstructionTarget(Instruction instruction, Instruction oldTarget, Instruction newTarget) -> In this method the old instruction target are never replaced. I can't hit the break points set in line 363 or 372 under Windows/Linux. In OS X works no problem. 

This means the instrumented code is never injected.

dotnet --version = 2.1.402 in Windows, 2.1.400 in Linux, 2.1.03 in OS X
Mono.Cecil = 0.10 across

The projects target .Net Core 2.0

It seems the problem lies in the dotnet version. But they do not seem to be that different. Same major revision

**Comment by Looking-at-the-ballpark** [comment]
By cleaning the temp folder of previous dlls I managed to get code instrumented. But I am back at the point 1: From OS X the writes to console from RecordHit(...)  succeed. From Windows it hoses the whole test run

**Comment by tonerdo** [comment]
@Looking-at-the-ballpark, what runtimes (and versions) are you running Coverlet on?

**Comment by Looking-at-the-ballpark** [comment]
@tonerdo:

Thanks a lot! This is what "dotnet --info" throws on OS X:

 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

This is the same on Windows 10:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by tonerdo** [comment]
This is definitely a weird one. Sounds like a bug in the copy of the CLR you have or something, all my tests have been successful. Can you try re-installing .NET Core on your machine? Also, try to test it on another OSX machine, possibly one in a CI server

**Comment by Looking-at-the-ballpark** [comment]
Yes, I will try reinstalling .Net Core on the Windows/Linux boxes. The OS X + CI server have to wait. I need to install gitlab in my laptop. I will post any new findings as soon as I get them

**Comment by MarcoRossignoli** [comment]
@Looking-at-the-ballpark any news?

**Comment by Looking-at-the-ballpark** [comment]
No. I got moved to another project. I will try again as soon I have the bandwidth and I will update the thread

**Comment by MarcoRossignoli** [comment]
After read your issue I think you should use new collectors to avoid issue with process exit and interaction with vstest plat.

**Comment by MarcoRossignoli** [comment]
Maybe you hit know issue https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#1-vstest-stops-process-execution-earlydotnet-test
I'll close for now...feel free to re-open the issue isn't solved.
