### ISSUE TITLE
Add support for TeamCity using service messages

### ISSUE THREAD

**Issue by obtuse-whoosh** [tonerdo/coverlet#226]
I've noticed that TeamCity does not support any of the output formats currently offered by this tool and the [ReportGenerator](https://github.com/danielpalme/ReportGenerator) tool. It would be a simple thing to add some support for writing TeamCity service messages out to the console, since we already print some statistics.

**Some Statistics that are easily supported:**

| TeamCity Statistic Key | Description                    |
| :---                    |    :----:                      |
| CodeCoverageL           | Line Coverage       |
| CodeCoverageC           | Class Coverage      |
| CodeCoverageM           | Method Coverage                 |
| CodeCoverageAbsLTotal   | The total number of lines      |
| CodeCoverageAbsLCovered | The number of covered lines    |
| CodeCoverageAbsCTotal   | The total number of classes    |
| CodeCoverageAbsCCovered | The number of covered classes  |
| CodeCoverageAbsMTotal   | The total number of methods |
| CodeCoverageAbsMCovered | The number of covered methods |

**Some statistics that would require extra work to support:**

| TeamCity Statistic Key   | Description                        |
| :---                    |    :----:                          |
| CodeCoverageS           | Statement Coverage                 |
| CodeCoverageB           | Block Coverage          |
| CodeCoverageR           | Branch Coverage         |
| CodeCoverageAbsSTotal   | The total number of statements     |
| CodeCoverageAbsSCovered | The number of covered statements   |
| CodeCoverageAbsBTotal   | The total number of blocks         |
| CodeCoverageAbsBCovered | The number of covered blocks       |
| CodeCoverageAbsRTotal   | The total number of branches |
| CodeCoverageAbsRCovered | The number of covered  branches     |

[See the documentation here for more info about TeamCity service messages](https://confluence.jetbrains.com/display/TCD18/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ServiceMessages)
[See the documentation here for more info about TeamCity statistics](https://confluence.jetbrains.com/display/TCD18/Custom+Chart#CustomChart-DefaultStatisticsValuesProvidedbyTeamCity)

**Comment by obtuse-whoosh** [comment]
BTW Reptarsrage is my other account, and the PR for this is #227

**Comment by obtuse-whoosh** [comment]
@tonerdo What's the eta for the next release?

**Comment by gilescope** [comment]
Good start. Would be great to get an in-depth view that was on parity with the other formats.
Seems TC has service message support for sucking in a file: 
##teamcity[importData type='dotNetCoverage' tool='<tool name>' path='<path to the results file>']
where tool name can be partcover, ncover or ncover3.

**Comment by Reptarsrage** [comment]
@gilescope You should open a new issue that can be tracked/prioritized by the code owners, if you haven't done that already.
