### ISSUE TITLE
coverlet fails when using Moq

### ISSUE THREAD

**Issue by tliebl** [tonerdo/coverlet#231]
I have a couple projects that use coverlet. The ones that do not use Moq work fine, but the one I have using Moq throws errors when running the code coverage. Is there a problem with coverlet and Moq?

Error Message:
 System.IO.FileLoadException : Could not load file or assembly 'Moq, Version=4.8.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by obtuse-whoosh** [comment]
I'm not seeing this issue. Are you using .Net Core? What version? If you could copy+paste the csproj file for the failing project that would be extremely helpful.

**Comment by fiuzaB** [comment]
I work with .NET Core 2.0 with Moq and it works fine. For some reason, you seem to suspect the cause is the combo coverlet + Moq. Did you try to remove Moq to check if this is true ?

**Comment by tliebl** [comment]
The XUnit project is .Net Framework 4.6.2 class library. I removed Moq from the XUnit project and coverlet ran perfect. I had to comment out all tests using Moq, but after I did it worked fine. So, my initial assumption is still valid. Something with .Net Framework 4.6.2 class library XUnit project and Moq is causing coverlet to error while running tests that use Moq.

**Comment by obtuse-whoosh** [comment]
It's for sure something on your end. I would look into re-installing the .Net framework SDK and see if that helps.

Here's my csproj for reference:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="2.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="Moq" Version="4.10.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

And the command I'm using to run tests:
`dotnet test .\XUnitTestProject1.csproj -c Release --logger:"console;verbosity=normal" /p:CollectCoverage=true`

Notice that I'm using .Net Framework 4.6.2, Moq 4.10.0 and coverlet 2.3.1.

**Comment by Roshek** [comment]
I think the problem is that Moq seems to not be compatible directly with net462, only through NET Standard 1.3.
I'm not an expert on this but adding this to the `<PropertyGroup>` element might solve your problem:
`<PackageTargetFallback>$(PackageTargetFallback);netstandard1.3</PackageTargetFallback>`

**Comment by MarcoRossignoli** [comment]
@tliebl can you try with last version?

**Comment by MarcoRossignoli** [comment]
I think it's solved now, we should skip Moq because we cannot instrument so the issue with tampering should gone.
Feel free to re-open if needed.
