### ISSUE TITLE
Add support for exclude by attribute

### ISSUE THREAD

**Issue by nordinrahman** [tonerdo/coverlet#232]
As of now, _coverlet_ could exclude any classes/methods/properties decorated with _ExcludeFromCodeCoverage_ attribute. However, it does not applicable for code annotated by other attributes like _GeneratedCodeAttribute_ nor _CompilerGeneratedAttribute_. In short, it does not allow user to exclude with arbitrary attribute. This is one of most common feature for other coverage tool (e.g. _dotcover_) that I usually use.

There are already demands to this feature, as listed below:

* #194 - CompilerGeneratedAttribute
* #125 - GeneratedCodeAttribute

The feature will have the following criteria:

1. Add additional argument parameter `--exclude-by-attribute` for _CLI_ tool
2. Add additional _MSBUILD_ property `ExcludeByAttribute`
3. Existing implementation to exclude code annotated by `ExcludeByCodeCoverage` remains as is
4. Exclusion list could be arbitrary specified in multiple, delimited by `,`, just like existing `Exclude` list.
5. Any code, i.e.: _classes_, _properties_, and _methods_ annotated with listed attributes, will be ignored from coverage.
6. The behavior of criteria 5 above, will be similar to how existing `ExcludeByCodeCoverage` works.

TQ.

**Comment by tonerdo** [comment]
Hi @nordinrahman, I'm inclined to agree with you on this. Will add it to my personal backlog but I'm open to PRs on this

**Comment by amweiss** [comment]
I can start taking a stab at this if no one else is since it also can cover my desire to see `ObsoleteAttribute` excluded.

**Comment by nordinrahman** [comment]
@amweiss , yes I reviewed the code, and it looks good to me.

Initially, I intend to add more unit test to cover the business logic introduced, but it's kinda of a challenge (eg changes on console app).

I'm yet to run the build against sample project, for manual testing - I will update here once I'm done.

Thanks, @amweiss . I wonder what @tonerdo 's opinion on this?

**Comment by amweiss** [comment]
@nordinrahman I agree, I did the minimum unit test to make sure the attribute excluded the code from coverage. I do have a few stylistic and coverage changes I'll send over on a subsequent PR if this one is getting merged.

**Comment by amweiss** [comment]
Perhaps apparent to other people, but not me, I think it's only going to work as part of a build the way I did it, not in the CLI afterward since it runs at the instrumenter level. So technically it won't meet the needs of this.

**Comment by amweiss** [comment]
I believe this is working as part of the build tasks now, @nordinrahman and @tonerdo is there anything left needed to merge #233 ?

**Comment by nordinrahman** [comment]
Thanks @amweiss , awesome. Looking forward for new release by @tonerdo

**Comment by tonerdo** [comment]
@nordinrahman @amweiss fix is available in latest NuGet releases

**Comment by sbansal-mdsol** [comment]
Can we exclude Startup.cs or Program.cs using ExcludeFromCodeCoverage attribute?

**Comment by MarcoRossignoli** [comment]
@sbansal-mdsol you could try with https://github.com/tonerdo/coverlet#source-files-1

**Comment by amweiss** [comment]
ExcludeFromCodeCoverage is also separate from this, that part worked fine already. This pull request allows for defining arbitrary attributes to ignore as well as ExcludeFromCodeCoverage.
