### ISSUE TITLE
Different results between local and Azure DevOps

### ISSUE THREAD

**Issue by lurumad** [tonerdo/coverlet#235]
Hi folks,

I run into something strange. When I run my tests in my local machine I received these results:

<img width="480" alt="local" src="https://user-images.githubusercontent.com/1729519/48092352-b6d99d80-e20c-11e8-8cbf-0ac6296407c3.png">

When I run in Azure DevOps I received these results:

<img width="505" alt="vsts" src="https://user-images.githubusercontent.com/1729519/48092372-c658e680-e20c-11e8-82af-ad40a3d5aee7.png">

Same number of tests (118) same code. Do you have any ideas?

Regards

**Comment by WiredUK** [comment]
How many test projects do you have? What commands do you run locally and on AD?

**Comment by MarcoRossignoli** [comment]
@lurumad any news?

**Comment by MarcoRossignoli** [comment]
Close for stale, feel free to re-open if needed.
