### ISSUE TITLE
Support any XML xUnit-compatible test reports

### ISSUE THREAD

**Issue by VladislavAntonyuk** [tonerdo/coverlet#240]
Bitbucket requires XML xUnit-compatible test reports.
https://confluence.atlassian.com/bitbucket/test-reporting-in-pipelines-939708543.html

**Comment by MarcoRossignoli** [comment]
I think you're talking about test report not coverage...seem that for coverage BitBucket supports  
`coverage.format - supported formats are JACOCO (xml), COBERTURA (xml) and LCOV. Default value is LCOV.`
Coverlet already supports lcov e cubertura.
https://bitbucket.org/atlassian/bitbucket-code-coverage/src/master/code-coverage-maven-plugin/

Feel free to reopen if I misunderstood.
