### ISSUE TITLE
teamcity service messages have values swapped

### ISSUE THREAD

**Issue by jzytnyk-korewireless** [tonerdo/coverlet#243]
Issue [226](https://github.com/tonerdo/coverlet/issues/226
) added teamcity reporting. (thank you!) 

From https://confluence.jetbrains.com/display/TCD18/Custom+Chart#CustomChart-listOfDefaultStatisticValues we can see that TeamCity is expecting a percentage for the "CodeCoverageX" keys, and a total line count for "CodeCoverageAbsXTotal" values.   These were swapped in the original implementation.

**Comment by jzytnyk-korewireless** [comment]
PR for this fix - https://github.com/tonerdo/coverlet/pull/244

**Comment by jzytnyk-korewireless** [comment]
@tonerdo What's the eta for the next release?

**Comment by tonerdo** [comment]
@jzytnyk-korewireless new releases have been published on NuGet
