### ISSUE TITLE
Coverlet test assembly path 

### ISSUE THREAD

**Issue by ViktorHofer** [tonerdo/coverlet#246]
Invoking the Coverlet as a global tool and supplying a test assembly seems to not work if the test assemblies is located in the cwd and there is not current directory mark supplied `.\`. In example:

```
coverlet "System.Text.RegularExpressions.Tests.dll" --target "dotnet.exe" --targetargs "xunit.console.dll System.Text.RegularExpressions.Tests.dll ..."

The path is empty.
Parameter name: path
```

Seems to be related to the command line parsing library `Microsoft.Extensions.CommandLineUtils`. Unsure if the cwd is not recognized correctly. I would expect the test assembly to be resolvable without the cwd mark.

**Comment by tonerdo** [comment]
Fixed in #253 and available in latest releases
