### ISSUE TITLE
Coverlet hangs when using System.Net.HttpStatusCode as a default parameter.

### ISSUE THREAD

**Issue by MaartenX** [tonerdo/coverlet#249]
When running ```dotnet test``` from the command line with a project that uses ```System.Net.HttpStatusCode``` as a default parameter, the test hangs using one full CPU core.

I've traced this issue to Mono.Cecil, and when I update to 0.10.1, the issue goes away.

I'll attach an example that shows the problem.

**Comment by MaartenX** [comment]
Project that uses NUnit with coverlet that contains the error:

[AssemblyToTest.zip](https://github.com/tonerdo/coverlet/files/2610463/AssemblyToTest.zip)

**Comment by tonerdo** [comment]
Latest release includes #252
