### ISSUE TITLE
Add option for minimum coverage / fail if under

### ISSUE THREAD

**Issue by spboyer** [tonerdo/coverlet#26]

**Comment by tonerdo** [comment]
Functionality added in https://github.com/tonerdo/coverlet/commit/4126086c9ac12a90c14f9d250baefb4811f74d84

**Comment by tonerdo** [comment]
See https://github.com/tonerdo/coverlet/tree/v1.1.0#threshold

**Comment by spboyer** [comment]
Should reopen, does not fail - https://github.com/spboyer/coverlet-test

have 83% coverage, run with 85 or 90 and still show as passed?

**Comment by spboyer** [comment]
I think that the expectation was to see **Threshold Failed** message or a **Test Run Fail**

```bash
Total tests: 5. Passed: 5. Failed: 0. Skipped: 0.
Test Run Successful.  Threshold FAILED
Test execution time: 1.2511 Seconds
```

OR

```bash
Total tests: 5. Passed: 5. Failed: 0. Skipped: 0.
Test Run Fail - Coverage of 85% not met.
Test execution time: 1.2511 Seconds
```

**Comment by tonerdo** [comment]
New NuGet bits: https://www.nuget.org/packages/coverlet.msbuild/1.1.1

**Comment by spboyer** [comment]
Perfect! 

```bash
error : Overall average coverage '83.3%' is lower than specified threshold '85%'
```
