### ISSUE TITLE
0% branch coverage when code has no branches

### ISSUE THREAD

**Issue by FreedCapybara** [tonerdo/coverlet#261]
Hi,

Small issue I noticed while playing around with Coverlet is that for code with no branches, 0% branch coverage is reported instead of 100%.

**ConsoleApp1.csproj**
*Program.cs*
```cs
using System;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

**ConsoleApp1.Tests.csproj**
*UnitTest1.cs*
```cs
using System;
using Xunit;

namespace ConsoleApp1.Tests
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            Program.Main(new string[] { });
        }
    }
}
```

**Output**
```
Test run for C:\src\ConsoleApp1\ConsoleApp1.Tests\bin\Debug\netcoreapp2.1\Consol
eApp1.Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.7762 Seconds

Calculating coverage result...
  Generating report 'C:\src\ConsoleApp1\ConsoleApp1.Tests\coverage.opencover.xml
'

+-------------+--------+--------+--------+
| Module      | Line   | Branch | Method |
+-------------+--------+--------+--------+
| ConsoleApp1 | 100%   | 0%     | 100%   |
+-------------+--------+--------+--------+

Total Line: 100%
Total Branch: 0%
Total Method: 100%
```

Thanks!

**Comment by pape77** [comment]
this one I already fixed locally, pretty easily @tonerdo 

On your ```CoverageDetails``` class:
just return 1 when ```Total``` is ```0```
```
 public double Percent
        {
            get => Math.Round(Total == 0 ? 1 : Covered / Total, 3);
        }
```

**Comment by FreedCapybara** [comment]
Thank you!

**Comment by samajs** [comment]
Hello Folks,

It seems this commit(https://github.com/tonerdo/coverlet/commit/85fa0f35ebb9f5f80e3f952ebed7cdfff82fe574) re-introduced the branch coverage issue.

Can we re-open this and fix it ?

Thanks

**Comment by p4p3** [comment]
@FreedCapybara

**Comment by MarcoRossignoli** [comment]
@samajs which version are you using?

**Comment by MarcoRossignoli** [comment]
This PR fix the issue https://github.com/tonerdo/coverlet/pull/267 and last days we simplify more with rounding https://github.com/tonerdo/coverlet/pull/397

**Comment by samajs** [comment]
@MarcoRossignoli my bad, just realised I am using `coverlet.msbuild 2.0.1` but latest is 2.6.1`, this one is fixed there. 
Thanks for pointing out :)
