### ISSUE TITLE
False negative with "/p:MergeWith" async/await branches

### ISSUE THREAD

**Issue by MarcoRossignoli** [tonerdo/coverlet#275]
I moved discussion from old PR to new issue.

---------------------
@pape77 issue https://github.com/tonerdo/coverlet/pull/158#issuecomment-448654060

I have a similar issue with this "ghost branches" which are never covered.
My code looks like this

    public class KeyProvider : IKeyProvider
    {
        private readonly IKeyRepository _repository;
        private readonly IMemoryCache _cache;

        public KeyProvider(IKeyRepository repository, IMemoryCache cache)
        {
            _repository = repository;
            _cache = cache;
        }

        public async Task<Key> GetByUuidAndTypeAsync(Guid uuid, KeyType type, CancellationToken cancellationToken)
        {
            return await _cache.GetOrCreateAsync($"uuid-{uuid.ToString()}-key-{type}",
                async entry => await _repository.FindOrCreateAsync(uuid, type, cancellationToken));
        }

   public class Key
    {
        public int Id { get; set; }

        public Guid Uuid { get; set; }

        [Required]
        public Guid Kid { get; set; }

        [Required]
        public KeyType KeyType { get; set; }
    }

 public enum KeyType
    {
        Cenc,
        Fairplay,
        Aes
    }
}
This code generates 4 branches, 2 of which I'm never able to cover

my tests:

  public class KeyProviderTests
    {
        private readonly Mock<IKeyRepository> _keyRepositoryMock;
        private readonly MemoryCache _memoryCache;
        private readonly Guid _testGuid = Guid.NewGuid();
        private readonly KeyProvider _keyProvider;

        public KeyProviderTests()
        {
            _memoryCache = new MemoryCache(new MemoryCacheOptions());

            _keyRepositoryMock = new Mock<IKeyRepository>();

            _keyProvider = new KeyProvider(_keyRepositoryMock.Object, _memoryCache);
        }

        [Theory(DisplayName = "Should call repository method with correct values")]
        [InlineData(KeyType.Cenc)]
        [InlineData(KeyType.Aes)]
        [InlineData(KeyType.Fairplay)]
        public async Task GetByUuidAndTypeAsync01(KeyType keyType)
        {
            _keyRepositoryMock.Setup(kr =>
                    kr.FindOrCreateAsync(_testGuid, keyType, It.IsAny<CancellationToken>()))
                .ReturnsAsync(new Key());

            await _keyProvider.GetByUuidAndTypeAsync(_testGuid, keyType, new CancellationToken());

            _keyRepositoryMock.Verify(
                kr => kr.FindOrCreateAsync(_testGuid, keyType, It.IsAny<CancellationToken>()), Times.Once);
        }

        [Theory(DisplayName = "Should get key from cache")]
        [InlineData(KeyType.Cenc)]
        [InlineData(KeyType.Aes)]
        [InlineData(KeyType.Fairplay)]
        public async Task GetByUuidAndTypeAsync02(KeyType keyType)
        {
            var cacheKey = $"uuid-{_testGuid.ToString()}-key-{keyType}";
            _memoryCache.Set(cacheKey, new Key());
           
            await _keyProvider.GetByUuidAndTypeAsync(_testGuid, keyType, new CancellationToken());

            _keyRepositoryMock.Verify(
                kr => kr.FindOrCreateAsync(_testGuid, keyType, It.IsAny<CancellationToken>()), Times.Never);
        }
}
The generated branches in my coverage.json are (notice the MoveNext() thing):

     "Keys.Application.Services.KeyProvider/<>c__DisplayClass3_0/<<GetByUuidAndTypeAsync>b__0>d": {
        "System.Void Keys.Application.Services.KeyProvider/<>c__DisplayClass3_0/<<GetByUuidAndTypeAsync>b__0>d::MoveNext()": {
          "Lines": {
            "27": 9
          },
          "Branches": [
            {
              "Line": 27,
              "Offset": 8,
              "EndOffset": 14,
              "Path": 0,
              "Ordinal": 0,
              "Hits": 3
            },
            {
              "Line": 27,
              "Offset": 81,
              "EndOffset": 83,
              "Path": 0,
              "Ordinal": 2,
              "Hits": 0
            },
            {
              "Line": 27,
              "Offset": 8,
              "EndOffset": 119,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 0
            },
            {
              "Line": 27,
              "Offset": 81,
              "EndOffset": 147,
              "Path": 1,
              "Ordinal": 3,
              "Hits": 3
            }
          ]
        }
      },
Line 27 in my code is precisely the async await one:
async entry => await _repository.FindOrCreateAsync(uuid, type, cancellationToken));

hope it's useful

------------------
Repro [keys.zip](https://github.com/tonerdo/coverlet/files/2703474/keys.zip)

/cc @kevindqc /@tonerdo

**Comment by MarcoRossignoli** [comment]
I was able to repro the issue with @pape77 code, I'll come back ASAP.

**Comment by MarcoRossignoli** [comment]
> I was able to repro the issue with @pape77 code, I'll come back ASAP.

False positive for now...it was an issue with report generator.

@pape77 I need more info...can you provide "command line" to generate your coverage.json sample(with 4 branch) i.e. from root (Keys.sln place).
I cannot generate 4 branch for that call but only 2.

**Comment by pape77** [comment]
I removed the cache part to make it more explicit. That was adding two more branches because there was another await being used. There should be 2 branches now. One of which is never covered

**Comment by MarcoRossignoli** [comment]
My current test:
```
dotnet test "test\Keys.Application.Tests\Keys.Application.Tests.csproj" /p:CollectCoverage=true   /p:CoverletOutput=..\..\test-results\coverage\Keys.Application.Tests.json /p:Include="[Keys.Application]*"
```
result
```
{
  "Keys.Application.dll": {
    "...\\src\\coverlet\\Issue1\\src\\Keys.Application\\Services\\KeyProvider.cs": {
      "Keys.Application.Services.KeyProvider": {
        "System.Void Keys.Application.Services.KeyProvider::.ctor(Keys.Data.Repositories.Contracts.IKeyRepository)": {
          "Lines": {
            "16": 3,
            "17": 3,
            "18": 3,
            "19": 3
          },
          "Branches": []
        }
      },
      "Keys.Application.Services.KeyProvider/<GetByUuidAndTypeAsync>d__2": {
        "System.Void Keys.Application.Services.KeyProvider/<GetByUuidAndTypeAsync>d__2::MoveNext()": {
          "Lines": {
            "22": 3,
            "23": 3,
            "24": 3
          },
          "Branches": [
            {
              "Line": 23,
              "Offset": 62,
              "EndOffset": 128,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 3
            }
          ]
        }
      }
    }
  }
}
```

**Comment by pape77** [comment]
I use the console version of coverlet. Will provide the script in a sec

**Comment by MarcoRossignoli** [comment]
> I use the console version of coverlet. Will provide the script in a sec

Thank's here my playground if you find something strange https://github.com/MarcoRossignoli/marcorossignoli.github.io/tree/coverletbug/src/coverlet/Issue1

**Comment by MarcoRossignoli** [comment]
> If I run your command I get the same as you. Correct branch. While while running with the merge with over all I get this incorrect branch thing

Maybe merge issue...I go on...

**Comment by MarcoRossignoli** [comment]
@pape77 I found the issue...merge is the culprit, the issue is in this line https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/CoverageResult.cs#L94
To merge it uses all field, but different test has got different instrumentation values
```
"Branches": [
            {
              "Line": 23,
              "Offset": 62,
              "EndOffset": 128,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 3
            },
            {
              "Line": 23,
              "Offset": 62,
              "EndOffset": 64,
              "Path": 0,
              "Ordinal": 0,
              "Hits": 0
            }
          ]
```
For instance if we compare only "Line" it works...but I think that it's could lead to ambiguity, I'll try to understand if it's safe.

/cc @tonerdo

**Comment by pape77** [comment]
Nice! Hope it's fixed soon :)

**Comment by pape77** [comment]
I don't think only line is enough. I have things like this in my well generated coverage files:

```
"Branches": [
            {
              "Line": 44,
              "Offset": 18,
              "EndOffset": 20,
              "Path": 0,
              "Ordinal": 0,
              "Hits": 1
            },
            {
              "Line": 44,
              "Offset": 18,
              "EndOffset": 49,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 1
            }
          ]
```

So it seems to me that the ```EndOffset``` is the problem here. At first sight at least.

Maybe @tonerdo knows a bit more about this

**Comment by MarcoRossignoli** [comment]
@kevindqc are you using merge?

**Comment by MarcoRossignoli** [comment]
However if we decide that is correct we can apply same trick(remove uncovered branch for MoveNext() async state machine if one of two branch has been covered) on "merge".
@tonerdo what do you think?

**Comment by pape77** [comment]
Well, i think it should be done right? To apply the same accordingly also when merging. Otherwise we always will have this non covered branches when merging now. I wonder how would you do it though

I never completely understood this line 

```
 if (moveNextBranch.Value.Method == branch.Value.Method && moveNextBranch.Value != branch.Value && moveNextBranch.Value.Hits == 0)
```
because it's comparing the full branch object, still the method could have some other branch with hits 0 which you will be removing . How do you know that's exactly this "ghost branch" one?

**Comment by MarcoRossignoli** [comment]
> because it's comparing the full branch object, still the method could have some other branch with hits 0 which you will be removing . How do you know that's exactly this "ghost branch" one?

Because "today" async state machine has got only 2 path...sync and async so for now we have only 2 branch.

**Comment by pape77** [comment]
I think I just answered my own question. With the MoveNext you make sure it's the async line you are checking and not other part of the Method itself (because the method name includes this MoveNext stuff)
Sorry :P

**Comment by MarcoRossignoli** [comment]
FYI I stole idea from well know and supported coverage engine https://github.com/OpenCover/opencover/blob/19ebe9c19ba0f8205f28b6923f7c7d5e2730004a/main/OpenCover.Framework/Persistance/BasePersistance.cs#L893

**Comment by pape77** [comment]
@MarcoRossignoli is it too much to ask if you create a PR (just whenever you have the time)? If this is not merged here, I will use it for sure in a fork. But hopefully it will be taken into coverlet :) 
How would you achieve this? Extracting this part into a method and running it after the Merge run now? Or what was your plan?

**Comment by pape77** [comment]
@MarcoRossignoli No rush! I won't jump into this before new year. I wanted to see the pr/ changes so I change my own fork which is already a bit different than actual.

If the pr is not there by then I'll dig into yoir repo for figuring out the changes. But i think you will have it in a pr by then ;)

Thanks again for taking the time for this

**Comment by MarcoRossignoli** [comment]
@pape77 thank's for support!

**Comment by kevindqc** [comment]
@MarcoRossignoli I don't use `/p:MergeWith`, but I call reportgenerator with `**/coverage.cobertura.xml`

**Comment by MarcoRossignoli** [comment]
@kevindqc today here we found possible issue on reports merge. If this isn't your issue can you try to isolate a repro?

**Comment by pape77** [comment]
I slightly changed the  code in keyProvider , and it's tests, and the same seems to happen, regardless of using code from pr #277   

Here the new proj I'm using to generate this branches again:

[keys.zip](https://github.com/tonerdo/coverlet/files/2706138/keys.zip)

Then I end up with:

```
"Keys.Application.Services.KeyProvider/<>c__DisplayClass3_0/<<GetByUuidAndTypeAsync>b__0>d": {
        "System.Void Keys.Application.Services.KeyProvider/<>c__DisplayClass3_0/<<GetByUuidAndTypeAsync>b__0>d::MoveNext()": {
          "Lines": {
            "26": 9
          },
          "Branches": [
            {
              "Line": 26,
              "Offset": 8,
              "EndOffset": 14,
              "Path": 0,
              "Ordinal": 0,
              "Hits": 3
            },
            {
              "Line": 26,
              "Offset": 81,
              "EndOffset": 83,
              "Path": 0,
              "Ordinal": 2,
              "Hits": 0
            },
            {
              "Line": 26,
              "Offset": 8,
              "EndOffset": 119,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 0
            },
            {
              "Line": 26,
              "Offset": 81,
              "EndOffset": 147,
              "Path": 1,
              "Ordinal": 3,
              "Hits": 3
            }
          ]
        }
   }
```

**Comment by MarcoRossignoli** [comment]
@pape77 found the issue...nested async state machine,I'm working on a solution.

**Comment by MarcoRossignoli** [comment]
@pape77 I'm trying something more "secure", check if class that contains MoveNext() implements IAsyncStateMachine https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.iasyncstatemachine?view=netframework-4.7.2

**Comment by pape77** [comment]
@MarcoRossignoli ah that's even nicer 👍
