### ISSUE TITLE
ExcludeFromCodeCoverageAttribute ignored on some types in nested class

### ISSUE THREAD

**Issue by hughbe** [tonerdo/coverlet#279]
Steps:
```
dotnet tool install --global dotnet-reportgenerator-globaltool
git clone https://github.com/hughbe/wpf
cd wpf
git checkout coverlet
dotnet test ./src/Microsoft.DotNet.Wpf/test/System.Xaml /P:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage.xml /P:ExcludeByAttribute=ExcludeFromCodeCoverageAttribute
reportgenerator -reports:./coverage.xml -targetdir:./coverage
```

## Expected

- Method is excluded

## Actual

- Method is not excluded 

See for example 1495 of the coverage for XamlSchemaContext.cs
![image](https://user-images.githubusercontent.com/1275900/50386684-ca20c980-06e3-11e9-8b16-cfd9574df908.png)

**Comment by hughbe** [comment]
I mean the first issue with `IsReadOnly` is probably the same as #269 but not sure about the enumerator?

**Comment by SteveGilham** [comment]
See also issue #129

**Comment by MarcoRossignoli** [comment]
close for dup, we track issue there https://github.com/tonerdo/coverlet/issues/279#issuecomment-449708572
