### ISSUE TITLE
Providing standard input to a runner

### ISSUE THREAD

**Issue by turbo** [tonerdo/coverlet#280]
I need to collect coverage for a `dotnet run` execution (not `dotnet test`). Right now, the program is called like this:

```bash
# Run backup tests
echo "backup" | dotnet run -c Release -p TCLS ALL

# Run all tests (newline)
echo "" | dotnet run -c Release -p TCLS ALL
```
Is there a way to pass standard input to a `--target`?

**Comment by turbo** [comment]
Alright, seems that if I put the above in a script file and use that as a target, it kinda works. Would be nice to have a proper option though.

**Comment by tonerdo** [comment]
Thanks for the suggestion but I don't think your scenario is something we plan to support in Coverlet. Your workaround should be sufficient
