### ISSUE TITLE
Unable to filter report against certain assemblies

### ISSUE THREAD

**Issue by HardySoftware** [tonerdo/coverlet#283]
I have a .net core solution with several projects in it. Here is the steps what I did

- `dotnet add package coverlet.msbuild` to add the reference to my Xunit test project.
- `dotnet test /p:CollectCoverage=true` to execute tests and produce reports

The reports look like

| Module | Line | Branch | Method |
|--------------------------------------------------|-------|--------|--------|
| My.Project1 | 0% | 0% | 0% |
| My.Project2 | 1% | 1% | 1% |
| xunit.runner.reporters.netcoreapp10 | 1.1% | 0.5% | 5.1% |
| xunit.runner.utility.netcoreapp10 | 15.7% | 9.1% | 21% |
| xunit.runner.visualstudio.dotnetcore.testadapter | 45.6% | 35.6% | 47.8% |

I want to filter out xunit assemblies from my report, I tried following commands
- `dotnet test /p:CollectCoverage=true /p:Exclude="[xunit*]"`
- `dotnet test /p:CollectCoverage=true /p:Include="[My*]"`

But the result is still the same. Please help, how shall I exclude xunit assemblies from my report?

**Comment by tonerdo** [comment]
Hi @HardySoftware, you want to do `dotnet test /p:CollectCoverage=true /p:Exclude="[xunit.*]*"`

**Comment by HardySoftware** [comment]
Unfortunately, the result is the same, xunit is still included.

**Comment by Roshek** [comment]
Had the same problem, exclude didn't work, then realized I was missing the second * in the Exclude parameter (/p:Exclude="[xunit.*]\*<-this guy right here"). In your original description you are missing it too.

**Comment by HardySoftware** [comment]
Thanks guys for pointing out that I missed the last *. It all works now.
