### ISSUE TITLE
Coverlet 2.5.0 throws Exception 

### ISSUE THREAD

**Issue by akshaybheda** [tonerdo/coverlet#285]
I have updated my Coverlet.msbuild Version to 2.5.0. I am getting

> An exception occurred while invoking executor 'executor://xunit/VsTestRunner2/desktop_and_uap': The type initializer for 'Coverlet.Core.Instrumentation.Tracker.xunit.runner.visualstudio.testadapter_c
> -4aa5-a24d-de2d8256b22e' threw an exception.
> Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Exception. 

Project Information:
.net framework 4.6.1.

Also, in Version 2.3.0, It was failing my some tests due to rebuilding the project when enabled code coverage.

**Comment by SlowLogicBoy** [comment]
I'm having the same problem after upgrading to `2.5.0`
If I run on netcoreapp2.2 it works fine, however if I run on net462 it fails:
```
System.TypeInitializationException : The type initializer for 'Coverlet.Core.Instrumentation.Tracker.Path.To.My.Tests' threw an exception.
---- System.TypeLoadException : Could not load type 'System.AppDomain' from assembly 'System.Runtime.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Stack Trace:
   at Coverlet.Core.Instrumentation.Tracker.Path.To.My.Tests.RecordHit(Int32 )
   at System.Collections.Generic.ICollectionExtensions.AddRangeIfNotContains(ICollection`1 collection, StringComparison comparisonType, String[] values)
   at Path.To.My.Tests in Path/To/MyTestFile.cs
```
