### ISSUE TITLE
No Coverage Results When Single Test Fails

### ISSUE THREAD

**Issue by abbotware** [tonerdo/coverlet#287]
Not sure if this is expected behavior, but I have a lot of unit tests, if a single one of them fails, no coverage results are generated.    I think it would be desirable to still get coverage if a single test fails so I dont know if this is a bug or by design.

I am using .Net Core 2.2 + Nunit 3.11 / Nunit3TestAdapter 3.12 and coverlet version 2.5.0

**Comment by abbotware** [comment]
If this is a bug, it is trivially reproducible - see attached
[NUnitTestProject1.zip](https://github.com/tonerdo/coverlet/files/2734383/NUnitTestProject1.zip)

**Comment by tonerdo** [comment]
This only happens when using `coverlet.msbuild` package. This is expected behaviour as MSBuild will not move on to the next target if the previous one fails. You can use the `coverlet.console` global tool if you don't want this behaviour
