### ISSUE TITLE
coverlet.msbuild 2.3.0 rebuilds the project with not enough information

### ISSUE THREAD

**Issue by akshaybheda** [tonerdo/coverlet#288]
Hi, 

I am using coverlet.msbuild 2.3.0 with Shouldly package. It looks like whenever i try to enable codecoverage, some of my test fails as the coverlet rebuilds the project which are referenced from my test project with less than Debug level information. I can see the difference in the sizes of dll.

When i build the project with dotnet build, it builds the project with Debug level information set to Full. and when i add coverlet.msbuild to my test project and enable the code coverage and run the test with dotnet test --no-build. It still rebuilds the testee projects. and due to that some of my tests fail as the Shoudly requires full debug information to generate exception messages.

**Comment by tonerdo** [comment]
Hi @akshaybheda, is you debug information embedded or in a separate PDB file?

**Comment by akshaybheda** [comment]
Its in separate PDB file. the pdb size remains the same but the dll changes. dll of the projects referenced by my test

**Comment by akshaybheda** [comment]
@tonerdo I also tried to change my application to .netcore2.2 with all updated packages, i face the same issue that the coverlet modifies the source dll which doesnt match with pdb's

**Comment by tonerdo** [comment]
#318 updates the Instrumenter to write new symbol information after instrumentation. New NuGet bits with this change will drop in 24 hours
