### ISSUE TITLE
Improvement. Add to average return of code coverage of all lines

### ISSUE THREAD

**Issue by felipenicolini** [tonerdo/coverlet#29]
Improvement. Add to average return of code coverage of all lines.
example:

project 1 | 100%
project 2 | 50%

Total coverage: 75%

**Comment by tonerdo** [comment]
Why average and not total?

**Comment by paulers** [comment]
Having totals for each project, class and/or method would be handy. On method level specifically something like ``{ total: 10, covered: 5 }`` and we can do the math ourselves. I'm currently loading the json file, going through each line result, keeping count of zeroes and non-zeroes then calculating the %.

**Comment by tonerdo** [comment]
The other output formats like `opencover` already have this information

**Comment by paulers** [comment]
I just used this here: https://github.com/tonerdo/coverlet/blob/6985035c1fca4b749450325e205b76acec67b6d0/src/coverlet.core/CoverageSummary.cs#L16 as a template for how many loops I needed to spin up to get to the meat of the report. Would love to get this inside the Json file, cause parsing opencover xml is... *shudder*.

**Comment by trickvi** [comment]
I just added this to a CI/CD process in Gitlab (so Gitlab can grab the total coverage on a pull request (called merge requests in Gitlab-land) and let reviewers know what it is (see top-right corner):
![Merge request cover](https://gitlab.com/help/user/project/pipelines/img/pipelines_test_coverage_mr_widget.png)

I ended up writing this lovely piece of incomprehensible beauty:

    dotnet test /p:CollectCoverage=true {} \; | grep '%' | awk '{ print $0 }{ sum += substr($4, 1, length($4)-1) } END { if (NR > 0) print "Total coverage: " sum / NR "%" }'

**Comment by cRUSHER-HLG** [comment]
> I just added this to a CI/CD process in Gitlab (so Gitlab can grab the total coverage on a pull request (called merge requests in Gitlab-land) and let reviewers know what it is (see top-right corner):
> ![Merge request cover](https://camo.githubusercontent.com/557b734e7fd7261374c91574348dcda4067b45ef/68747470733a2f2f6769746c61622e636f6d2f68656c702f757365722f70726f6a6563742f706970656c696e65732f696d672f706970656c696e65735f746573745f636f7665726167655f6d725f7769646765742e706e67)
> 
> I ended up writing this lovely piece of incomprehensible beauty:
> 
> ```
> dotnet test /p:CollectCoverage=true | grep '%' | awk '{ print $0 }{ sum += substr($4, 1, length($4)-1) } END { if (NR > 0) print "Total coverage: " sum / NR "%" }'
> ```

Is this still working for you?
