### ISSUE TITLE
System modules in coverage report

### ISSUE THREAD

**Issue by rwasala** [tonerdo/coverlet#293]
### Issue description
After upgrading coverlet.msbuild package from 2.3.2 to **2.5.0** I have noticed that in coverage report System modules are present e.g.
```
+--------------------------+--------+--------+--------+
| Module                   | Line   | Branch | Method |
+--------------------------+--------+--------+--------+
| SomeModule...            | 90.4%  | 66.1%  | 97.8%  |
+--------------------------+--------+--------+--------+
| System.Reactive          | 0%     | 0%     | 0%     |
+--------------------------+--------+--------+--------+
| System.Interactive.Async | 1.6%   | 1.3%   | 1.8%   |
+--------------------------+--------+--------+--------+
```

It only happens when dotnet test is executed with `/p:CopyLocalLockFileAssemblies=true` option e.g.:
```
dotnet test /p:CopyLocalLockFileAssemblies=true /p:CollectCoverage=true
```
It work as expected when option `/p:CopyLocalLockFileAssemblies=true` is not present

For easy issue reproduction I created repository https://github.com/rwasala/CodeCoverage. After cloning it just run in repo root folder:
```
dotnet test /p:CopyLocalLockFileAssemblies=true /p:CollectCoverage=true
```
and you will get such output
```
+--------------------------+--------+--------+--------+
| Module                   | Line   | Branch | Method |
+--------------------------+--------+--------+--------+
| SampleLib                | 100%   | 100%   | 100%   |
+--------------------------+--------+--------+--------+
| System.Interactive.Async | 0%     | 0%     | 0%     |
+--------------------------+--------+--------+--------+
```
If you run:
```
dotnet test /p:CollectCoverage=true
```
then the output will be:
```
+-----------+--------+--------+--------+
| Module    | Line   | Branch | Method |
+-----------+--------+--------+--------+
| SampleLib | 100%   | 100%   | 100%   |
+-----------+--------+--------+--------+
```
If you downgrade coverlet.msbuild package to **2.4.0** you will get the same output regardless of using `/p:CopyLocalLockFileAssemblies=true` parameter

**Comment by tonerdo** [comment]
@rwasala this is as a result of adding support for assemblies with embedded PDBs. You can workaround this by excluding the `System.*` assemblies

**Comment by rwasala** [comment]
> 
> 
> @rwasala this is as a result of adding support for assemblies with embedded PDBs. You can workaround this by excluding the `System.*` assemblies

This is not a solution as those Modules will still be present in report with 100% coverage. This causes that code coverage report uploaded using cobertura plugin on Jenkins does not work correctly as I guess it tries to copy sources to proper directory to be able to present to user what is covered and what is not.

**Comment by tonerdo** [comment]
If you exclude the modules they will not be included in the coverage result

**Comment by rwasala** [comment]
> 
> 
> If you exclude the modules they will not be included in the coverage result

If I run
```
dotnet test /p:CopyLocalLockFileAssemblies=true /p:Exclude=\"[*]System.*\" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
```
the output is
```
Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2,3186 Seconds

Calculating coverage result...
  Generating report 'D:\Repos\CodeCoverage\CodeCoverage\coverage.cobertura.xml'

+--------------------------+--------+--------+--------+
| Module                   | Line   | Branch | Method |
+--------------------------+--------+--------+--------+
| SampleLib                | 100%   | 100%   | 100%   |
+--------------------------+--------+--------+--------+
| System.Interactive.Async | 100%   | 100%   | 100%   |
+--------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 100%   | 100%   | 100%   |
+---------+--------+--------+--------+
| Average | 50%    | 50%    | 50%    |
+---------+--------+--------+--------+
```
In xml file I can see
```
    <package name="System.Interactive.Async" line-rate="1" branch-rate="1" complexity="0">
      <classes />
    </package>
```
And I guess this is a reason why cobertura Jenkins plugin is not working as expected. Is there any possibility of disabling this support for embedded PDBs using some parameter? Or maybe your suggestion would be to contact cobertura Jenkins plugin team?

**Comment by SlowLogicBoy** [comment]
Should be: `[System*]*`

**Comment by rwasala** [comment]
@SlowLogicBoy Thanks for your help. We can close that
