### ISSUE TITLE
Viewing instrumented assemblies

### ISSUE THREAD

**Issue by sharwell** [tonerdo/coverlet#296]
I would like to inspect the instrumented assembly for a project, e.g. with ILSpy. Is there an easy way to create the instrumented assembly for this purpose?

**Comment by ViktorHofer** [comment]
If you add a reference to coverlet.msbuild you can just the required properties to invoke this target: https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild/coverlet.msbuild.targets#L20

**Comment by MarcoRossignoli** [comment]
@sharwell can we close this?Does @ViktorHofer's idea works?
Usually similar to @ViktorHofer's idea I copy targets on "tests" and point `<UsingTask>` to debug build path, after with Debug.Launch() I attach to VS inside coverlet(and rebuild), in this way I stop code before "restore" dll and I can analyze instrumented dll.

**Comment by sharwell** [comment]
@MarcoRossignoli There isn't a good approach today but I'm hoping we can implement it after the project PRs are merged.

**Comment by MarcoRossignoli** [comment]
@sharwell I found a way:
```
dotnet msbuild /t:Restore,Build,InstrumentModulesAfterBuild /p:CollectCoverage=true "C:\git\coverlet-issue-343\DemoLibraryTests\DemoLibraryTests.csproj" /v:m
```

**Comment by MarcoRossignoli** [comment]
Feel free to re-open if needed
