### ISSUE TITLE
Support command line options in lieu of property notation

### ISSUE THREAD

**Issue by spboyer** [tonerdo/coverlet#3]
Use `--option` in addition to or instead of property notation `/p:`

`/p:CollectCoverage=true` -> `--collect|-c (true|false)` 
`/p:CoverletOutputFormat=opencover` -> `--output|-o (json (default), lcov and opencover)`
`/p: CoverletOutputDirectory ` --> `--directory|-d`

**Comment by tonerdo** [comment]
This is unfortunately a limitation with MSBuild. The standard command line option format will be supported by the coverlet cli once it's release (should coincide with the general availability of [.NET Core global tools](https://surfingthecode.com/fun-with-global-tools-in-.net-core-2.1-preview/))
