### ISSUE TITLE
Unable to run in bash shell

### ISSUE THREAD

**Issue by paulers** [tonerdo/coverlet#30]
https://github.com/tonerdo/coverlet/blob/75a43d2a39a8733289875c3b00ebdbb64adc4385/src/coverlet.msbuild/coverlet.msbuild.props#L11

Output gets formatted with \ resulting in trying to write to a directory not supported by non-CMD terminals. Additionally, running without ``/p:CoverletOutputDirecotory`` results in `Project file does not exist` error.

Not sure how to work around this, or if it's possible given that this value is hardcoded.

**Comment by tonerdo** [comment]
Can you pls give me the details of the OS? Coverlet was developed predominantly in bash on a Mac and tested in both Powershell and Ubuntu

**Comment by paulers** [comment]
Sure. I tried it both inside a Jenkins installation on a Windows Server 2014 machine using git bash (managed shell script), and on Windows 10 using git bash running a script manually. Haven't tried it on an actual linux machine as I do not have access to one. I worked around it for now generating the coverage in a CMD window, then running the script inside bash shell after.

**Comment by voronoipotato** [comment]
Git bash replaces forward with backward slashes a bit indiscriminately. See https://github.com/yarnpkg/yarn/issues/2785 . I have like a hundred dollar bounty on this issue if anyone's bored.

**Comment by xtiancapil** [comment]
@paulers I was running into a similar issue going from git bash shell to my jenkins running linux and dotnet core. I ended up creating a MSBuild Response file (msbuild.rsp) and referencing that in the command line. It's a new line separated file where you can define arguments you want msbuild to use. This is what I have in mine (named coverage.rsp)
````
/p:DebugType=full
/p:CollectCoverage=true
/p:CoverletOutputFormat=opencover
````
Then the command-line or your bash script would will now look like this:
````
dotnet test TestProject/TestProject.csproj -c Release --no-build @coverage.rsp
````

**Comment by tonerdo** [comment]
Thanks @xtiancapil. @paulers I'll close this out now, feel free to reopen

**Comment by NeedHack** [comment]
You can double up the slashes to escape them

```
//p:CoverletOutputDirecotory=true
```
