### ISSUE TITLE
OpenCover report contains ignored files

### ISSUE THREAD

**Issue by SlowLogicBoy** [tonerdo/coverlet#310]
When ignoring files with `ExcludeByFile` property OpenCover report contains reference to ignored files anyway, just the coverage is not included, I would expect reference to file should be ignored too (at least that's how opencover worked).

**coverage.opencover.xml**:
CoverageSession/Modules/Module/Files/File:
```xml
<File uid="1" fullPath="Path\To\My\Ignored\File.Designer.cs" />
```
**MyProject.csproj**:
Project/PropertyGroup:
```xml
<ExcludeByFile>**/*.Designer.cs</ExcludeByFile>
```

If I remove `ExcludeByFile` property, it contains that file with it's coverage included.

**Comment by ViktorHofer** [comment]
IMO seems reasonable. You wanna send a contribution to fix this?
