### ISSUE TITLE
coverage for assembly disappeared after some change

### ISSUE THREAD

**Issue by joeharrison714** [tonerdo/coverlet#311]
I made some minor changes to an assembly and now coverage is no longer reported for that assembly by coverlet. Coverage still is reported correctly if i try dotcover. If I revert my changes, coverlet goes back to reporting correctly. I am systematically going though each change to see if I can pinpoint what it was that broke it. All changes were very minor, standard c# changes, no project file changes. Anyone ever see anything like this?

**Comment by tonerdo** [comment]
@joeharrison714 not at all, but helping to pinpoint those changes will go a very long way to figure out similar issues others are having

**Comment by joeharrison714** [comment]
Thanks for the reply. One interesting thing is that if I downgrade to coverlet 2.3, it actually gives me an error about not being able to find a referenced assembly when trying to run tests, and the coverage report fails. Could this still be the underlying issue but in the newer version it is ignored?

**Comment by joeharrison714** [comment]
I was able to work around the problem by adding steps to the Build script to copy the DLL it was complaining about into the folders it was looking for it in.

**Comment by MarcoRossignoli** [comment]
You could also try with
```
dotnet test /p:CollectCoverage=true /p:CopyLocalLockFileAssemblies=true
```
or
```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
BTW in last .net core version 3.0 the build move all packages reference to output folder no more load from global packages location https://github.com/dotnet/cli/issues/12705#issuecomment-535150372

Feel free to close if solved please!

**Comment by MarcoRossignoli** [comment]
Close for stale, feel free to re-open if needed.
