### ISSUE TITLE
Sourcelink filter

### ISSUE THREAD

**Issue by ViktorHofer** [tonerdo/coverlet#312]
We need a filter to not use the source link argument for all assemblies, i.e. ones that we build ourselves (i.e. corefx assemblies) vs. ones that we not build but consume and still need coverage (i.e. System.Private.CoreLib). There are two options:

- Rename the existing argument `--use-source-link` to `--source-link-filter` which accepts a list of assembly names or `all`.
- Add an additional argument `--source-link-filter` which accepts a lit of assembly names which is only used if the option `--use-source-link` is provided.

@tonerdo what's your preference here?

**Comment by ViktorHofer** [comment]
Reopening as this is now pops up again. We want to use the source link information embedded in the assemblies/pdbs and write it into the report but only for non live building assets like System.Private.CoreLib.

cc @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
I prefer non breaking changes approach so new filter args works well to me cc: @tonerdo

**Comment by MarcoRossignoli** [comment]
@ViktorHofer is this feature useful again?If so do you need it for .net tool driver?

**Comment by ViktorHofer** [comment]
It's not very important for us anymore as we are moving assemblies together.

**Comment by MarcoRossignoli** [comment]
Ok feel free to close!
