### ISSUE TITLE
FEAT: net45

### ISSUE THREAD

**Issue by ViceIce** [tonerdo/coverlet#320]
I would like to run coverage for net45 tests.

**Comment by sharwell** [comment]
This is likely covered by #299

**Comment by ViceIce** [comment]
Maybe.

The current problem is that the package props and targets will not be added to a net452 target framework. if i add them manually it will work.

A second problem is a `BadImageFormatException` thrown here:
https://github.com/tonerdo/coverlet/blob/8e618c35ec60bd8dac9410bb28551bf6798490db/src/coverlet.core/Helpers/InstrumentationHelper.cs#L67

There should be a try catch and return false.

Then it will work

**Comment by sharwell** [comment]
The exception sounds like a very different bug (related to a specific assembly referenced by a project, and not characteristic of .NET Framework projects in general).

**Comment by ViceIce** [comment]
The exception can be easily catched by a try catch here:

https://github.com/tonerdo/coverlet/blob/8e618c35ec60bd8dac9410bb28551bf6798490db/src/coverlet.core/Helpers/InstrumentationHelper.cs#L62-L84
