### ISSUE TITLE
not work coverlet.console core 2.2

### ISSUE THREAD

**Issue by akprof2000** [tonerdo/coverlet#321]
If version .net testing application is 2.1 coverlet.console generate result data 
If version .net testing application is 2.2 coverlet.console generate result data always zero

if coverlet.console compiled with version .net 2.2 all data return back
please compile coverlet.console.1.4.X.nupkg in .net 2.2 version

**Comment by MarcoK80** [comment]
We have the same issues when running  .net Core 2.2 and testing asychronous web requests with the aspnet core test server approach. It was running with .net Core 2.1.
