### ISSUE TITLE
Possibility to exclude console table in Global tool / MSBuild?

### ISSUE THREAD

**Issue by LordMike** [tonerdo/coverlet#324]
I'm looking to embed Coverlet as part of a pipeline. In it, we run multiple test projects one by one (multiple `dotnet test` invocations). Adding coverlet would mean that we would get multiple tables in our build log (where I'd prefer to merge the coverlet results and then do one table at the end).

Is there an option I'm missing?

From what I gather, [this code](https://github.com/tonerdo/coverlet/blob/cd2ec73ad72384d7ab7ebc203962ed2e0c24016b/src/coverlet.console/Program.cs#L128-L145) doesn't have any option to disable it, but I might be wrong.

**Comment by LordMike** [comment]
I'm looking into the msbuild task as well, it also does the table by default.

**Comment by LordMike** [comment]
Ideally, for my use case, I would run a lot of coverage operations, get a resulting file, and then presenting a result given the resulting file.

**Comment by tonerdo** [comment]
I believe the best solution to this will be adding solution-wide coverage capabilities to Coverlet

**Comment by tonerdo** [comment]
#357 will track the work need for this scenario
