### ISSUE TITLE
How to include test code in coverage result?

### ISSUE THREAD

**Issue by jamir-araujo** [tonerdo/coverlet#332]
I've notice that Coverlet does not include test code in the coverage result by default. Which is good, I guess.

In my situation I need the test code to be include in the result, but I can't find a way to include manually. I've tried to use the `/p:Include` parameter, but doesn't work.

Is there a way to include the test code in the coverage result or it's something the library will not/can not do?

**Comment by tonerdo** [comment]
Hi @jamir-araujo #318 fixes just that

**Comment by MarcoRossignoli** [comment]
This behaviour will change soon https://github.com/tonerdo/coverlet/pull/318

**Comment by MarcoRossignoli** [comment]
Oops too late 😄

**Comment by jamir-araujo** [comment]
Awesome!!
