### ISSUE TITLE
0 coverage when running integration tests in ASP.NET Core

### ISSUE THREAD

**Issue by tpetrina** [tonerdo/coverlet#333]
When running integration tests as described on [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
) we get 0% for all assemblies.

When those tests are disabled, the code coverage is calculated correctly.

**Comment by tpetrina** [comment]
I am using NUnit and if I remove `[Test]` attribute then the code coverage is calculated normally. If I return it back i.e. the tests are run, code coverage is 0.

**Comment by MarcoRossignoli** [comment]
Weird, can you isolate a small repro?Simila to https://github.com/abe545/CoverletAwaitBranchCoverage

**Comment by tpetrina** [comment]
Weird, I cannot reproduce it in a smaller repo. Need to spend more time on it before calling it a day since it is an issue in our production project.

**Comment by MarcoK80** [comment]
We have the same issues when running  .net Core 2.2 and testing asychronous web requests with the aspnet core test server approach. It was running with .net Core 2.1.

**Comment by tpetrina** [comment]
That is exactly what I am doing!

**Comment by MarcoRossignoli** [comment]
Could be a dup of https://github.com/tonerdo/coverlet/issues/110

**Comment by MarcoRossignoli** [comment]
@tpetrina any news?
Feel free to close if resolved.

**Comment by tpetrina** [comment]
I'll try again with the problematic project, but lately things seem more stable. Good job!

**Comment by MarcoRossignoli** [comment]
@tpetrina any news?

**Comment by tpetrina** [comment]
Apologies for being late, it works fine!

**Comment by sw-ms-ankitsangani** [comment]
@all 

When running integration Test get output 0 in sonar qube. Please Help....

**Comment by MarcoRossignoli** [comment]
@sw-ms-ankitsangani can you open a new issue and provide command line, scenario and if possible some repro?

**Comment by sw-ms-ankitsangani** [comment]
@MarcoRossignoli I have generate new issue. Please help on this.

https://github.com/coverlet-coverage/coverlet/issues/1128
