### ISSUE TITLE
Merging test coverage results when performing `dotnet test solution.sln -p:CollectCoverage=true`

### ISSUE THREAD

**Issue by PeterKnealeBizCover** [tonerdo/coverlet#334]
Is it possible to merge the coverage results of all test projects in a solution 
ie: `Solution.sln` contains multiple xunit test projects
```
dotnet test Solution.sln -p:CollectCoverage=true
```

The ` --merge-with` parameter is mentioned in the below context but i dont know whether or if this can be applied to the above scenario
```
coverlet <ASSEMBLY> --target <TARGET> --targetargs <TARGETARGS> --merge-with "/path/to/result.json"
```

**Comment by tonerdo** [comment]
Coverlet doesn't currently support Solution wide executions. You'll need to run it for each project in the solution

**Comment by onovotny** [comment]
The approach I describe in #177 should work. You'll need to use a tool like ReportGenerator to merge the xml files.

In my `Directory.Build.targets` file, I have this:

```
  <PropertyGroup>
    <IsTestProject>$(MSBuildProjectName.Contains('Test'))</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <UseSourceLink>true</UseSourceLink>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <Exclude>[xunit.*]*</Exclude>
    <CoverletOutput>$(MSBuildThisFileDirectory)coverlet/$(AssemblyName)/$(TargetFramework)/</CoverletOutput>
  </PropertyGroup>
```
It then creates a subdirectory for each assembly and target framework, enabling me to run dotnet test with a wildcard.

**Comment by MarcoRossignoli** [comment]
Tracked by https://github.com/tonerdo/coverlet/issues/357
