### ISSUE TITLE
Invalid paths in coverage report on Linux

### ISSUE THREAD

**Issue by nbaztec** [tonerdo/coverlet#336]
`w/ dotnetcore 2.2 on Ubuntu 18.04`

Hi just did a blanket run with a dotnetcore 2.2 project and v2.5 of coverlet. 

The coverage report generation works okay but the resulting output contains references to some non-existing files like: `C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\Utility\ExceptionExtensions.cs`, `C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\Utility\LoggerHelper.cs`, etc.

Attempting to generate a HTML report with the `lcov` or similar format results in an error since the `genhtml` tool cannot find these files to read.

Any ideas what could be the issue at hand? Thanks.

**Comment by tonerdo** [comment]
That's due to the embedded pdb support. You can try excluding the xunit assemblies

**Comment by tomap** [comment]
`--exclude "[xunit*]*"`

**Comment by nbaztec** [comment]
Thanks guys.
