### ISSUE TITLE
"MergeWith" option doesn't seem to be working for me

### ISSUE THREAD

**Issue by xiaofma** [tonerdo/coverlet#339]
I'm testing coverlet and it seems the "MergeWith" option does not work for me. Here's my setup:

I created a sample solution which contains 4 .Net Core projects: Module1, Module2, Test1, Test2. Test1 tests some method in module1 and test2 tests some method in module2. Then I run command:
`dotnet test Test1.csproj /p:CollectCoverage=true`
it builds the test, run it, and generate a coverage.json file which contains the coverage summary for Module1. Everything is good. The same for Test2. However when running test2 like this:
`dotnet test Test2.csproj /p:CollectCoverage=true /p:MergeWith='C:\TestCoverlet\Test1\Test1\coverage.json'`

The json file generated is identical with the one generated without the "MergeWith" option (only has the code coverage summary for Module2, but no Module1). It seems the option is not taking effect. Did I miss anything? It seems others didn't encounter this issue. I have double checked the file path and made sure the file exists. I also tried using a non-exist file path, it didn't throw any error. This isn't normal, is it?

Packages I used in test1 and test2:
    `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />`
    `<PackageReference Include="MSTest.TestAdapter" Version="1.4.0" />`
    `<PackageReference Include="MSTest.TestFramework" Version="1.4.0" />`
    `<PackageReference Include="coverlet.msbuild" Version="2.5.1" />`

dotnet core version is 2.1.403

**Comment by MarcoRossignoli** [comment]
Can you provide repro similar to https://github.com/abe545/CoverletAwaitBranchCoverage?

**Comment by xiaofma** [comment]
Sure. Please see the repo here: https://github.com/xiaofma/TestCoverletMergeWith
Thanks!

**Comment by MarcoRossignoli** [comment]
Thank's I'll take a look ASAP!

**Comment by pape77** [comment]
works for me

**Comment by pape77** [comment]
I use the output param. Like this 

```
dotnet test Test1.csproj /p:CollectCoverage=true /p:CoverletOutput="/Users/dpaz/Desktop/Test/coverage"
```

```
dotnet test Test2.csproj /p:CollectCoverage=true /p:CoverletOutput="/Users/dpaz/Desktop/Test/coverage" /p:MergeWith="/Users/dpaz/Desktop/Test/coverage.json"`
```

**Comment by xiaofma** [comment]
Thanks @pape77 @MarcoRossignoli . I see you're using Linux so I tried on my Ubuntu 18.04, and it does work, even without the output param, so I don't think that param makes any difference. However when I go back to Windows it still doesn't work, even with the Output param. My windows and Ubuntu have same dotnet core version (2.1.503). Windows version 10.0.17763 Build 17763. Is it possible for you to try on Windows? Thanks a lot!

**Comment by pape77** [comment]
@xiaofma Works like a charm to me in windows powershell

```
PS C:\Users\dpaz\Desktop\Test> dotnet test .\Test1\Test1\Test1.csproj /p:CollectCoverage=true /p:CoverletOutput="C:\User
s\dpaz\Desktop\Test\coverage"
Build started, please wait...
Build completed.

Test run for C:\Users\dpaz\Desktop\Test\Test1\Test1\bin\Debug\netcoreapp2.1\Test1.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.4683 Seconds

Calculating coverage result...
  Generating report 'C:\Users\dpaz\Desktop\Test\coverage.json'

+---------+--------+--------+--------+
| Module  | Line   | Branch | Method |
+---------+--------+--------+--------+
| Module1 | 50%    | 100%   | 50%    |
+---------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 50%    | 100%   | 50%    |
+---------+--------+--------+--------+
| Average | 50%    | 100%   | 50%    |
```

```
PS C:\Users\dpaz\Desktop\Test> dotnet test .\Test2\Test2.csproj /p:CollectCoverage=true /p:CoverletOutput="C:\Users\dpaz
\Desktop\Test\coverage" /p:MergeWith="C:\Users\dpaz\Desktop\Test\coverage.json"
Build started, please wait...
Build completed.

Test run for C:\Users\dpaz\Desktop\Test\Test2\bin\Debug\netcoreapp2.1\Test2.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.5444 Seconds

Calculating coverage result...
  Generating report 'C:\Users\dpaz\Desktop\Test\coverage.json'

+---------+--------+--------+--------+
| Module  | Line   | Branch | Method |
+---------+--------+--------+--------+
| Module2 | 50%    | 100%   | 50%    |
+---------+--------+--------+--------+
| Module1 | 50%    | 100%   | 50%    |
+---------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 50%    | 100%   | 50%    |
+---------+--------+--------+--------+
| Average | 25%    | 50%    | 25%    |
+---------+--------+--------+--------+
```

**Comment by xiaofma** [comment]
Thanks @pape77  it's really weird that it starts working for me as well... maybe the path was wrong before. I'm sorry that you had to spend time looking into this. Thanks for your help!

**Comment by pape77** [comment]
@xiaofma No problem :)
