### ISSUE TITLE
Suspicious Average

### ISSUE THREAD

**Issue by bmccord** [tonerdo/coverlet#346]
We have an application with 5 projects.  I installed coverlet and ran the coverage.  We currently have 100% coverage (project is just starting).  Here are the results:

+------------------------------------------------+--------+--------+--------+
| Module                                         | Line   | Branch | Method |
+------------------------------------------------+--------+--------+--------+
| Project 1                                       | 100%   | 100%   | 100%   |
+------------------------------------------------+--------+--------+--------+
| Project 2                                       | 100%   | 100%   | 100%   |
+------------------------------------------------+--------+--------+--------+
| Project 3                                       | 100%   | 100%   | 100%   |
+------------------------------------------------+--------+--------+--------+
| Project 4                                       | 100%   | 100%   | 100%   |
+------------------------------------------------+--------+--------+--------+
| Project 5                                       | 100%   | 100%   | 100%   |
+------------------------------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|                 | Line       | Branch | Method |
+---------+--------+--------+--------+
| Total        | 100%     | 100%    | 100%   |
+---------+--------+--------+--------+
| Average  | 20%       | 20%      | 20%    |
+---------+--------+--------+--------+

This doesn't seem right to me.  It's 100% coverage across the board for each project, but the average is only 20% across the board.  I understand how it is getting it (100 / 5), but I don't think the average is an accurate reflection.

It seems that the average should also be 100%.

**Comment by tonerdo** [comment]
@bmccord I think this might be a side effect of how Coverlet displays results. For example, if the code contains no branches, Coverlet will display 100% instead of 0%. However, when calculating the total and average it'll use the `0` value.

**Comment by bmccord** [comment]
@tonerdo Is that the way it should function or is this considered a bug?

**Comment by danielloganking** [comment]
I was also wondering if excluded projects had something to do with this?

**Comment by diegofox2** [comment]
Hi guys. I see this bug still opened, is this right?

**Comment by AlexTeixeira** [comment]
Same issue for me. 

+-------------------------------+------+--------+--------+
| Module                        | Line | Branch | Method |
+-------------------------------+------+--------+--------+
| GardenDynamics.Infrastructure | 100% | 100%   | 100%   |
+-------------------------------+------+--------+--------+
| GardenDynamics.Domain         | 100% | 100%   | 100%   |
+-------------------------------+------+--------+--------+
| GardenDynamics.Application    | 100% | 100%   | 100%   |
+-------------------------------+------+--------+--------+

+---------+-------------------+-------------------+-------------------+
|         | Line              | Branch            | Method            |
+---------+-------------------+-------------------+-------------------+
| Total   | 100%              | 100%              | 100%              |
+---------+-------------------+-------------------+-------------------+
| Average | 33.3333333333333% | 33.3333333333333% | 33.3333333333333% |
+---------+-------------------+-------------------+-------------------+

**Comment by dlplenin** [comment]
> @bmccord I think this might be a side effect of how Coverlet displays results. For example, if the code contains no branches, Coverlet will display 100% instead of 0%. However, when calculating the total and average it'll use the `0` value.

Hi @tonerdo @MarcoRossignoli 
I did a fork just to check how Average is working.
Could you take a look at: https://github.com/dlplenin/coverlet 
I did minor changes to calculate avegare based on average from all projects. Im not sure if it is ok only to modify `CalculateLineCoverage(Modules modules)` functions.
If it is right, only a change in CoverageResult.cs is needed (just to keep same logic, because it switch-case (ThresholdStatistic.Average) was working well):

```
//#line: 204 
//foreach (var module in Modules)
//{
//    line += summary.CalculateLineCoverage(module.Value).Percent;
//    branch += summary.CalculateBranchCoverage(module.Value).Percent;
//    method += summary.CalculateMethodCoverage(module.Value).Percent;
//}

line = summary.CalculateLineCoverage(Modules).AveragePercent;
branch = summary.CalculateBranchCoverage(Modules).AveragePercent;
method = summary.CalculateMethodCoverage(Modules).AveragePercent;
.
.
.
//if ((line / numModules) < threshold)
 if (line < threshold)
```
Or maybe is better just to copy current logic from CoverageResult.cs to Program.cs:

```
//#line:175
                //these lines **
                double line = 0;
                double branch = 0;
                double method = 0;

                foreach (var _module in result.Modules)
                {
                    var linePercent = summary.CalculateLineCoverage(_module.Value).Percent;
                    var branchPercent = summary.CalculateBranchCoverage(_module.Value).Percent;
                    var methodPercent = summary.CalculateMethodCoverage(_module.Value).Percent;

                    //and these***
                    line += linePercent;
                    branch += branchPercent;
                    method += methodPercent;

                    coverageTable.AddRow(Path.GetFileNameWithoutExtension(_module.Key), $"{linePercent.ToString("0.00")}%", $"{branchPercent.ToString("0.00")}%", $"{methodPercent.ToString("0.00")}%");
                }
```
![image](https://user-images.githubusercontent.com/2582026/60236045-887a0280-986f-11e9-8130-6c724679c790.png)

Thanks!

**Comment by MarcoRossignoli** [comment]
Diego feel free to open a PR with your changes we'll discuss solutions directly there otherwise there is a risk to fill issue thread and will be less clear what is the problem.
Thanks for your effort here!
