### ISSUE TITLE
Absolute Path in /p:CoverletOutput fails

### ISSUE THREAD

**Issue by nzain** [tonerdo/coverlet#348]
I don't want to see results inside my project directories but gather all results into something like `solutionDir\TestResults\`. Therefore, I've set an absolute path via `/p:CoverletOutput='D:\Foo\Bar\TestResults\'` but coverlet then fails:

```
C:\Users\pstalph\.nuget\packages\coverlet.msbuild\2.5.1\build\netstandard2.0\coverlet.msbuild.targets(33,5): error : The filename, directory name, or volume label syntax is incorrect : 
'D:\Foo\Bar\Tests\Bar.Tests\'D:\Foo\Bar\TestResults' 
[D:\Foo\Bar\Tests\Bar.Tests\Bar.Tests.csproj]
```

It seems the property is converted to an absolute path again.

**Comment by nzain** [comment]
This is actually a documentation vs batch file problem. Absolute and relative paths work as intended, but not when use single quotes in a windows batch file as the readme.md suggests:

> `dotnet test /p:CollectCoverage=true /p:CoverletOutput='./results/'`

Removing the single quotes made it work for my scenario. Feel free to close this (or investigate further).

**Comment by onovotny** [comment]
Easiest thing is to set CoverletOutput in your csproj or a Directory.Build.targets. Then you can make it dynamic too.

https://github.com/dotnet/reactive/blob/350b62266a3a6998f2291f66d3852a24876efedb/Ix.NET/Source/Directory.build.targets#L26-L32

**Comment by nzain** [comment]
Nice idea @onovotny but `$(AssemblyName)` is empty in my case and all coverage reports would go to the same file overwriting each other. I guess, this is because our `Directory.build.props` lives in solution root and is evaluated before anything else. In fact your structure looks similar, so how did you get this variable filled?
