### ISSUE TITLE
coverlet.msbuild does not work for projects targeting .NET Framework 4.6

### ISSUE THREAD

**Issue by sharwell** [tonerdo/coverlet#358]
This regression was introduced in #355.

> ❗️ This change broke coverlet support for projects targeting .NET Framework prior to 4.6.1. Placing the props/targets in a framework-specific folder makes them dependent on the declared target framework of the project, which we do not want. We only want them to be dependent on the target framework of the currently executing version of MSBuild.

_Originally posted by @sharwell in https://github.com/tonerdo/coverlet/pull/355#discussion_r262329107_

**Comment by tonerdo** [comment]
Hmm..I see. Will update and include in the next release. Thanks

**Comment by ViceIce** [comment]
The files can be simply put in the build folder, then it is working fine
