### ISSUE TITLE
How can I union coverage results in one file?

### ISSUE THREAD

**Issue by Valeriy1991** [tonerdo/coverlet#36]
Hello! 

I have multiple tests projects - one with unit tests and one with integration tests. How can I calculate code coverage for both projects with coverlet?

**Comment by dmccaffery** [comment]
This is especially important if attempting to upload test results to VSTS, which is expecting a single summary file (and grabs the last match if using a glob pattern).

**Comment by dmccaffery** [comment]
![grumble, grumble](https://user-images.githubusercontent.com/1803684/39091265-73faffe4-45a5-11e8-914f-e4ac5bc32ba8.png)

**Comment by OneCyrus** [comment]
is there an API to hook in to once all tests are complete? i guess currently a single instance of coverlet doesn't know if it's the last time a test is called and would need to consolidate the results for every test project.

**Comment by Hugh-walsh** [comment]
We run several tests in parallel using gitlab CI so would like to take the output files and combine them to give an overall result.  Would be nice if this were possible.

**Comment by patros** [comment]
@aptester's suggestion works well for generating a report. But not a combined xml for VSTS unfortunately :(

**Comment by skoruba** [comment]
@tonerdo What do you think about it? Do you have any suggestions for it? Thx.

**Comment by sjk07** [comment]
i want this so bad! :wink:

**Comment by tonerdo** [comment]
I'm gonna explore how existing tools achieve this and see how best to implement since it's a popular ask. Will go a lot faster if I can get some help 😄

**Comment by basilfx** [comment]
I've started something [over here](https://github.com/basilfx/coverlet/commits/feature/merge_ir), which I'm  currently testing and will PR if ready. This basically allows one to merge the coverage result of one run, with an intermediate result of a previous run.

It's somewhat similar to what OpenCover offers.

Note that this will generate the 'final' report for each intermediate run, so there is some overhead, but should just be as simple as adding `/p:CoverletIntermediateResult=output.json`.

**Comment by tonerdo** [comment]
Awesome @basilfx, thanks a lot for the help

**Comment by basilfx** [comment]
The PR is here: https://github.com/tonerdo/coverlet/pull/123.

**Comment by tonerdo** [comment]
@basilfx can you please point me to the where OpenCover documents its implementation of this feature? Thanks

**Comment by basilfx** [comment]
You can find it here: https://github.com/opencover/opencover/wiki/Usage

Look for -merge output and -mergebyhash.
