### ISSUE TITLE
Error "Could not find file "

### ISSUE THREAD

**Issue by hlubovac** [tonerdo/coverlet#360]
Could you please take a look at this and see if it falls within your realm: https://github.com/xunit/xunit/issues/1909

What the xunit guys are suggesting is definitely not within the realm of my project. Something changed within the host environment that perhaps now requires a different set of arguments for `dotnet test`. Thank you.

**Comment by tonerdo** [comment]
You should ignore all `xunit` assemblies

**Comment by MarcoRossignoli** [comment]
dup https://github.com/tonerdo/coverlet/issues/359#issuecomment-469577948

you have to exclude xunit or include only specific lib i.e.  `/p:Exclude="[xunit*]*"` or  `/p:Include="[Build]*"` you can verify instrumented lib appending `-v:n` at the end of `dotnet test` command.

**Comment by MarcoRossignoli** [comment]
@hlubovac have you tried?can be close issue?

**Comment by hlubovac** [comment]
Hi - yes, I tried few variations of those: excluding "xunit" worked - thank you!

However, I still find it weird that this started happening with no actual changes within compiled/tested source files or the script-file that actually executes `dotnet test` or any of the involved file-locations. Perhaps I'm overlooking a forced nuget-package version change or something. I'll watch for this. Thank you!

**Comment by MarcoRossignoli** [comment]
Let us know if you need further help!Happy coding!
