### ISSUE TITLE
Incorrect TargetPath with combination of PLATFORM envvar and --no-build

### ISSUE THREAD

**Issue by tylerohlsen** [tonerdo/coverlet#374]
I'm using coverlet.msbuild version 2.6.0 and my build pipeline sets the environment variable `PLATFORM` to `x64`.  That environment variable in combination with `--no-build` causes the calculated target path to be incorrect.

Here's the error I get when that combination is in play after I've built the solution.

```
C:\Users\[MyUser]\.nuget\packages\coverlet.msbuild\2.6.0\build\netstandard2.0\coverlet.msbuild.targets(7,5): error : Could not find a part of the path '[MyTestProjectPath]\bin\X64\Debug\netcoreapp2.2'
```

The calculated target path is 
`bin\X64\Debug\netcoreapp2.2`
but the actual target path of the already built solution is
`bin\Debug\netcoreapp2.2`

**Comment by tonerdo** [comment]
@tylerohlsen Coverlet only uses the value of the `TargetPath` provided to it by MSBuild and does not itself deduce where the assembly is located

**Comment by tylerohlsen** [comment]
Understood.  I discovered new information on why this is happening and created a new issue in the dotnet/cli project here: https://github.com/dotnet/cli/issues/11051.  

This issue in coverlet can be closed.
