### ISSUE TITLE
Make app / assembly version match releases

### ISSUE THREAD

**Issue by jburnett** [tonerdo/coverlet#380]
Why do version numbers mismatch? The most recent version of coverlet is [v5.0.0](https://github.com/tonerdo/coverlet/releases/tag/v5.0.0), but the app reports version 1.5.0.0.  This seems confusing to new-comers, particularly since semantic versioning has been the norm for years.

**Comment by tonerdo** [comment]
@jburnett coverlet is made up of three separate components; the core library `coverlet.core`, the msbuild library `coverlet.msbuild` and the global tool `coverlet.console`. Each of these are versioned separately and follow the rules of semver. The releases in this repo represent the core library, the other components are represented through their respective NuGet packages
