### ISSUE TITLE
Adjust log level when using coverlet.console (global tool)

### ISSUE THREAD

**Issue by ViktorHofer** [tonerdo/coverlet#381]
How can I adjust the log level when using coverlet.console - the global tool - and not coverlet.msbuild?

cc @MarcoRossignoli @tonerdo

**Comment by MarcoRossignoli** [comment]
AFAIK at the moment is not possible avoid [`PrepareModules`](https://github.com/tonerdo/coverlet/blob/master/src/coverlet.console/Program.cs#L64) logs, coverlet.console use a simple `ConsoleLogger` implementation.
We should add control switch similar to `TaskLoggingHelper` https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019
```
-v|--verbosity q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]
```
At the moment we use information/warning/error so we could print  always error/warning and info for level > `q[uiet]` (like now `minimal` level log inclusion/exclusion list)
What do you think @tonerdo?
