### ISSUE TITLE
Line coverage output should be rounded

### ISSUE THREAD

**Issue by ViktorHofer** [tonerdo/coverlet#382]
+------------------------+---------------------+--------+--------+
  | Module                 | Line                | Branch | Method |
  +------------------------+---------------------+--------+--------+
  | System.AppContext      | 100%                | 100%   | 100%   |
  +------------------------+---------------------+--------+--------+
  | System.Private.CoreLib | 14.000000000000002% | 9.5%   | 12%    |
  +------------------------+---------------------+--------+--------+

  +---------+---------------------+--------+--------+
  |         | Line                | Branch | Method |
  +---------+---------------------+--------+--------+
  | Total   | 14.000000000000002% | 9.5%   | 12%    |
  +---------+---------------------+--------+--------+
  | Average | 7.000000000000001%  | 4.75%  | 6%     |
  +---------+---------------------+--------+--------+

**Comment by tonerdo** [comment]
@ViktorHofer do you propose a floor or a ceiling?

**Comment by ViktorHofer** [comment]
Probably floor but I don't have a strong opinion here.

**Comment by MarcoRossignoli** [comment]
I'm for floor

**Comment by tonerdo** [comment]
The floors have it then. I think method and branch coverage could also benefit from this

**Comment by sasivishnu** [comment]
Hi, 
If no one is working on the issue, can I take a look into it? 
Also, I think we use floor & keep it to maximum of 2 decimal places. What you think?Especially in bigger projects, It will be better to have 82.23% then 82%

**Comment by MarcoRossignoli** [comment]
@sasivishnu sure give it a try!
I'm ok with 2 decimal places, but we can delay the choice at review time!
Let me know if you'll be in trouble with something.

**Comment by sasivishnu** [comment]
Thanks, I will work on this weekend. 

I was able to build the project and will spend time understanding the flow. If there is any document/guide/tips on how to run & debug project locally will be helpful.

**Comment by MarcoRossignoli** [comment]
You can use some of summary unit test https://github.com/tonerdo/coverlet/blob/master/test/coverlet.core.tests/CoverageSummaryTests.cs
Open `coverlet.sln` in VS and debug some test:
![image](https://user-images.githubusercontent.com/7894084/57176095-e7189680-6e53-11e9-8038-5bcfd7af3e06.png)

**Comment by sasivishnu** [comment]
Since it is fixed, should we close this issue now?

**Comment by MarcoRossignoli** [comment]
Yes thank's again!
