### ISSUE TITLE
Exit code for coverlet should communicate different failures

### ISSUE THREAD

**Issue by ardove** [tonerdo/coverlet#388]
Today, when a test fails or code coverage fails, a non-zero exit code is returned. This is desirable because it allows build automation systems to fail when the coverlet command fails. Unfortunately, the return code is always 1 so it doesn't provide detail about what went wrong. One could, theoretically, grep the output of coverlet for things like "the minimum line coverage is below specified 95", but this is brittle and unnecessary (since that is already written to stdout and can be inspected by a human). 

To better support build automation systems it'd be great if coverlet exited with specific non-zero exit codes to communicate why the build failed so that programmatic action can be taken upon that code without needing to do something hacky like grep the output. 

Here's a proposal:
* Return 2 when a test fails
* Return 3 when coverage is below the configured threshold
* Return 5 when both a test fails AND coverage is below the configured threshold
* Updated documentation reflecting this behavior

I'm not married to the actual numbers, just that they are specific and documented.

**Comment by MarcoRossignoli** [comment]
I think it's not possible...we rely on `dotnet test` command and by design we cannot change return value https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21#description, I found some discussion on test repo https://github.com/Microsoft/vstest/issues/1624
Also as regards msbuild task(internally used by test verb), we cannot return only `true` or `false` https://docs.microsoft.com/en-us/visualstudio/msbuild/task-writing?view=vs-2019#tasks

**Comment by ardove** [comment]
Right, but `dotnet test` is just used for the test portion, right? So you should know whether or not tests fail at the point that you invoke that command. And then, when you calculate coverage, you should know whether or not it passed. At that point, you should have enough to determine what passed and what failed.

**Comment by MarcoRossignoli** [comment]
I think we could do something for dotnet tool version because we "host" the process of instrumentation and coverage calculation https://github.com/tonerdo/coverlet/blob/master/src/coverlet.console/Program.cs#L205
But I don't know if we can do the same for msbuild version because we inject coverage calculation throught a task after VSTest https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/coverlet.msbuild.targets#L36 and from that we can only return true or false to msbuild infrastructure https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L195

For now labeled "as-designed" what do you think @tonerdo?

**Comment by tonerdo** [comment]
Exit codes do sound like a good idea. I'm not big on maintaining UX parity between tool and msbuild as they're already being used in different scenarios

**Comment by MarcoRossignoli** [comment]
We could use:
 1 for test fail(like `dotnet test`)
 2 when "any" coverage is below the configured threshold
 3 when both a test fails AND coverage is below the configured threshold

the alg could be a simple sum.

@ardove is there a specific meaning for your "exit code"?

**Comment by ardove** [comment]
Yeah, the actual number doesn't matter to me. Just that they are disambiguated. We need it to have correct and specific messages when run from a Jenkinsfile using a scripted pipeline. We'd like to fail with an error that says "code coverage was below threshold" OR "tests failed" OR "code coverage was low AND unit tests failed". 

Right now, we can only say "code coverage was below threshold and/or unit tests failed", but the reader of that then needs to go an inspect a different error message to figure out which it was.  

If I were implementing it, I'd probably reserve 1 for unhandled errors and use something more specific to indicate specific handle-able errors (which was why I originally mentioned 2, 3, and 5 for the same cases you just mentioned).

**Comment by MarcoRossignoli** [comment]
@ardove can you confirm you're using Coverlet dotnet tool?

**Comment by ardove** [comment]
Yes, that's correct. I'm not using the msbuild integration.

**Comment by MarcoRossignoli** [comment]
Can we agree with https://github.com/tonerdo/coverlet/issues/388#issuecomment-488682044?

**Comment by ardove** [comment]
Works for me.

**Comment by sasivishnu** [comment]
I can pick this but I am out for weekend and can start working from next week.

**Comment by sasivishnu** [comment]
> 
> 
> We could use:
> 1 for test fail(like `dotnet test`)
> 2 when "any" coverage is below the configured threshold
> 3 when both a test fails AND coverage is below the configured threshold
> 
> the alg could be a simple sum.
> 
> @ardove is there a specific meaning for your "exit code"?

I am back now. Just for confirmation, we are going with this error code level only? What error code to return for invalid commands? Currently for CommandParsingException, we return 1. 

Btw, I agree with @ardove that we should consider reserving 1 for common errors and then go with 2, 3 and 5 for specific errors.

**Comment by MarcoRossignoli** [comment]
> Although it seems decided, I do agree with @ardove that we should consider reserving 1 for common errors and then go with 2, 3 and 5 for specific errors.

My idea of 1 for test error comes from fact that `dotnet test` return 1 if some test fail per guide https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21 and we could be in line with that.
```
 If all tests are successful, the test runner returns 0 as an exit code; otherwise if any test fails, it returns 1. 
```
Maybe for parsing and exception we could return -1 to keep alg simple sum.
BTW I won't oppose on other ideas, wait @tonerdo thoughts, for now you can work on it will be a simple numbering changes on review in case.

**Comment by sasivishnu** [comment]
@MarcoRossignoli okay. Yeah, keeping "1" reserved to be in-line with dotnet test output seems valid.

I pushed my changes now. I went with higher exit code values for exception and parsing.
