### ISSUE TITLE
System.Reflection.Metadata version mismatch unable to find file System.Reflection.Metadata,Version=1.4.3.0

### ISSUE THREAD

**Issue by vagisha-nidhi** [tonerdo/coverlet#391]
I am trying to load coverlet into a [datacollector ](https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md)which would collect coverage and report back the results to [TestPlatform](https://github.com/Microsoft/vstest). The issue with loading coverlet APIs is that coverlet.core depends on [System.Reflection.Metadata, AssemblyVersion : 1.4.3.0](https://github.com/tonerdo/coverlet/blob/062b907735901bdf3ad9d4d40953f53a4fe3f364/src/coverlet.core/coverlet.core.csproj#L12) and the datacollector process (in which it is being loaded) has a dependency on System.Reflection.Metadata, AssemblyVersion=1.4.2.0

This results in **System.Reflection.Metadata, AssemblyVersion=1.4.2.0** being loaded and coverlet erroring out with `System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file.`

This can be resolved with lowering down the version of [System.Reflection.Metadata](https://github.com/tonerdo/coverlet/blob/062b907735901bdf3ad9d4d40953f53a4fe3f364/src/coverlet.core/coverlet.core.csproj#L12).

I am a Software Engineer on the [TestPlatform](https://github.com/Microsoft/vstest) team and can raise a PR to address the issue.

**Comment by MarcoRossignoli** [comment]
> I am trying to load coverlet into a datacollector which would collect coverage and report back the results to TestPlatform. 

Can you elaborate the scenario?We have some work in place to use coverlet with data collector to fix issue where test plat kill process before we can save instrumentation report file to disk https://github.com/tonerdo/coverlet/pull/329

**Comment by vagisha-nidhi** [comment]
@MarcoRossignoli 
We have written an [outproc datacollector](https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md) that references coverlet.core.dll. This calls into coverlet APIs such as coverage.PrepareModules(), coverage.GetCoverageResult(). We get coverage results thus and send these back to testplatform using [DataCollectionSink](https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md#datacollectionsink). 

The issue I have already mentioned is that datacollector has a dependency on Microsoft.TestPlatform.ObjectModel [here](https://github.com/Microsoft/vstest/blob/master/src/datacollector/datacollector.csproj#L22) which has a dependency on System.Reflection.Metadata, AssemblyVersion=1.4.2.0 [here](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Microsoft.TestPlatform.ObjectModel.csproj#L37). Due to the datacollector dependency, System.Reflection.Metadata, AssemblyVersion=1.4.2.0 is already loaded and coverlet errors out saying it cannot find System.Reflection.Metadata, AssemblyVersion=1.4.3.0, since it is unable to load System.Reflection.Metadata again. 
#329 is a different issue.

**Comment by MarcoRossignoli** [comment]
Understood, apart from this issue I'm warning you that we're working on internals to allow [better testability](https://github.com/tonerdo/coverlet/issues/387) and I don't guarantee that "internal api" like `coverage.PrepareModules()` `coverage.GetCoverageResult()` will be untouched, to achieve [this](https://github.com/tonerdo/coverlet/issues/212) cc @tonerdo

**Comment by tonerdo** [comment]
@vagisha-nidhi like @MarcoRossignoli mentioned the `coverlet.core` API is subject to change on a whim. Out of curiosity, are you using an unofficial NuGet or a local build of `coverlet.core`?

**Comment by vagisha-nidhi** [comment]
@tonerdo Yeah. Noted the warning. I have been using a local build of coverlet.core (setting hintpath to coverlet.core dll).

**Comment by MarcoRossignoli** [comment]
fixed in #392
