### ISSUE TITLE
How to generate report from visual studio project post build event

### ISSUE THREAD

**Issue by ftaran** [tonerdo/coverlet#400]
Hello

Is it possible to generate a report using the nuget package everytime the test project is built?

I'm talking about maybe using a command in the project post build events. Can you provide an example please?

Also is it possible to only have a text reporting that only contains the stats table?

**Comment by MarcoRossignoli** [comment]
> Is it possible to generate a report using the nuget package everytime the test project is built?
I'm talking about maybe using a command in the project post build events. Can you provide an example please?

I think it's possible if you add to "post build" events(using VS studio) and something like https://github.com/tonerdo/coverlet#coverage-output-1 with correct VS environment vars.
BTW I've got a doubt...can you explain better your scenario?Instrumenting/Testing/Reporting is a bit "heavy" process and run for every "build" of project could slowdown dev process.

> Also is it possible to only have a text reporting that only contains the stats table?

At the moment we don't have switch to exclude/include module/stats table...do you need to extrapolate values or is only a "ui noise" issue?

**Comment by ftaran** [comment]
@MarcoRossignoli

I would like to include the report as part of every pull request so that we can keep track of the changes and see any significant changes as soon as possible and fix any issues immediately.

If it would hinder dev process then it might not be a good idea. Do you have any alternative way of doing this?

**Comment by MarcoRossignoli** [comment]
We use codecov is a possible alternative? https://docs.codecov.io/docs/pull-request-comments
