### ISSUE TITLE
Branch coverage mismatch between Coverlet and generated OpenCover report

### ISSUE THREAD

**Issue by seesharper** [tonerdo/coverlet#401]
Hi!

I have a situation where Coverlet reports the following.

```
 Generating report 
+----------+------+--------+--------+
| Module   | Line | Branch | Method |
+----------+------+--------+--------+
| DbReader | 100% | 99.7%  | 100%   |
+----------+------+--------+--------+
```

Then if I convert the `coverage.opencover.xml` to an HTML report using ReportGenerator I get a branch coverage of 100%

![image](https://user-images.githubusercontent.com/1034073/57221333-20413a00-6fff-11e9-8b7e-ca34238ba597.png)

Where should I start to look here? Is there some way to make Coverlet output exactly where the branch coverage is insufficient?

**Comment by MarcoRossignoli** [comment]
Instinctively seems some round issue, if project is not private can you share your `coverage.opencover.xml` or better a json format(`native` coverlet format, easier to debug)?

**Comment by seesharper** [comment]
Hi @MarcoRossignoli  and thanks for your quick reply. 

Here is my coverage file 👍

[coverage.json.zip](https://github.com/tonerdo/coverlet/files/3147762/coverage.json.zip)

**Comment by MarcoRossignoli** [comment]
Ok I'll take a look ASAP.

**Comment by MarcoRossignoli** [comment]
I did a check and seems that report you linked is "rounded"(maybe by parser) because generated xml report correct `branchCoverage="99.7"`
```xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession>
  <Summary numSequencePoints="1028" visitedSequencePoints="1028" numBranchPoints="304" visitedBranchPoints="303" sequenceCoverage="100" branchCoverage="99.7" maxCyclomaticComplexity="460" minCyclomaticComplexity="460" visitedClasses="75" numClasses="79" visitedMethods="232" numMethods="232" />
  <Modules>
    <Module hash="573D4983-FCFD-4272-AF7C-75D3A5F1F28A">
      <ModulePath>DbReader.dll</ModulePath>
      <ModuleTime>2019-05-06T12:55:28</ModuleTime>
      <ModuleName>DbReader</ModuleName>
      <Files>
        <File uid="1" fullPath="/Users/bernhardrichter/GitHub/DbReader/src/DbReader/ArgumentProcessor.cs" />
        <File uid="2" fullPath="/Users/bernhardrichter/GitHub/DbReader/src/DbReader/CompositionRoot.cs" />
        <File uid="3" fullPath="/Users/bernhardrichter/GitHub/DbReader/src/DbReader/DataReaderExtensions.cs" />
        <File uid="4" fullPath="/Users/bernhardrichter/GitHub/DbReader/src/DbReader/DataRecordExtensions.cs" />
```
Calculation seem ok 1 branch not covered.

![image](https://user-images.githubusercontent.com/7894084/57227824-9ac78500-7012-11e9-88a9-19d2c78a565e.png)

**Comment by seesharper** [comment]
Ah, thanks. So the xml file is correct. This issue may belong in the `ReportGenerator` repo then? 😀

**Comment by MarcoRossignoli** [comment]
> Ah, thanks. So the xml file is correct. 

Calculated value in xml file are ok to me, maybe report generator do some rounding.
Close this for the moment, we'll re-open if necessary.
