### ISSUE TITLE
Unable to change paths in cobertura report

### ISSUE THREAD

**Issue by EricStG** [tonerdo/coverlet#413]
Getting an issue where our application is compiled within docker and we're trying to export the cobertura xml file from it. 

Since the `filename` attribute is the full path to the file, we need to do a search a replace. 

Adding the root of the project to `sources/source` and using relative paths for `filename`, it would be a lot easier to manager.

**Comment by sasivishnu** [comment]
I agree, this will be nice enhancement. Instead of doing only for cobertura format, It will be good to do for all other format's except Team City. We can add one more options, `--format --relative-code-path`

**Comment by MarcoRossignoli** [comment]
could be similar to https://github.com/tonerdo/coverlet/issues/408?
and https://github.com/tonerdo/coverlet/issues/408#issuecomment-491502234 could fix?

**Comment by sasivishnu** [comment]
Seems like Coverlet was using relative path earlier but @tonerdo changed it.

[#295 (Comment)](https://github.com/tonerdo/coverlet/issues/295#issuecomment-469011441)

> This happens because I switched to using absolute paths. #356 re-includes the source element

I think, change was done as part of  #260
https://github.com/tonerdo/coverlet/commit/de558c5f62b46d30fb2ba15231e50fc7f41877f7?diff=unified

There is an open issue for similar request in Icov Format, #263

**Comment by ViceIce** [comment]
jenkins don't like absolute path, I would like to see a switch to change to relative path.

**Comment by MarcoRossignoli** [comment]
FYI https://github.com/tonerdo/coverlet/issues/408#issuecomment-497674737

**Comment by daveMueller** [comment]
In #614 we changed the cobertura report back to using relative paths so that the jenkins plugin is working again and the source link option is still supported. 
The difference is that currently the root dir of the OS is used in ```sources/source``` and not the root of the project. Most likely this could be changed but I'm not really sure how to determine the root of the project? To be precise, I'm not sure about the definition of project root. Is it the .csproj files, the .sln file or even the repository?
@MarcoRossignoli What do you think?

**Comment by MarcoRossignoli** [comment]
@daveMueller I think that we shouldn't search the "root" of a project, but the algs should simply try to find longest shared absolute(per drive on win) and add to sources, the relative parts will go inside file attribute.

Report is "unrelated" to project structure and we don't know how a project will be setup, could be created runtime, could o couldn't have a sln an so on...report wants only "locate" source files.
Something similar to trie structure where the absolute stops at first fork and letter are folders.

**Comment by daveMueller** [comment]
@MarcoRossignoli I got it. Is it OK when I work on it?

**Comment by MarcoRossignoli** [comment]
Yes thank's!
