### ISSUE TITLE
coverlet.msbuild /p:UseSourceLink=true causes exception

### ISSUE THREAD

**Issue by dbolin** [tonerdo/coverlet#418]
On windows 10, dotnet core 3 preview 5.
[Using this repo](https://github.com/dbolin/Apex.Serialization), running the following command:

dotnet test Tests/Apex.Serialization.Tests/Apex.Serialization.Tests.csproj -f netcoreapp2.2 -c Debug --logger "trx;LogFileName=results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[Apex.*]*" /p:UseSourceLink=true

Fails after printing "Calculating coverage result..." with the error "The given key '' was not present in the dictionary." at at Coverlet.Core.Coverage.GetSourceLinkUrl(Dictionary`2 sourceLinkDocuments, String document)

Everything works as expected if the UseSourceLink switch is omitted.

**Comment by MarcoRossignoli** [comment]
@dbolin you can try our nightly build, it should fix your issue https://www.myget.org/feed/coverlet-dev/package/nuget/coverlet.msbuild/2.6.1-g0dd56242f2

**Comment by josuuribe** [comment]
Hi, I have the exact same issue in Azure DevOps with the last version available, I do not use Sonnar or any other third party tool, it's easy to reproduce:

1. Use the default Azure Build Pipeline .Net Core template (like Asp.Net Core) and putting these arguments in Azure DevOps .net core task:

--no-build --configuration $(BuildConfiguration) /p:CollectCoverage=true /p:Threshold=85 /p:UseSourceLink=true /p:CoverletOutputFormat=cobertura  /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/

![image](https://user-images.githubusercontent.com/20932002/84576343-53362f80-adb4-11ea-9c6a-ae4ae055e8db.png)

Thanks,

**Comment by MarcoRossignoli** [comment]
@josuuribe pls can you open new issue?
