### ISSUE TITLE
Instrumentation only reported on 1 dll in build

### ISSUE THREAD

**Issue by brewsoftware** [tonerdo/coverlet#42]
Hey, 
  So I'm having an issue where it appears as though only the first DLL in the output build is being instrumented. We have 5 dll's being output in a linux .net core project. Coverage works for 1 dll (alphabetical first from what I can tell) but the other dll's are all being reported as 0 coverage.

Cheers,
Jason

**Comment by tonerdo** [comment]
This is the same problem in #18 which has been fixed in #27 but not yet released as NuGet package. The new release bits will drop within 8 hours from the time of this comment

**Comment by tonerdo** [comment]
Use latest NuGet bits https://www.nuget.org/packages/coverlet.msbuild/1.1.0
