### ISSUE TITLE
Example using Threshold

### ISSUE THREAD

**Issue by timker** [tonerdo/coverlet#43]
I assumed adding
```
  dotnet test  /p:CollectCoverage=true  /p:Threshold=100
```
would cause dotnet test to return a non zero result.

How do you use Threshold in project to fail the test run?

**Comment by tonerdo** [comment]
@timker you're correct! Been occupied with preparing master for a new release. A new NuGet package will go out within the next 8 hours

**Comment by tonerdo** [comment]
New NuGet release https://www.nuget.org/packages/coverlet.msbuild/1.1.0 See https://github.com/tonerdo/coverlet/tree/v1.1.0#threshold for sample usage
