### ISSUE TITLE
Set cloud build number based on official build version

### ISSUE THREAD

**Issue by AArnott** [tonerdo/coverlet#438]
See [cloud build considerations](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md) for options. 

In this repo you have 3 unique version.json files, which begs the question of which version you consider to be "official" or most broadly applicable that you'd want to use as the cloud build number.

**Comment by MarcoRossignoli** [comment]
> which begs the question of which version you consider to be "official" 

At the moment are all three "official" we are  treating three package as "separate" product with some difference, we have different feature support between console(dotnet tool) msbuild and collector usage.

**Comment by AArnott** [comment]
Interesting. Do you intend to continue with 3 distinct versions of packages shipping from each commit? 
If so, the a cloud build number probably would be more confusing than anything and you can Won't Fix this.

And FYI, when you want to translate a version number back into a commit, you'll need to specify the path to the project whose version you're starting from:
```
nbgv get-commits -p src\coverlet.console 1.2.3
```

**Comment by MarcoRossignoli** [comment]
> Interesting. Do you intend to continue with 3 distinct versions of packages shipping from each commit?

I think so, but maybe @tonerdo can answer better than me he published coverlet before I started to help.
Personally I don't mind for now keep three product separated, as I've said they are "different product" with different features, they share a core lib but with different "supported features", for instance we could fix a collector without touch core lib in that case we bump only collector version.

> And FYI, when you want to translate a version number back into a commit, you'll need to specify the path to the project whose version you're starting from:

Oh ok thank's
