### ISSUE TITLE
memory allocation issue in 1.1.0

### ISSUE THREAD

**Issue by OneCyrus** [tonerdo/coverlet#45]
with the new 1.1.0 version i've a memory allocation issue. i tried it with one of my smaller projects. it generates almost a 10 GB hits-file. and it looks like it would need at least that much memory. currently the system runs out of memory and the dotnet process is stuck while trying to allocate more memory.

**Comment by OneCyrus** [comment]
unfortunately it's closed source. yes, it may be due to a lot of looped data processing. 1.0.2 works on this project (though misses some lines as mentioned in other issues). does the hits-file track each hit or only the first time?

**Comment by OneCyrus** [comment]
i guess replacing ReadAllLines with ReadLines in InstrumentationHelper should fix this.

https://medium.com/@nuno.caneco/c-file-readlines-vs-file-readalllines-4742d738064e

**Comment by OneCyrus** [comment]
thanks for merging! Will the new release be out soon? We would like to use it in prod.

**Comment by tonerdo** [comment]
I'm hoping to get a few more fixes in before I do a new release. I'm thinking this Friday, how urgent is your use?

**Comment by OneCyrus** [comment]
I was just interested to see if this really fixes our problem in prod. no problem, I'll try whenever you're ready with a new release.

**Comment by tonerdo** [comment]
@OneCyrus new release https://www.nuget.org/packages/coverlet.msbuild/1.2.0
