### ISSUE TITLE
Wrong percentages within ReportGenerator

### ISSUE THREAD

**Issue by boldt** [tonerdo/coverlet#463]
# Setup

* nUnit (3.12.0)
* coverlet.msbuild (2.6.2)
* ReportGenerator (4.1.8)

## My toolchain

```bash
dotnet clean
dotnet build
dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura\"
packages\ReportGenerator.4.1.10\tools\net47\ReportGenerator.exe "-reporttypes:Html;HtmlChart" "-reports:Test\coverage.cobertura.xml" "-targetdir:report/" "-filters:-AddInPlayground*"
```

# Issue

In ReportGenerator I see 966600% instead of 96%:

![grafik](https://user-images.githubusercontent.com/750793/59027791-3d656480-885a-11e9-96e3-663553bbd94e.png)

This is how it looks in the `coverage.cobertura.xml`:

```xml
<method name="VariableChanged" signature="()" line-rate="1" branch-rate="0,9666">
```
## Related bug report

I already created a bug report at ReportGenerator: https://github.com/danielpalme/ReportGenerator/issues/252

They say:

> The problem is, that I would expect `0.9666`. The `,` makes the difference.
> 
> There are several tools that generate _Cobertura_ files. _coverlet_ is the only one that uses `,`.

# Solution

Report the rate in dot-format instead of comma-format.

**Comment by MarcoRossignoli** [comment]
Thank's for reporting

**Comment by boldt** [comment]
Thanks for the very quick fixing. Please let me know, when it's released officially.

**Comment by MarcoRossignoli** [comment]
@boldt after merge you can use nightly build with fix, at the moment I don't know if we plan to release official so quick cc: @tonerdo
