### ISSUE TITLE
No coverage available on dotnetcore sdk3.0 preview 6

### ISSUE THREAD

**Issue by tai-yi** [tonerdo/coverlet#468]
Version info:
coverlet.msbuild : 2.6.2
DotNetCore Sdk : 3.0.100-preview6-012264

**Comment by MarcoRossignoli** [comment]
Dup https://github.com/tonerdo/coverlet/issues/456#issuecomment-500184354

**Comment by MarcoRossignoli** [comment]
Sorry maybe misread, can you provide more info?
What does "no coverage available"?
If you are talking about collector it doesn't available yet on preview...msbuild and tool should work.

**Comment by tai-yi** [comment]
Console output coverage 0 after run command 'dotnet test', but dotnetcore3.0 preview 5 works fine.

**Comment by MarcoRossignoli** [comment]
Can you create a simple repro?It's hard to understand if the issue is related to something inside preview 6 or inside coverlet.
Something like https://github.com/Harvzor/coverlet-enum-test

**Comment by tai-yi** [comment]
Sorry for mistake, set with wrong `Exclude` property.
Thanks for your support.

**Comment by MarcoRossignoli** [comment]
No worries!
