### ISSUE TITLE
Cobertura Report Specifies UTF-16 encoding, when it is saved as UTF-8

### ISSUE THREAD

**Issue by begoldsm** [tonerdo/coverlet#47]
This is a minor issue, but it causes other programs that read the xml file to fail with the following error:
`There is no Unicode byte order mark. Cannot switch to Unicode`, since it expects the file to actually be UTF-16, even though it is saved as UTF-8. My recommendation is to change the header declaration to either remove the encoding piece, or specify UTF-8

**Comment by tariknz** [comment]
Getting the same issue on VSTS
```
Failed to read D:\a\1\s\Mop.Stores.UnitTests\coverage.xml. Error : There is no Unicode byte order mark. Cannot switch to Unicode..
No coverage data found. Check the build errors/warnings for more details.
```

**Comment by tariknz** [comment]
Looks like there is already a `Utf8StringWriter` which writes the XML as UTF-8 (being used for the OpenCoverReporter). I can create a PR if you guys are accepting.

**Comment by tonerdo** [comment]
@tariknz no need. I already created a fix in a separate branch, removed the need for `Utf8StringWriter` altogether

**Comment by tariknz** [comment]
Awesome, appreciate the work!

**Comment by tonerdo** [comment]
New NuGet bits: https://www.nuget.org/packages/coverlet.msbuild/1.1.1
