### ISSUE TITLE
Code coverage breaks strong-name signature, causing test failure on .NET Framework

### ISSUE THREAD

**Issue by AArnott** [tonerdo/coverlet#471]
When my repo strong-name signs its assemblies and I execute a test run with code coverage on .NET Framework, `dotnet test` ultimately fails because when it shadow-copies the assembly, the strong-name signature is checked and found to be invalid. 
I wonder if this is because the code coverage changes the IL in the assembly, thus invalidating its signature.

Is this a known issue? If not, I can provide repro steps if necessary.

**Comment by MarcoRossignoli** [comment]
Is a dup of https://github.com/tonerdo/coverlet/issues/347?

**Comment by AArnott** [comment]
Yes. Thanks.
