### ISSUE TITLE
How could one use coverlet when running from a console application

### ISSUE THREAD

**Issue by Lutando** [tonerdo/coverlet#483]
Is it possible to run coverlet from a console test app like illustrated [here](https://github.com/xunit/samples.xunit/blob/master/TestRunner/Program.cs) and if so could I be pointed in the right direction on where to look?

We have some custom tests that are written in a similar fashion to the above example for various reasons. 

Any help appreciated :)

**Comment by MarcoRossignoli** [comment]
dup of https://github.com/tonerdo/coverlet/issues/212

At the moment we don't offer "official supported package" to use coverlet engine, you can find reasons on thread.

**Comment by Lutando** [comment]
If anybody passes by

If all you want to do is see how running assembly `Foo` covers Assembly `Bar`. A does not have to be a test assembly, as in, it does not have to be a test runner application, it can be any runnable .net application. If `Foo` is a console app you can do:

`coverlet /path/to/Foo.dll --target "dotnet" --targetargs "run /path/to/Bar --no-build"`
where `Foo` is a standard console app an `Bar` is potentially a library of `sorts`

This to me seems cleaner than consuming the forked package that came from https://github.com/tonerdo/coverlet/issues/212
