### ISSUE TITLE
netcoreapp1.1 support?

### ISSUE THREAD

**Issue by ambujs** [tonerdo/coverlet#484]
Hello, just wondering if I should be able to use this package on a netcoreapp1.1 project? 
I'm trying to run:
 `dotnet test  ./dh.SR.WebApi.www.Test/dh.SR.WebApi.www.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover`

but getting this error:
` Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified..`

Any ideas or help would be much appreciated!
Thanks

**Comment by MarcoRossignoli** [comment]
dup of https://github.com/tonerdo/coverlet/issues/466 at the moment we support `netstandard2.0`
to support `netcoreapp1.1` we need to do some updates and downgrade to `netstandardard1.3`

**Comment by MarcoRossignoli** [comment]
Feel free to reopen or move on discussion on other thread.
