### ISSUE TITLE
invalid Exclude parameter

### ISSUE THREAD

**Issue by stumpyfr** [tonerdo/coverlet#486]
Hi,

trying to add more filter to the Exclude option but soon as I am trying to add a second one, separated by comma as indicated in the doc, I got this error:

```
dotnet test /p:CollectCoverage=true /p:CoverletOutput=Coverage\  --no-build /p:Exclude="[xunit.*]*,[*]DAL.ModelsV2.*"
MSBUILD : error MSB1006: Property is not valid.
Switch: [*]DAL.ModelsV2.*

For switch syntax, type "MSBuild /help"
```

corverlet version: 2.6.3

**Comment by stumpyfr** [comment]
ok...msbuild doesn't handle well `,`, we are in 2019 :).
If you encode it `%2c`, it's working well:
```
dotnet test /p:CollectCoverage=true /p:CoverletOutput=Coverage\  --no-build /p:Exclude="[xunit.*]*%2c[*]DAL.ModelsV2.*"
```

Thanks to https://github.com/Microsoft/msbuild/issues/471

**Comment by MarcoRossignoli** [comment]
FYI https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#note-for-powershell--vsts-users

**Comment by stumpyfr** [comment]
And now feeling stupid :).
Thanks!

**Comment by MarcoRossignoli** [comment]
Actually it's not so clear on guide, it's under `Note for Powershell / VSTS users` maybe we should make it clearer.

**Comment by stumpyfr** [comment]
Cannot confirm right now but I think I try and got the same error on CMD too, so not only Powershell but "Windows"
