### ISSUE TITLE
use coverlet with binary based tests using dotnet vstest 

### ISSUE THREAD

**Issue by TFTomSun** [tonerdo/coverlet#489]
is there a possibility to use coverlet with dotnet vstest (not to confuse with dotnet test)?
dotnet vstest takes test assemblies as parameters.

btw. i tried to add the switch --collector:"XPlat Code Coverage" but i got the message that the collector couldn't be found. How do i need to publish my test assembly to make it available?

**Comment by tonerdo** [comment]
@TFTomSun what version of the .NET CLI are you using?

**Comment by TFTomSun** [comment]
@tonerdo 3.0 preview-6
I found another way, I used the coverlet global tool instead in conjuction with dotnet vstest. Works fine.

**Comment by MarcoRossignoli** [comment]
I think could be related to https://github.com/tonerdo/coverlet/issues/456#issuecomment-500184354

**Comment by MarcoRossignoli** [comment]
You can follow the guide https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md rember to publish the project before.
