### ISSUE TITLE
Cobertura: Some issues with the formatting that cause jenkins issues

### ISSUE THREAD

**Issue by begoldsm** [tonerdo/coverlet#49]
First of all **HUGE** thank you for doing the heavy lifting for Cobertura directly in coverlet. This is a huge time saver and reduces the complexity of report conversion for Jenkins pipeline reporting. Now for the fun part :). As part of investigating usage of this format, I found the following components need to be updated/fixed in order to get the same (BETTER!) experience that we currently get with OpenCover -> Cobertura using the converter:

1. In the `package` node there is no `name` attribute, this should be the assembly name of the code being covered (without `dll`)
2. The filename section does not include the full path to the files being covered, which can break linkage in Jenkins (this could also be a jenkins specific problem, but wanted to call it out).
3. `Coverage` node is missing the following info: 
  - `lines-valid`
  - `lines-covered`
  - `branches-covered`
  - `branches-valid`
  - `complexity`
4. In line coverage, when it is a branch hit the `line` node does not include the attribute: `condition-coverage`
5. There is a discrepancy between how you are defining signature and how it gets converted, and I am not sure which is right: the converter reports a method like this: 
  - `<method name=".ctor" signature="(OpenQA.Selenium.IWebDriver)" line-rate="1" branch-rate="1">` 
vs. the built-in here in coverlet reports it like this:
`<method name=".ctor" signature="System.Void UI.Framework.Pages.BasePage::.ctor(OpenQA.Selenium.IWebDriver,System.Boolean)" line-rate="1" branch-rate="1">`

That is all I have found, and again, huge thank you for all of this hard work! With these issues addressed we can finally switch off OpenCover -> Cobertura conversion!

Final note/information: I am using your latest coverlet package (1.1.0) and the latest `OpenCoverToCoberturaConverter` package (0.3.1). I then compared the cobertura xml from the converter to using cobertura directly in `coverlet` to get the info above.

**Comment by tonerdo** [comment]
Hi @begoldsm thanks for pointing this out. I've actually already fixed it in a separate branch and will create a new NuGet release later tonight

**Comment by tonerdo** [comment]
New NuGet bits: https://www.nuget.org/packages/coverlet.msbuild/1.1.1
