### ISSUE TITLE
Output multiple formats when executed via vstest (coverletArgs.runsettings)

### ISSUE THREAD

**Issue by molszews** [tonerdo/coverlet#490]
Hey, is there a way to output multiple attachments with coverage results in different formats when VSTest integration is used? 
Settings parser right now takes the first format defined from .runsettings file: https://github.com/tonerdo/coverlet/blob/66a01198679f8d2c0e79d1fe1955d1e5553abecc/src/coverlet.collector/DataCollection/CoverletSettingsParser.cs#L88

**Comment by MarcoRossignoli** [comment]
cc: @vagisha-nidhi

**Comment by vagisha-nidhi** [comment]
We need to look at if we can get multiple attachments from datacollectors to test platform.
cc: @cltshivash @PBoraMSFT

**Comment by vagisha-nidhi** [comment]
@MarcoRossignoli Multiple attachments support is present in datacollectors. 
We just need to get the logic of creating reports out of Coverage Manager and do something like this [https://github.com/tonerdo/coverlet/blob/09f91f2afa623dbd011acac8a10f6023d9513812/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L99](https://github.com/tonerdo/coverlet/blob/09f91f2afa623dbd011acac8a10f6023d9513812/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L99) for each report format and send them all to test platform.
