### ISSUE TITLE
Coverlet cli on Alpine Linux not working

### ISSUE THREAD

**Issue by TFTomSun** [tonerdo/coverlet#494]
I get the following output on alpine linux:

> Tool 'coverlet.console' (version '1.5.3') was successfully installed.
>   Tool 'coverlet.console' was reinstalled with the latest stable version (version '1.5.3').
>   Microsoft (R) Test Execution Command Line Tool Version 16.1.1
>   Copyright (c) Microsoft Corporation.  All rights reserved.
>   Starting test execution, please wait...
>   Results File: /builds/collaboration/net/demo/template/calculator.api/_out/test/_out/TestResults/Calculator.Api.Tests_Results.trx
>   Test Run Successful.
>   Total tests: 1
>        Passed: 1
>    Total time: 1.3404 Seconds
>   
>   Calculating coverage result...
>     Generating report '/builds/collaboration/net/demo/template/calculator.api/_out/test/_out/TestResults/Calculator.Api.Tests_coverage.json'
>   +-------------+------+--------+--------+
>   | Module      | Line | Branch | Method |
>   +-------------+------+--------+--------+
>   | PackageTest | 0%   | 100%   | 0%     |
>   +-------------+------+--------+--------+
>   
>   +---------+------+--------+--------+
>   |         | Line | Branch | Method |
>   +---------+------+--------+--------+
>   | Total   | 0%   | 100%   | 0%     |
>   +---------+------+--------+--------+
>   | Average | 0%   | 100%   | 0%     |
>   +---------+------+--------+--------+
>   

> Build succeeded.

For the same project on windows i get the following output

> Tool 'coverlet.console' was reinstalled with the latest stable version (version '1.5.3').
>   Microsoft (R) Test Execution Command Line Tool Version 16.0.1
>   Copyright (c) Microsoft Corporation.  All rights reserved.
>   Starting test execution, please wait...
>   Results File: D:\Git\Demo\Template\calculator.api\_out\test\_out\TestResults\Calculator.Api.Tests_Results_2019-07-22_16-31-10-489.trx
>   Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
>   Test Run Successful.
>   Test execution time: 1,0672 Seconds
>   
>   Calculating coverage result...
>     Generating report 'D:\Git\Demo\Template\calculator.api\_out\test\_out\TestResults\Calculator.Api.Tests_coverage.json'
>   +----------------+------+--------+--------+
>   | Module         | Line | Branch | Method |
>   +----------------+------+--------+--------+
>   | Calculator.Api | 80%  | 50%    | 100%   |
>   +----------------+------+--------+--------+
>   | PackageTest    | 0%   | 100%   | 0%     |
>   +----------------+------+--------+--------+
>   
>   +---------+--------+--------+--------+
>   |         | Line   | Branch | Method |
>   +---------+--------+--------+--------+
>   | Total   | 66,66% | 50%    | 50%    |
>   +---------+--------+--------+--------+
>   | Average | 33,33% | 25%    | 25%    |
>   +---------+--------+--------+--------+

I can see no issues, but coverlet seems not to collect coverage data on the alpine linux. Is there a possibility to get more log information?

**Comment by MarcoRossignoli** [comment]
Have you tried with https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md?

**Comment by TFTomSun** [comment]
I got the following output:

> You can invoke the tool using the following command: coverlet
>   Tool 'coverlet.console' (version '1.5.3') was successfully installed.
>   Tool 'coverlet.console' was reinstalled with the latest stable version (version '1.5.3').
>   Excluded module filter '[xunit*]*'
>   Instrumented module: '/builds/collaboration/net/demo/template/calculator.api/_out/bin/PackageTest/netcoreapp2.2/publish/PackageTest.dll'
>   Microsoft (R) Test Execution Command Line Tool Version 16.1.1
>   Copyright (c) Microsoft Corporation.  All rights reserved.
>   Starting test execution, please wait...
> 
>   Results File: /builds/collaboration/net/demo/template/calculator.api/_out/TestResults/Calculator.Api.Tests_Results.trx
>   Test Run Successful.
>   Total tests: 4
>        Passed: 4
>    Total time: 5.3861 Seconds
>   
>   Calculating coverage result...
>   Hits file:'/tmp/PackageTest_77c65c61-0228-48db-991a-d329bcd8fcc8' not found for module: 'PackageTest'
>     Generating report '/builds/collaboration/net/demo/template/calculator.api/_out/TestResults/Calculator.Api.Tests_coverage.json'
>   +-------------+------+--------+--------+
>   | Module      | Line | Branch | Method |
>   +-------------+------+--------+--------+
>   | PackageTest | 0%   | 100%   | 0%     |
>   +-------------+------+--------+--------+
>   
>   +---------+------+--------+--------+
>   |         | Line | Branch | Method |
>   +---------+------+--------+--------+
>   | Total   | 0%   | 100%   | 0%     |
>   +---------+------+--------+--------+
>   | Average | 0%   | 100%   | 0%     |
>   +---------+------+--------+--------+
>   
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)

I wonder why my API and Test assembly are not instrumented. And what does Excluded module filter '[xunit*]*' mean ?

**Comment by TFTomSun** [comment]
Maybe the reason is that I restore the test using another project. To make the test run i have to copy the some json files

```xml
    <Copy Condition="$(TargetFramework.StartsWith('netcoreapp'))" ContinueOnError="true" SourceFiles="$(PublishDir)$(MSBuildProjectName).runtimeconfig.json" DestinationFiles="$(PublishDir)testhost.runtimeconfig.json"></Copy>
    <Copy Condition="$(TargetFramework.StartsWith('netcoreapp'))" ContinueOnError="true" SourceFiles="$(PublishDir)$(MSBuildProjectName).deps.json" DestinationFiles="$(PublishDir)testhost.deps.json"></Copy>


```

**Comment by TFTomSun** [comment]
The output with detailed verbosity on windows:

> 
>  Tool 'coverlet.console' is already installed.
> C:\Users\adfrth5\.nuget\packages\crosscutting.build\1.0.1563954173\build\targets\NugetPackageTest.targets(55,5): warning MSB3073: Der Befehl "dotnet tool install -g coverlet.console" wurde mit dem Code 1 beendet. [D:\Git\Demo\Template\calculator.api\_out\test\PackageTest.csproj]
>   Tool 'coverlet.console' was reinstalled with the latest stable version (version '1.5.3').
>   Excluded module filter '[xunit*]*'
>   Instrumented module: 'D:\Git\Demo\Template\calculator.api\_out\test\_out\bin\PackageTest\netcoreapp2.2\publish\Calculator.Api.dll'
>   Instrumented module: 'D:\Git\Demo\Template\calculator.api\_out\test\_out\bin\PackageTest\netcoreapp2.2\publish\Common.Test.dll'
>   Instrumented module: 'D:\Git\Demo\Template\calculator.api\_out\test\_out\bin\PackageTest\netcoreapp2.2\publish\PackageTest.dll'
>   Microsoft (R) Test Execution Command Line Tool Version 16.0.1
>   Copyright (c) Microsoft Corporation.  All rights reserved.
>   Starting test execution, please wait...

>   Results File: D:\Git\Demo\Template\calculator.api\_out\test\_out\TestResults\Calculator.Api.Tests_Results_2019-07-24_10-25-26-469.trx
>   Total tests: 4. Passed: 4. Failed: 0. Skipped: 0.
>   Test Run Successful.
>   Test execution time: 5,3049 Seconds
>   
>   Calculating coverage result...
>   Hits file:'C:\Users\adfrth5\AppData\Local\Temp\Calculator.Api_98067c5f-d88f-45ac-9ba8-ef80427e45fb' not found for module: 'Calculator.Api'
>   Hits file:'C:\Users\adfrth5\AppData\Local\Temp\PackageTest_98067c5f-d88f-45ac-9ba8-ef80427e45fb' not found for module: 'PackageTest'
>     Generating report 'D:\Git\Demo\Template\calculator.api\_out\test\_out\TestResults\Calculator.Api.Tests_coverage.json'
>   +----------------+--------+--------+--------+
>   | Module         | Line   | Branch | Method |
>   +----------------+--------+--------+--------+
>   | Calculator.Api | 0%     | 0%     | 0%     |
>   +----------------+--------+--------+--------+
>   | Common.Test    | 35,13% | 14,28% | 66,66% |
>   +----------------+--------+--------+--------+
>   | PackageTest    | 0%     | 100%   | 0%     |
>   +----------------+--------+--------+--------+
>   
>   +---------+-------------------+-------------------+-------------------+
>   |         | Line              | Branch            | Method            |
>   +---------+-------------------+-------------------+-------------------+
>   | Total   | 30,23%            | 12,5%             | 40%               |
>   +---------+-------------------+-------------------+-------------------+
>   | Average | 10,0766666666667% | 4,16666666666667% | 13,3333333333333% |
>   +---------+-------------------+-------------------+-------------------+
>   
> 
> Der Buildvorgang wurde erfolgreich ausgefhrt.

**Comment by MarcoRossignoli** [comment]
I noticed a small difference in paths

```
/builds/collaboration/net/demo/template/calculator.api/_out/TestResults/Calculator.Api.Tests_Results.trx Alpine
D:\Git\Demo\Template\calculator.api_out\test_out\TestResults\Calculator.Api.Tests_Results_2019-07-24_10-25-26-469.trx Win
```

That `/calculator.api/_out/` vs `calculator.api_out\test_out\` could be related?

**Comment by MarcoRossignoli** [comment]
@TFTomSun any news?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to re-open if needed.
