### ISSUE TITLE
With VB WinForms on CoreFX and XUnit I don't get a summary

### ISSUE THREAD

**Issue by paul1956** [tonerdo/coverlet#499]
dotnet test --collect:"XPlat Code Coverage"
Run from test directory

I do get results in TestExplorer directory.

**Comment by MarcoRossignoli** [comment]
> I don't get a summary

Do you mean console output?

**Comment by paul1956** [comment]
Yes I get console output just not a coverage summary
```
Starting test execution, please wait...

Attachments:
  C:\Users\PaulM\Documents\Visual Studio 2017\Projects\CSharpToVB\CSharpToVB.Tests\TestResults\07419929-e066-4257-adf1-deef36152674\coverage.json

Test Run Successful.
Total tests: 153
     Passed: 153
 Total time: 21.9898 Minutes
```

**Comment by MarcoRossignoli** [comment]
At the moment we don't print anything for collectors.
@vagisha-nidhi have you got some requests(issue) about it in your VSTest repo?

**Comment by paul1956** [comment]
@MarcoRossignoli I am not requesting it, I thought it might be rated to not getting any collection on VB applications. I will close this.
