### ISSUE TITLE
Report format support for JaCoCo

### ISSUE THREAD

**Issue by OneCyrus** [tonerdo/coverlet#5]
it works quite well so far! we are using it already in VSTS/TFS. but one thing which is not so streamlined for using in VSTS/TFS are the supported output formats. Currently VSTS/TFS only supports Cobertura and JaCoCo. Supporting one of this formats would be great.

**Comment by tonerdo** [comment]
@OneCyrus multiple coverage formats is definitely and improvement. Do you happen to have links where these formats are documented?

**Comment by OneCyrus** [comment]
it looks like there is no proper Cobertura specification.

but may be this links help:
https://leonard.io/blog/2011/06/cobertura-sample-xml-output/
https://github.com/danielpalme/OpenCoverToCoberturaConverter

**Comment by tonerdo** [comment]
Alright, will take a look. Thanks!

**Comment by tonerdo** [comment]
Thanks, how about JaCoCo?

**Comment by OneCyrus** [comment]
Microsoft has links to the schema definition files for both here: https://docs.microsoft.com/en-us/vsts/build-release/tasks/test/publish-code-coverage-results?view=vsts

http://cobertura.sourceforge.net/xml/coverage-04.dtd
http://www.eclemma.org/jacoco/trunk/coverage/report.dtd

**Comment by timker** [comment]
FYI in the interim for linux builds I added
```
 dotnet Tools/OpenCoverToCoberturaConverter/OpenCoverToCoberturaConverter.dll  "-input:opencover.xml" "-output:Cobertura.xml"
```
from https://github.com/danielpalme/OpenCoverToCoberturaConverter

this worked for VSTS

**Comment by tonerdo** [comment]
Cobertura support available in latest NuGet bits https://www.nuget.org/packages/coverlet.msbuild/1.1.0

**Comment by ahaleiii** [comment]
I am using VSTS with Cobertura format and getting results, but I can only report on lines right now. Any plans to update Cobertura to report blocks? Thanks for all your work on this!

**Comment by MarcoRossignoli** [comment]
Cobertura was added.
