### ISSUE TITLE
Question Is there a defination of the BranchInfo Fields

### ISSUE THREAD

**Issue by paul1956** [tonerdo/coverlet#504]
BranchInfo Offset and EndOffset are almost always 2 apart and Path and Ordinal are usually 0 and when they are not I don't know what they mean. I am trying to color code source, lines work as expected.

**Comment by SteveGilham** [comment]
Ordinal is a zero-based numbering of branches within a method
Path indicates which exit from a branch -- usually 0 or 1, but for a n-way switch should be 0 to (n-1)
Offset is the IL offset of the branch instruction within the method
EndOffset is the IL offset of the destination

**Comment by paul1956** [comment]
Thanks

**Comment by MarcoRossignoli** [comment]
thank's @SteveGilham for the answer!
