### ISSUE TITLE
Test coverage average coming as infinity

### ISSUE THREAD

**Issue by arpymastro** [tonerdo/coverlet#516]
We use coverlet with all our .NET Core projects(APIs, Libraries) and it works just fine for us. 

Recently we have created one .NET Standard library and I have added .NET Core 2.2 xUnit test project in it with 2 tests. We have added coverlet.msbuild 2.5.1 nuget package to calculate the code coverage - 

`dotnet test -c Release --logger TRX /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults`

It runs the tests, all tests are passing but the code coverage is showing as empty with average "infinity". It is not even identifying module name. Please refer attached notepad file for sample output. 

What's going wrong here?
[Sample output.txt](https://github.com/tonerdo/coverlet/files/3498055/Sample.output.txt)

**Comment by MarcoRossignoli** [comment]
Can you try with last version https://www.nuget.org/packages/coverlet.msbuild/ 2.6.3?

**Comment by MarcoRossignoli** [comment]
@arpymastro any news?

**Comment by Blaatschaap** [comment]
@MarcoRossignoli I have the same issue, using 2.6.3.

I also have the issue that my coverage xml's are basically empty.

Jenkins console output:"
+ dotnet test /var/jenkins_home/workspace/Build/XUnitTestProject1.csproj /p:CollectCoverage=true /p:CoverletOutput=/var/jenkins_home/workspace/Build/TestResults/ /p:CoverletOutputFormat=cobertura --logger trx;LogFileName=UnitTests.trx --collect:XPlat Code Coverage
Test run for /var/jenkins_home/workspace/Build/bin/Debug/netcoreapp2.2/XUnitTestProject1.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.2.0-preview-20190606-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
WARNING: Overwriting results file: /var/jenkins_home/workspace/Build/TestResults/UnitTests.trx
Results File: /var/jenkins_home/workspace/Build/TestResults/UnitTests.trx

Attachments:
  /var/jenkins_home/workspace/Build/TestResults/63d42b4b-4a28-4e66-907c-4db2016e7346/coverage.cobertura.xml

Test Run Successful.
Total tests: 4
     Passed: 4
 Total time: 4.1592 Seconds

Calculating coverage result...
  Generating report '/var/jenkins_home/workspace/Build/TestResults/coverage.cobertura.xml'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | INF% | INF%   | INF%   |
+---------+------+--------+--------+

coverage.cobertura.xml:
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1567598099" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources>
    <source></source>
  </sources>
  <packages />
</coverage>

**Comment by MarcoRossignoli** [comment]
@Blaatschaap do you get same result if you run in local or is related only to ci?

**Comment by Blaatschaap** [comment]
@MarcoRossignoli I get the same result running locally

**Comment by MarcoRossignoli** [comment]
can you attach you command?

**Comment by Blaatschaap** [comment]
dotnet test /var/jenkins_home/workspace/Build/XUnitTestProject1.csproj /p:CollectCoverage=true /p:CoverletOutput=/var/jenkins_home/workspace/Build/TestResults/ /p:CoverletOutputFormat=cobertura --logger trx;LogFileName=UnitTests.trx --collect:XPlat Code Coverage

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli I have the same issue, using 2.6.3.

Sorry but you command are using collector and above you said 2.6.3 msbuild version...are you using msbuild or collector?

**Comment by Blaatschaap** [comment]
I have both in the project (collection version 1.0.1)

**Comment by MarcoRossignoli** [comment]
mmm not sure if could lead to overlapped issue can you try with only collector like https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-integration-with-vstest

**Comment by Blaatschaap** [comment]
+ dotnet publish
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 64.06 ms for /var/jenkins_home/workspace/Build/XUnitTestProject1.csproj.
  XUnitTestProject1 -> /var/jenkins_home/workspace/Build/bin/Debug/netcoreapp2.2/XUnitTestProject1.dll
  XUnitTestProject1 -> /var/jenkins_home/workspace/Build/bin/Debug/netcoreapp2.2/publish/
[Pipeline] sh
+ dotnet vstest /var/jenkins_home/workspace/Build/bin/Debug/netcoreapp2.2/XUnitTestProject1.dll --collect:XPlat Code Coverage
Microsoft (R) Test Execution Command Line Tool Version 16.2.0-preview-20190606-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Attachments:
  /var/jenkins_home/workspace/Build/TestResults/5b3f23bb-07de-4a1a-8468-f1ef96fa923b/coverage.cobertura.xml

Test Run Successful.
Total tests: 4
     Passed: 4
 Total time: 4.3694 Seconds

**Comment by MarcoRossignoli** [comment]
Collector doesn't print anything in console...is it the file empty?

**Comment by Blaatschaap** [comment]
the file is empty yes, and indeed, the table stopped showing in console

**Comment by MarcoRossignoli** [comment]
Can you try with msbuild(the core instrumentation is the same but logs are more verbose) https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration?
Before ask for a "repro" code we could try to undestand with logs what is instrumented.

**Comment by Blaatschaap** [comment]
+ dotnet test /var/jenkins_home/workspace/Build/XUnitTestProject1.csproj -c debug /p:CollectCoverage=true /p:CoverletOutput=/var/jenkins_home/workspace/Build/TestResults/ /p:CoverletOutputFormat=cobertura -verbosity:diagnostic -bl:msbuild.binlog -noconsolelogger --logger trx;LogFileName=UnitTests.trx
/usr/share/dotnet/sdk/2.2.401/MSBuild.dll -noconsolelogger -nologo -bl:msbuild.binlog -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/2.2.401/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/2.2.401/dotnet.dll -maxcpucount -nodereuse:false -property:Configuration=debug -property:VSTestLogger=trx%3bLogFileName=UnitTests.trx /p:CollectCoverage=true /p:CoverletOutput=/var/jenkins_home/workspace/Build/TestResults/ /p:CoverletOutputFormat=cobertura -restore -target:VSTest -verbosity:m -verbosity:quiet -verbosity:diagnostic /var/jenkins_home/workspace/Build/XUnitTestProject1.csproj

Test run for /var/jenkins_home/workspace/Build/bin/debug/netcoreapp2.2/XUnitTestProject1.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.2.0-preview-20190606-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

WARNING: Overwriting results file: /var/jenkins_home/workspace/Build/TestResults/UnitTests.trx
Results File: /var/jenkins_home/workspace/Build/TestResults/UnitTests.trx

Test Run Successful.
Total tests: 4
     Passed: 4
 Total time: 5.2135 Seconds

Calculating coverage result...
  Generating report '/var/jenkins_home/workspace/Build/TestResults/coverage.cobertura.xml'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | INF% | INF%   | INF%   |
+---------+------+--------+--------+

**Comment by Blaatschaap** [comment]
I could create a git repo for the current code, but it's a very simple factorial test project

**Comment by MarcoRossignoli** [comment]
if you can zip and attach project...ah and tell me `dotnet --info`

**Comment by Blaatschaap** [comment]
[XUnitTestProject1.zip](https://github.com/tonerdo/coverlet/files/3574627/XUnitTestProject1.zip)

.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  1.1.7 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by MarcoRossignoli** [comment]
Ah now it's clear...you have test and code in test project that is excluded by default...you have to use a switch like:
`dotnet test /p:CollectCoverage=true /p:IncludeTestAssembly=true`

**Comment by Blaatschaap** [comment]
wow, okay. That fixed it. Can't believe it is caused by using a project too simple though

**Comment by MarcoRossignoli** [comment]
> Can't believe it is caused by using a project too simple though

It's been a long debate with a lot of discussion if include or not test project by default...https://github.com/tonerdo/coverlet/pull/376 https://github.com/tonerdo/coverlet/pull/318#issuecomment-457223596

**Comment by MarcoRossignoli** [comment]
Close because solved...feel free to re-open if needed

**Comment by SruthiSyamala-Wellsky** [comment]
Hi 
I am getting same result after I included "/p:IncludeTestAssembly=true"  ---- .xml file is empty. 
![tempsnip](https://user-images.githubusercontent.com/66686521/86951911-cca51180-c117-11ea-8ef0-ed54aacc8eff.png)


This is what I'm running:   dotnet test ./Tests/**--filter "**" /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=cobertura --logger trx

 I am getting correct result when I'm running in local also it is generating correct .xml file.

**Comment by SruthiSyamala-Wellsky** [comment]
> Close because solved...feel free to re-open if needed

I opened this ticket. Can you see my post?
