### ISSUE TITLE
Using Coverlet for acceptance test coverage

### ISSUE THREAD

**Issue by mgw854** [tonerdo/coverlet#52]
First, not to be too patronizing, but I've loved the experience I've had with Coverlet so far while unit testing. I've introduced it into a number of projects I've worked on, and it's helping me to identify pathways that really ought to have unit tests.

That being said, there are sometimes pathways that I can't unit test. I'd like to be able to measure whether or not a suite of acceptance tests covers those pathways. After poking around a bit, I figured it would be feasible:

- In the executable hosting the acceptance tests (which references a second project), add a reference to coverlet.msbuild and additional build targets to run the compiled .dll, and then generate the coverage result from that run.

```
  <Target Name="CodeCov" AfterTargets="InstrumentModulesAfterBuild">
    <Exec Command="dotnet quot;$(MSBuildThisFileDirectory)$(OutputPath)AcceptanceTests.dll&quot; --diagnostics" />
  </Target>
  <Target Name="GenerateCoverageResult" AfterTargets="CodeCov">
    <Coverlet.MSbuild.Tasks.CoverageResultTask Condition="$(CollectCoverage) == 'true'" Output="$(CoverletOutput)" OutputFormat="$(CoverletOutputFormat)" />
  </Target>
```

- Run `dotnet msbuild .\AcceptanceTests.csproj /t:CodeCov /p:CollectCoverage=true /p:CoverletOutputFormat=opencover`

That much generates the instrumentation (verified in dotPeek) and begin the application. After the first line of code is executed, however, I get this error:

```
  Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'coverlet.core, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

I've tried adding references to the projects, adding additional probing paths, and setting binding redirects, to no avail. Is there a way to support this functionality, or perhaps a better question, is this something that Coverlet should allow at all?

**Comment by tonerdo** [comment]
Hiya @mgw854, verify that the `coverlet.core` binary is present in the same directory as the instrumented dll
