### ISSUE TITLE
Read out single and summary coverage(without Regex)

### ISSUE THREAD

**Issue by Nusserdt** [tonerdo/coverlet#520]
I have the issue that I need to read out the coverage results from coverlet. Is it possible to get the values of single and summary coverage of the results in a practical way (without using string or regex operations)?

**Example:**
![image](https://user-images.githubusercontent.com/35678990/63079269-39cb1980-bf3e-11e9-89fd-efaf1228be20.png)

```
Write-Host hashtable["Project.UnitTest.dll"]
>> "41.89", "74.54", "70.87"

Write-Host hashtable["Total"]
>> "41.89", "74.54", "70.87"

Write-Host hashtable["Average"]
>> "41.89", "74.54", "70.87"
```

**Comment by MarcoRossignoli** [comment]
dup https://github.com/tonerdo/coverlet/issues/148 https://github.com/tonerdo/coverlet/issues/284

At the moment we don't have a way to extract that values.

**Comment by MarcoRossignoli** [comment]
Question...why do you need to extract that values?

**Comment by Nusserdt** [comment]
@MarcoRossignoli Thanks a lot for your response. We want to extract the values to generate a historical view for the code coverage over all commits. Coverlet should run inside a buildpipeline on a Azure DevOps Server and should make a warning when the coverage get lower the the historical results registrated before. There fore I need to extract for example the single coverage of a Test-Assembly and compare this particular Assembly over time with future commits. As a service for the developer team I want to point on these particular test assembly when something change in to the "negative" way. Repeat this procedure to >100 Test Assemblies.

**Comment by Nusserdt** [comment]
@MarcoRossignoli found a solution thats works for me. I found out that all these information can easily extract from the report. Thanks for all.

**Comment by MarcoRossignoli** [comment]
Great!
