### ISSUE TITLE
Coverlet does not generate code coverage

### ISSUE THREAD

**Issue by CodesharpJonas** [tonerdo/coverlet#523]
### Main Error

After running tests coverlet generates empty cobertura xml file on my build agent

### Agent
Azure Devops - Hosted Agent

### Issue Description

I'm following a SO post to generate a cobertura code coverage report on a .Net Full Framework 4.7.1.

https://stackoverflow.com/questions/54627918/view-code-coverage-report-on-azure-devops-portal/54738732#54738732

I'm using coverlet to run 'dotnet vstest' and then generate a coverage.cobertura.xml file.
This is working on my local machine but when running on the build agent the coverage xml file is just empty of results.

**My yaml build step**
```
- powershell: |
        "install tools:"
        &dotnet tool install coverlet.console --tool-path . --version 1.5.3

        "`nrun tests:"
        $unitTestFile = gci -Recurse | ?{ $_.FullName -like "*bin\*test.dll" }
        Write-Host "`$unitTestFile value: $unitTestFile"

        $coverlet = "$pwd\coverlet.exe"

        "calling $coverlet for $($unitTestFile.FullName)"
        &$coverlet $unitTestFile.FullName --target "dotnet" --targetargs "vstest $($unitTestFile.FullName) --logger:trx" --format "cobertura"
```

**Log output:**
```
calling C:\__w\9\s\coverlet.exe for C:\__w\9\s\Source\Server.Net\ActivityCalendarSvc\ActivityCalendar.Test\bin\Release\ActivityCalendar.Test.dll 
Microsoft (R) Test Execution Command Line Tool Version 16.2.0-preview-20190606-02
Copyright (c) Microsoft Corporation.  All rights reserved.
  
Starting test execution, please wait... 
! TestRecurringEntryTestData [895ms]  
! TestDetailsMissing [5ms] 
! TestSplitEvents [4ms]
Results File: C:\__w\9\s\TestResults\ContainerAdministrator_E1968FE75CB5_2019-08-19_10_52_23.trx   
   
 Test Run Successful. 
 Total tests: 19 
 Passed: 16 
 Skipped: 3 
 Total time: 2.4672 Seconds 

 Calculating coverage result... 
 Generating report 'C:\__w\9\s\coverage.cobertura.xml' 

  | +--------+--------+--------+--------+ |  
  | Module \| Line   \| Branch \| Method |  
  | +--------+--------+--------+--------+ |  

  | +---------+--------+--------+--------+ |  
  |        \| Line   \| Branch \| Method  |  
  | +---------+--------+--------+--------+ |  
  | Total   \| 100%   \| 100%   \| 100%    |  
  | +---------+--------+--------+--------+ |  
  |  Average \| ∞%     \| ∞%     \| ∞%     |  
  | +---------+--------+--------+--------+

```

Since it does run the tests correctly, and I've viewed the trx file, what could be causing it to not outputting any code coverage data?

**Comment by MarcoRossignoli** [comment]
Seem very similar to https://github.com/tonerdo/coverlet/issues/503#issuecomment-520112616 can you take a look if it works for you?

**Comment by CodesharpJonas** [comment]
It does look very similar indeed! One difference though is that I'm using 'dotnet vstest' rather than 'dotnet test', I'm not sure if that's a big difference or not?

I'm not familiar with props files, the few I can find in the source code does not include the mentioned attributes. I'm working with a new client so I'm not a 100% familiar with their setup yet so it's not impossible that it could be related and I just don't know where to look.

**Comment by MarcoRossignoli** [comment]
Can you try to add verbose logging https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#coverlet-global-tool?

**Comment by CodesharpJonas** [comment]
It seems my build server still has version 1.4.1 of coverlet, which doesn't have the verbosity option. Trying to figure out why 1.5.3 doesn't get installed. Will get back when I have that detailed output! 

Thanks for taking your time btw :)

**Comment by CodesharpJonas** [comment]
I managed to get the detailed output, but in truth it doesn't seem to show alot

```
calling C:\__w\9\s\coverlet.exe for C:\__w\9\s\Source\Server.Net\ActivityCalendarSvc\ActivityCalendar.Test\bin\Release\ActivityCalendar.Test.dll
Cross platform .NET Core code coverage tool
1.5.0.0
Excluded module filter '[xunit*]*'
Unable to instrument module: C:\__w\9\s\Source\Server.Net\ActivityCalendarSvc\ActivityCalendar.Test\bin\Release\Microsoft.Web.Infrastructure.dll because : No symbol found for file: C:\__w\9\s\Source\Server.Net\ActivityCalendarSvc\ActivityCalendar.Test\bin\Release\Microsoft.Web.Infrastructure.dll
Microsoft (R) Test Execution Command Line Tool Version 16.2.0-preview-20190606-02
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
  ! TestRecurringEntryTestData [835ms]
  ! TestDetailsMissing [5ms]
  ! TestSplitEvents [10ms]
Results File: C:\__w\9\s\TestResults\ContainerAdministrator_18E6B9466B1B_2019-08-19_14_21_32.trx
Test Run Successful.
Total tests: 19
     Passed: 16
    Skipped: 3
 Total time: 2.3322 Seconds

Calculating coverage result...
  Generating report 'C:\__w\9\s\coverage.cobertura.xml'
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | ∞%   | ∞%     | ∞%     |
+---------+------+--------+--------+
```

When I run the same command locally on my machine it outputs alot more, it starts with 

`'Instrumented module: C:\Users\jonver\source\repos\sloop\Source\Server.Net\ActivityCalendarSvc\ActivityCalendar.Test\bin\Debug\ActivityCalendar.API.dll'`

Which is the main part of the application. So for some reason it doesn't find this dll on the build agent, but logically it must be there since the tests are run?

**Comment by MarcoRossignoli** [comment]
Mmm I'm again conviced that the issue is the same of links above are you sure that `DeterministicSourcePaths` option is not enabled for some reason? https://github.com/dotnet/sourcelink/blob/71c29afff2601faba28a894f10f3315dcd40a58d/docs/README.md#deterministicsourcepaths

**Comment by MarcoRossignoli** [comment]
cc: @david-driscoll maybe could help(I never hit this issue in my projects related to ci)

**Comment by CodesharpJonas** [comment]
As I understand the DeterministicSourcePaths or ContinuousIntegrationBuild attributes would be in a props file? Is there any other way these attributes could be set? 

I'm building using a msbuild task (not dotnet command) that looks like this: 

```
    - task: MSBuild@1
      displayName: 'Build Solution Using MSBuild'
      inputs:
        solution: ${{ parameters.solution }}
        platform: 'Any CPU'
        configuration: Release
        msbuildArguments: /p:SolutionRoot="$(Build.Repository.LocalPath)";DeployTo=Main /p:DebugSymbols=false /p:DebugType=None /p:GenerateDocumentation=false /verbosity:normal /p:StopOnFirstBuildError=true /p:nowarn=1591
        logFileVerbosity: normal
      enabled: true
```

**Comment by MarcoRossignoli** [comment]
Why `/p:DebugSymbols=false`?Coverlet need pdb to instrument dll, could be related to issue?

**Comment by CodesharpJonas** [comment]
You were on to something!
When I removed/replaced all three of these parameters "/p:DebugSymbols=false /p:DebugType=None /p:GenerateDocumentation=false" woth "/p:DebugType=pdbonly /p:GenerateDocumentation=true" it worked!!

Thank you!!

Now I just need the client to approve these changes to the build... lets hope those parameters weren't there for a good reason!

**Comment by MarcoRossignoli** [comment]
Glad to hear!
I think that the idea is to build and generate artifacts for release to production(without pdb), you could combine that value with presence or not of "CollectCoverage".
Feel free to close this issue if resolved!

**Comment by CodesharpJonas** [comment]
I reverted some of my earlier changes to find exactly what or what combinations of parameters to msbuild that did the trick. It turned out it was "/p:DebugType=pdbonly" that was the solution. "/p:DebugSymbols=false" doesnt seem to have made any difference, it works with it set to false.

Once again, thanks for your help!

**Comment by MarcoRossignoli** [comment]
Well done!

**Comment by manishi2V** [comment]
According to question @CodesharpJonas is using coverlet tool. I am using same tool to get coverage and having same issue. My requirement is to use only test dll but not csproj. Is there a way to do same?
I tried to use p:DebugType but as this option is not available with coverlet.exe so I am not able to use it.

**Comment by MarcoRossignoli** [comment]
> I tried to use p:DebugType but as this option is not available with coverlet.exe so I am not able to use it.

This option is not related to coverlet .net tool but it's a setting during project build. It's a msbuild parameter https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019
