### ISSUE TITLE
lcov format seems to be broken

### ISSUE THREAD

**Issue by Razzeee** [tonerdo/coverlet#53]
If you check out a generated report for `lcov` you will see stuff like this:

![image](https://user-images.githubusercontent.com/5943908/38929180-ccbc7cd0-430b-11e8-8a4a-b4fded6412e3.png)

Format should probably look more like this https://github.com/alexandrudima/vscode-lcov/blob/master/examples/fizzbuzz/coverage/lcov.info

**Comment by tonerdo** [comment]
This has been fixed in the latest release: https://www.nuget.org/packages/coverlet.msbuild/1.1.1

**Comment by Razzeee** [comment]
Awesome, can confirm it working. Wasn't expecing a new release after my install yesterday :)

Thank you
