### ISSUE TITLE
multiple excludes doesn't seem to work

### ISSUE THREAD

**Issue by markwest51** [tonerdo/coverlet#530]
hi

2 things really, using .Net Core 2.1, Dev Ops and MSBuild

We have a test project that for some reason seems to be included in the code coverage report whereas other test projects seems to be fine, not sure why this.

Trying to exclude this project along with a class library one that is used to generate test data
we apply the following parameter

/p:Exclude=\"[*.TestFramework*]*,[*]XXX.XXXX.Services.Ontology.Common.Tests.*\" 

this results in none of the tests being run and also no coverage produced, if i choose one or the other statement then they get excluded correctly.

any ideas ?

**Comment by MarcoRossignoli** [comment]
Some questions... which version of coverlet are you using?
Can you try to enable logging to understand what's happening? https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md

**Comment by markwest51** [comment]
version is 2.6.3, will enable logging tomorrow once i get into work

**Comment by aleksandrshvets** [comment]
Seems to be related to [ms build issue](https://github.com/Microsoft/msbuild/issues/2999). Provided workaround works for me: /p:Exclude="[Org.Assembly1.\*]\*%2c[Org.Assembly2.\*]\*"

**Comment by MarcoRossignoli** [comment]
Thank's @aleksandrshvets for tip @markwest51 do you have news?

**Comment by markwest51** [comment]
apologies, did not get any notification.  Yes this resolves the issue, have been told by a fellow developer at work today that it does exclude multiple libraries using %2c.  Some reason the other issue of having a test project appear in coverage seems to have gone during further changes in the solution, not sure why but it looks good now

**Comment by MarcoRossignoli** [comment]
> Yes this resolves the issue,

Glad to hear, thanks @aleksandrshvets for solving!
