### ISSUE TITLE
Can't output multiple files in vstest

### ISSUE THREAD

**Issue by PaleNeutron** [tonerdo/coverlet#547]
After set 

```
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>lcov,cobertura,json</Format>
          <!-- <MergeWith>/custom/path/result.json</MergeWith> -->
          <Exclude>[coverlet.*.tests?]*,[*]Coverlet.Core*,[*]CosMate*Class1</Exclude> <!-- [Assembly-Filter]Type-Filter -->
          <!-- <Include>[coverlet.*]*,[*]Coverlet.Core*</Include> [Assembly-Filter]Type-Filter -->
          <SingleHit>false</SingleHit>
          <UseSourceLink>true</UseSourceLink>
        </Configuration>
      </DataCollector>
```
3 formats in settings file as example in docs, only the first format file will be output.

BTW, how can we specific the output file path here?

**Comment by MarcoRossignoli** [comment]
dup of https://github.com/tonerdo/coverlet/issues/490
will be present in next release https://github.com/tonerdo/coverlet/pull/533
for now you can use nightly build(not today but tomorrow I just fixed an issue and we're back by one week)  https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by MarcoRossignoli** [comment]
And you can specify output in this way https://github.com/tonerdo/coverlet/issues/500#issuecomment-521185050

**Comment by MarcoRossignoli** [comment]
Feel free to reopen if needed.
