### ISSUE TITLE
Excluding by namespace

### ISSUE THREAD

**Issue by GrimSmiler** [tonerdo/coverlet#55]
Hi!

Thanks for the awesome tool You built up!

A have a quick question about `ExcludeFromCoverage`.
In the documentation, You mention specifying classes. Is it possible to exclude by namespaces? Is there an example I can reference?

so would the following example be valid to exclude all test files from coverage?

```
dotnet test MyProject.csproj /p:CollectCoverage=true /p:ExcludeFromCoverage=MyProject.Test.*
```

**Comment by tonerdo** [comment]
At this time you can't specify namespaces or even classes via the command line. There's an ongoing discussion in #56 to help figure this out

**Comment by tonerdo** [comment]
@GrimSmiler this can be achieved with the latest NuGet bits: https://www.nuget.org/packages/coverlet.msbuild/2.0.0. You can find more information about "filter expressions" on the README page

**Comment by GrimSmiler** [comment]
Thanks!
