### ISSUE TITLE
Coverlet.Console does not seem to work

### ISSUE THREAD

**Issue by abhiphirke** [tonerdo/coverlet#551]
I am trying to use Coverlet.Console 1.5.3 which does not seem to work. With multiple simple test projects (using .Net Core 2.2.107) having different coverage stats and straightforward configuration, I am always getting:

1. empty coverage.json

2. coverage.opencover.xml as:
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession>
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>

3. And wrong coverage information as: 
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | ∞%   | ∞%     | ∞%     |
+---------+------+--------+--------+

After struggling a lot with this, I am still not able to make it to work. What possibly I am doing wrong here? Please help. Thanks you.

PS: With Coverlet.Msbuild 2.6.3, this is working well.

**Comment by MarcoRossignoli** [comment]
Why you don't use 2.6.3?

**Comment by MarcoRossignoli** [comment]
Can you attach the command line you're using?

**Comment by MarcoRossignoli** [comment]
@abhiphirke any news?
Feel free to close if solved.

**Comment by MarcoRossignoli** [comment]
Close for stale, feel free to re-open if needed.
