### ISSUE TITLE
Add extension `GetService<T>` to DependencyInjection for better readability

### ISSUE THREAD

**Issue by MarcoRossignoli** [tonerdo/coverlet#554]
Add extension to `Coverlet.Core.DependencyInjection`ot  cleanup a bit the code, something like 
```cs
    public static class DependencyInjectionExtensions
    {
        public static T GetService<T>(this IServiceProvider serviceProvider)
        {
            return (T)serviceProvider.GetService(typeof(T));
        }
    }
```
And update the callers.
NB. We could use `Microsoft.Extensions.DependencyInjection.Abstractions` but we want avoid to have too much transitive/reference.

**Comment by flerka** [comment]
@MarcoRossignoli hi! Added pull request to implement this, please check. Thank you.

**Comment by MarcoRossignoli** [comment]
Sure thank you!
