### ISSUE TITLE
We should strong name coverlet.collector.dll

### ISSUE THREAD

**Issue by MarcoRossignoli** [tonerdo/coverlet#555]
Now that we've in place injection it's easy that some internal types that lives in core have to be used(injected) in collectors code.
To do that we have 2 way, expose type or apply internals visible to attribute.
I prefer second way but to be clean/safe we should add signed assemblies.

Is there a reason to not sign coverlet.collector.dll?

cc: @vagisha-nidhi for vs test side

**Comment by tonerdo** [comment]
I believe coverlet.msbuild.tasks.dll is already strongly named

**Comment by MarcoRossignoli** [comment]
Uh you're right...

**Comment by vagisha-nidhi** [comment]
@MarcoRossignoli You can sign the dll. For the inproc collector to be picked up, we'll have to make a small change similar to https://github.com/microsoft/vstest/pull/2020/files on the vstest side.
