### ISSUE TITLE
Is it possible to specify a directory to exclude from coverage?

### ISSUE THREAD

**Issue by abe545** [tonerdo/coverlet#56]
Hi, we would love to start using coverlet to generate code coverage, but we really don't want to include code that gets automatically generated in our coverage results. Since we generate it during CI, it wouldn't be feasible for us to apply attributes to every class that we want to exclude from coverage. We do, however, have a common folder in which the code gets generated. 

Is there a flag we can pass to exclude the files in said folder from coverage?

**Comment by ryanmvt** [comment]
We're also using gRPC code generation which makes the attribute-based exclusion feature unrealistic.  A configuration or flag based solution would really help out here.

**Comment by abe545** [comment]
@tonerdo the syntax suggested in #55 looks like it could be a winner - if that were a globbing pattern (and we'd have to support multiple globs). My suggestion would be a semicolon separated list of globs (probably have to quote it)

```
/p:ExcludeFromCoverage="some/**/glob;c:\some\complex rooted path\*.glob"
```

I think it would need to support both absolute and relative paths. Thoughts?

**Comment by tonerdo** [comment]
I totally agree! My only thought is whether to limit this feature to just whole assemblies or to extend it to allow specifying namespaces/classes/methods and how that will work.

**Comment by MarcoRossignoli** [comment]
In my scenario could be very useful also to have an "include" switch(a lot of  auxiliary class i don't test). I like the idea of json config file(in addition) because we can address both. Another concern is the case with a lot of include/exclude, command line could become hard to use and i don't like the idea to organize code for coverage, again this isn't possible on existing code. My idea is to chose the code i want to test with minimum % of coverage or fail for new or existing code.

**Comment by abe545** [comment]
@tonerdo I think the easiest would be path based. This will cover the majority of the scenarios, and devs can use the attribute method to exclude methods still. I don't see a scenario where I'd want to cover *most* code generated code, but not one particular method. At the very least, I'd expect such code to be generated in its own file.

@MarcoRossignoli I think the ability to both include and exclude is valuable. I think if we help out with implementing an msbuild switch, it would be easy to include an msbuild xml file in your project (via project includes), which could define these in a file for you.

**Comment by ryanmvt** [comment]
@abe545 Path-based meaning everything inside the directory specified in the path, as well as all sub-directories?  That idea would be flexible enough to encompass generated code perfectly.  It also allows you to target large swaths of code or down to a single file at a time.

@tonerdo I don't think assembly-only based exclusions would be flexible enough.  It would potentially force the developer to create additional projects specifically to exclude portions of code from code coverage right?

Even the config I would think would end up path-based too?  What do you guys think?

**Comment by abe545** [comment]
@ryanmvt yes... except I was thinking to support globbing patterns. If you don't specify any wildcards, it would indeed exclude the directory. That way, you could even do something like `**/*test*.cs` and exclude all files with the word test in the filename.

**Comment by tonerdo** [comment]
@abe545 @ryanmvt all good ideas. Here's what my final thoughts are:

* Path based ignore with support for globbing patterns
* Keep `ExcludeFromCoverage` attribute for fine grained control over ignoring classes/methods

Is this a good setup?

**Comment by abe545** [comment]
@tonerdo sounds good to me

**Comment by abe545** [comment]
My coworker @do-namely has volunteered, if nobody else wants it.

**Comment by ryanmvt** [comment]
@tonerdo sounds good to me as well!  Thank you for the volunteer @abe545

**Comment by MarcoRossignoli** [comment]
Thank's @abe545 @ @ido-namely

**Comment by coenm** [comment]
I'm familiar with OpenCover and I've always liked the filter option it provides. Not saying Coverlet should use the same syntax and options though. 

Their filter option can include or exclude by assembly name and/or by type. I know that this topic is about excluding directories but I think the problem really boils down to have fine grained control over what to include and exclude. Personally I've never excluded something based on physical location but I've always specified what to include/exclude using assembly names and namespaces.

Again, I'm not suggesting Coverlet should use the same syntax but it might be worth to take a look.

The following is copied/based on [OpenCovers wiki page](https://github.com/opencover/opencover/wiki/Usage#understanding-filters )

Syntax : `(+|-)[Assembly-Filter]Type-Filter`
Multiple filters can be applied by seperating them with a space.

**Examples**

* `+[Open*]* -[Open.Test]*`    
    Include all classes in modules starting with Open.* but exclude all those in modules Open.Test.

* `+[Open]* -[Open]Data.*`    
    Include all classes in module Open but exclude all classes in the Data namespace.

* `+[Open]* -[Open]*Attribute`    
    Include all classes in module Open but exclude all classes ending with Attribute.

**Comment by ido-namely** [comment]
Would appreciate your comments on : https://github.com/tonerdo/coverlet/pull/64

**Comment by MarcoRossignoli** [comment]
@coenm I admit I like it...

cc: @tonerdo @abe545 @ryanmvt

**Comment by MarcoRossignoli** [comment]
> We do, however, have a common folder in which the code gets generated.
Is there a flag we can pass to exclude the files in said folder from coverage?

i think so(IMHO anyway after some  thought on @coenm post...i think we could be more close to opencovers accepted standard, coverlet plus is cross plat support).

cc @abe545

**Comment by MarcoRossignoli** [comment]
>* Classes can be partial.
What if one file is excluded by the filter and the other part of a partial class isn't?

very good point...

**Comment by tonerdo** [comment]
We can definitely have both assembly based filtering and source file based filtering, we don't necessarily have to choose. My only thought is how we want that functionality to look like from a usability standpoint.

Right now I'm thinking of introducing 2 new properties:

Excluding sources:
```
dotnet msbuild /p:CollectCoverage=true /p:ExcludeSources=*pathglob*;*pathglob*
```
@ido-namely has already made some good progress on this. Much appreciated!

Excluding assemblies:
```
dotnet msbuild /p:CollectCoverage=true /p:ExcludeAssemblies=*fileglob*;*fileglob*
```

The values for `ExcludeAssemblies` need not be file paths but just a glob pattern to filter out the assembly filename. E.g. `Open*.dll`

But at this point it feels a bit verbose and I'm currently leaning towards a single `Exclude` property that can accept an array of both source files and assemblies but is able to distinguish between the two and do the needful. E.g if the glob pattern resolves to a `.dll` then obviously treat it as an assembly and ignore calculating coverage for it, but if resolves to anything else then it must be a source file and treat accordingly

**Comment by MarcoRossignoli** [comment]
@tonerdo i agree with you on single prop.

**Comment by ido-namely** [comment]
I think I addressed all your comments and submitted some changes (let me know if I missed something).
@tonerdo I agree that we can use the same flag, I can make the necessary flag renaming.
However, I do think we will still need to have a flag to establish the parent dir for the searches (with default value of the project directory), this way you can use relative paths or absolute paths (by setting the parent dir to ("/" or "c:\"), another alternative is to check if the path is rooted or not and decide whether to use the the parent dir arg for the given path or take it as is.

**Comment by tonerdo** [comment]
#64 is all merged in. Will get to adding a `Filter` property for ignoring assemblies

**Comment by MarcoRossignoli** [comment]
@ido-namely  thank's for PR!
@tonerdo we could discuss https://github.com/tonerdo/coverlet/issues/56#issuecomment-384231141

**Comment by tonerdo** [comment]
Thanks @ido-namely. @mathnogueira, @MarcoRossignoli, @ryanmvt, @abe545 new release here: https://www.nuget.org/packages/coverlet.msbuild/1.2.0.

@MarcoRossignoli kindly help open a new issue to track adding a `Filter` property to exclude assemblies.

Thanks everyone for the productive comments

**Comment by tonerdo** [comment]
New release available here: https://www.nuget.org/packages/coverlet.msbuild/2.0.0. Thanks for your help and patience guys

**Comment by jeffrutland** [comment]
greetings, over a year later here.  :)

I'm curious if any progress was made on excluding code covered by specifying namespaces in the `<Exclude>` element in the `runsettings` file.

our codebase is built in Azure DevOps, and tested with `dotnet test` - I'd like the coverage analysis to exclude generated code in specific namespaces.  the documentation seems to suggest that filtering via regex is possible, but this is on a page that specifically talks about vstest.  is this possible using `dotnet test` and if so, are there some examples of this available?

**Comment by MarcoRossignoli** [comment]
You could try with something like `[asm]namespace.*` it should exlude all types in the assembly under that namespace. 
You can verify reading the logs, if you're using collectors you can enable and check inside vstest/test logs https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration

**Comment by jeffrutland** [comment]
> You could try with something like `[asm]namespace.*` it should exlude all types in the assembly under that namespace.

is that the exact syntax required this?  I see no different results when running with that in the `<Exclude>` tag.

> You can verify reading the logs, if you're using collectors you can enable and check inside vstest/test logs https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration, search for Included module/Excluded module string.

thanks for the log suggestion - good to know.

**Comment by MarcoRossignoli** [comment]
Mmm...I'll give it a try...I never tested for namespace, but I expect that is something close to that...and I think that we should support that filter feature if missing.

**Comment by MarcoRossignoli** [comment]
@jeffrutland I did some test and syntax should work...I added some test to be sure, take a look to sample https://github.com/tonerdo/coverlet/pull/579

**Comment by jrichardsz** [comment]
> @micheleissa ah, according the msdn documentation, you're using the [msbuild collector](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage). This is how we used to use the msbuild collector (note that we escape the quotes because it was required in the dockerfile to force docker to pass the quotes to the actual command to run - you might be experiencing something similar):
> 
> ```
> dotnet test \
>     --no-build \
>     --configuration Release \
>     -v n \
>     /p:CollectCoverage=true \
>     /p:CoverletOutputFormat=lcov \
>     /p:Include=\"[Namely.*]*\" \	
>     /p:Exclude=\"[Namely.Tests.*]*,[xunit*]*\" \
>     /p:ExcludeByFile=\"/app/src/Namely.Grpc.Client/Grpc/**/*,/app/src/Namely.Kafka/Grpc/**/*\" \
>     "/p:CoverletOutput=/out/coverage/coverage.info" \
>     "test/Namely.Tests/Namely.Tests.csproj"
> ```

`/p:ExcludeByFile=\"/app/src/Common/**/*\"` worked in netcore 7  + linux

**/p:Exclude**  don't works

**Comment by jrichardsz** [comment]
Try with  `/p:ExcludeByFile=` or share us your namespaces

**Comment by johnthagen** [comment]
After a long amount of searching around and trial and error, what I had to do to solve this problem (alluded to in previous comments) is to add the following to my `.Tests` `.csproj`:

```xml
<PackageReference Include="coverlet.msbuild" Version="6.0.0"/>
```

And then I had to switch from the [following command](https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022):

```
dotnet test --collect:"Code Coverage;Format=Cobertura;CoverageFileName=coverage.xml"
```

To:

```
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="coverage.xml /p:ExcludeByFile="**/MyProject/Subfolder/**/*.cs,**/MyProject/AnotherSubFolder/**/*.cs"
```
