### ISSUE TITLE
v5.2.0 was released without a ChangeLog

### ISSUE THREAD

**Issue by ruimaciel** [tonerdo/coverlet#562]
I've received a notification that coverlet 5.2.0 was released, but when I tried to check what changed  It would be nice if the project included a changelog and distributed it as part of a release.

**Comment by MarcoRossignoli** [comment]
Hi @ruimaciel, 
you're right...I'll list asap on this issue the change log.
I'll work on it to have a changelog file for future release.

**Comment by MarcoRossignoli** [comment]
These are the "main" fix/new features if you want to see all new commit between the two version run 

git log --oneline f24b9d567cb84c314cde46dd336f1919db73c5e4 e1593359497fdfe6befbb86304b8f4e09a656d14

[Feature][Collectors]Output multiple formats https://github.com/tonerdo/coverlet/pull/533
[Bug fix]Fix exclude by files https://github.com/tonerdo/coverlet/pull/524
[Feature]Skip instrumentation of module with embedded ppbd without local sources https://github.com/tonerdo/coverlet/pull/510 -> with this today xunit will be skipped in automatic way.
[Bug fix]Changed to calculate based on the average coverage of the module https://github.com/tonerdo/coverlet/pull/479
[Bug fix]Fix property attribute detection https://github.com/tonerdo/coverlet/pull/477
[Feature]Different exit codes to indicate particular failures https://github.com/tonerdo/coverlet/pull/412
[Bug fix]Fix instrumentation serialization bug https://github.com/tonerdo/coverlet/pull/458
[Bug fix]Fix culture for cobertura xml report https://github.com/tonerdo/coverlet/pull/464

**Comment by MarcoRossignoli** [comment]
Or better @tonerdo can you update the release https://github.com/tonerdo/coverlet/releases with my above list?

**Comment by ruimaciel** [comment]
Thanks for looking into this issue.  Meanwhile, how about adding a ChangeLog to the repo?  Here's a link that provides [a specification for a ChangeLog format/workflow](https://keepachangelog.com/en/1.0.0/)

**Comment by MarcoRossignoli** [comment]
Thank's for the interest and infos, added to backlog.

**Comment by tonerdo** [comment]
@ruimaciel thanks for pointing that out. I was in a hurry to get a new release out (we had gone a while without one) and didn't have time to do enough due diligence to write a changelog. Thanks for the list @MarcoRossignoli, I'll update it shortly
