### ISSUE TITLE
Using runsettings means sometimes missing coverage info

### ISSUE THREAD

**Issue by queen-of-code** [tonerdo/coverlet#571]
I've traced down a harrowing issue with missing code coverage on our build server down to the use of runsettings vs directly invoking the cross-plat coverage via the dotnet test command line.

The repro is very simple for our DLL - of SPECIAL note is that this is the same csproj + test csproj combo that previously was not reporting code coverage before the recent advent of collectors. MOST of our test projects do not have this issue.

**Works Fine:**
`dotnet test --collect:"XPlat Code Coverage"`
Output: 
```
<class name="AttributionStrategyBase/&lt;&gt;c__DisplayClass10_0" filename="C:\\src\Sdk\Attribution\AttributionStrategyBase.cs" line-rate="1" branch-rate="0.8636" complexity="22">
```

**Does Not Work:**
`dotnet test --settings ..\coverlet.runsettings`
Output:
```
        <Class>
          <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="22" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="0" maxCyclomaticComplexity="22" minCyclomaticComplexity="22" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="0" />
          <FullName>Attribution.AttributionStrategyBase/&lt;&gt;c__DisplayClass10_0</FullName>
          <Methods />
        </Class>
```
Contents of Runsettings file (I've tried with includes and excludes and all combinations thereof):
```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage">
        <Configuration>
          <Format>cobertura</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

The test csproj has the following versions:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.0.*"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="TeamCity.VSTest.TestAdapter" Version="1.0.15" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="Moq" Version="4.10.1" />
  </ItemGroup>
```

And we are using `dotnet core sdk  3.0.100`

**Comment by MarcoRossignoli** [comment]
@queen-of-code can you provide a repro?
I did some test on my local with and without runsettings but I cannot repro.
My repro with your settings  [issue571.zip](https://github.com/tonerdo/coverlet/files/3665202/issue571.zip)

**Comment by MarcoRossignoli** [comment]
Oh one more thing you should upgrade collector to new version https://www.nuget.org/packages/coverlet.collector/

**Comment by queen-of-code** [comment]
I'll try an upgrade. But are you at least able to repro the two very different formats regardless of coverage numbers? Because that's a clean + easy repro for me and should be the same for you.

**Comment by MarcoRossignoli** [comment]
>  But are you at least able to repro the two very different formats regardless of coverage numbers?

No...can you provide a repro?

**Comment by MarcoRossignoli** [comment]
@queen-of-code when you update the version to 1.1.0 you need to provide runsettings file with a InProcDataCollectors config because i found and issue on vstest plat collector load and we cannot fix on our side at the moment https://github.com/tonerdo/coverlet/issues/576#issue-500327522
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector assemblyQualifiedName="Coverlet.Collector.DataCollection.CoverletInProcDataCollector, coverlet.collector, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null"
                     friendlyName="XPlat Code Coverage"
                     enabled="True"
                     codebase="coverlet.collector.dll" />
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
</RunSettings>
```

**Comment by queen-of-code** [comment]
I'm testing with this now to see if it helps.

**Comment by MarcoRossignoli** [comment]
@queen-of-code any news?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation.
Feel free to re-open if needed!
