### ISSUE TITLE
Unexpected branches reported for async lambda expression

### ISSUE THREAD

**Issue by MarcoRossignoli** [tonerdo/coverlet#584]
In PR https://github.com/tonerdo/coverlet/pull/583 we fixed the issue with false line coverage for lambda.
Now we report a correct line coverage, but we've unexpected uncovered branches reported.
We should try to avoid to report compiler generated branches.
Test name `Lambda_Issue343`

![Capture](https://user-images.githubusercontent.com/7894084/66461435-50db4300-ea79-11e9-9352-88de7d5075cd.PNG)

**Comment by FreedCapybara** [comment]
For what it's worth, I'm seeing this on a non-lambda:
![coverlet](https://user-images.githubusercontent.com/7003723/73466234-95079180-434f-11ea-812c-8df851fadc48.png)

which works if I de-asyncify the code:
![fixed](https://user-images.githubusercontent.com/7003723/73466739-4d353a00-4350-11ea-9de1-284ef738dda5.png)

(coverlet.msbuild 2.8.0)

**Comment by MarcoRossignoli** [comment]
Should be fixed now on master can you try with nightly build https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md?

**Comment by MarcoRossignoli** [comment]
Fixed in https://github.com/tonerdo/coverlet/pull/702

**Comment by FreedCapybara** [comment]
That's okay, I belive you -- I'll just wait 👍

**Comment by MarcoRossignoli** [comment]
cc: @matteoerigozzi

**Comment by matteoerigozzi** [comment]
I agree, should be solved
