### ISSUE TITLE
Command line output, showing detailed class/method coverage

### ISSUE THREAD

**Issue by jbellmore** [tonerdo/coverlet#585]
Hello!

I have in the process of integrating coverlet into my CI builds and was wondering if there is a way to have the console output include more detailed information in the table, such as class and method level coverage?

I tried looking through the documentation but I haven't come across anything that specifies if this is possible, and if so what the cli arg would be to enable that.

I will also at some point be hooking up the reporters (such as opencover) but I would also like to have it in the output logs of the build as just a quick reference for local development runs.

Thanks for all the hard work everyone has put into this project!

**Comment by MarcoRossignoli** [comment]
> I have in the process of integrating coverlet into my CI builds 

Glad to hear....

> if there is a way to have the console output include more detailed information in the table, such as class and method level coverage?

Unfortunatly we don't have that detail or some switch to enable it.
BTW I don't know if could  be a "usable" feature...instrumented type/method could be "a lot", btw at the moment unique solution is to parse and print "by hand" with some script.

Feel free to close the issue if I've answered to your question!And thank's for trying coverlet!

**Comment by jbellmore** [comment]
Thanks for the response!

I will close the issue now, however I do think it would be a great feature to think about including in the future if possible. I have used instanbuljs/nyc before and they have a great output table that is very valuable for local development. See their website for an example:

https://istanbul.js.org/

Thanks again!

**Comment by MarcoRossignoli** [comment]
Thanks to you for link resource!happy coding!
