### ISSUE TITLE
Unable to instrument module: Could not load file or assembly

### ISSUE THREAD

**Issue by thomasgalliker** [tonerdo/coverlet#594]
I'm trying to collect code coverage from two Azure DevOps build tasks. The first task is running all 'UnitTests', the second one is running 'SystemTests'.

- task: DotNetCoreCLI@2
  displayName: 'Run UnitTests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) -p:langversion=$(langversion) --filter Category=UnitTests /p:CollectCoverage=true /p:Exclude="[*.Testdata]*" /p:MergeWith=$(Build.SourcesDirectory)/Tests/CoverletOutput/coverage.json'
    nobuild: true
    
- task: DotNetCoreCLI@2
  displayName: 'Run SystemTests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) -p:langversion=$(langversion) --filter Category=SystemTests /p:CollectCoverage=true /p:Exclude="[*.Testdata]*" /p:MergeWith=$(Build.SourcesDirectory)/Tests/CoverletOutput/coverage.json /p:CoverletOutputFormat=cobertura'
    nobuild: true

The first task, 'Run UnitTests', runs tests of a csproj which references Xamarin.Forms. Strangly, for this project coverlet cannot collect code coverage. The error message is:
` [coverlet] Unable to instrument module: d:\a\1\s\Tests\ProjectName.Tests\bin\Release\netcoreapp2.2\ProjectName.Api.Contracts.dll because : Could not load file or assembly 'Mono.Cecil,`

**Full log output:**
[command]"C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\Tests\ProjectName.Tests\ProjectName.Tests.csproj --logger trx --results-directory d:\a\_temp --configuration Release -p:langversion=latest --filter Category=UnitTests /p:CollectCoverage=true /p:Exclude=[*.Testdata]* /p:CoverletOutput=d:\a\1\s/Tests/CoverletOutput/ /p:MergeWith=d:\a\1\s/Tests/CoverletOutput/coverage.json
d:\a\1\s\ProjectName.Api.Contracts\ProjectName.Api.Contracts.csproj(17,5): warning : ProjectName.Api.Contracts.csproj is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensure that toolkit is properly installed.
d:\a\1\s\ProjectName\ProjectName\ProjectName.csproj(21,5): warning : ProjectName.csproj is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensure that toolkit is properly installed.
C:\Users\VssAdministrator\.nuget\packages\coverlet.msbuild\2.7.0\build\coverlet.msbuild.targets(24,5): warning : [coverlet] Unable to instrument module: d:\a\1\s\Tests\ProjectName.Tests\bin\Release\netcoreapp2.2\ProjectName.Api.Contracts.dll because : Could not load file or assembly 'Mono.Cecil, Version=0.10.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'. Could not find or load a specific file. (0x80131621) [d:\a\1\s\Tests\ProjectName.Tests\ProjectName.Tests.csproj]
C:\Users\VssAdministrator\.nuget\packages\coverlet.msbuild\2.7.0\build\coverlet.msbuild.targets(24,5): warning : [coverlet] Unable to instrument module: d:\a\1\s\Tests\ProjectName.Tests\bin\Release\netcoreapp2.2\ProjectName.dll because : Could not load file or assembly 'Mono.Cecil, Version=0.10.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'. Could not find or load a specific file. (0x80131621) [d:\a\1\s\Tests\ProjectName.Tests\ProjectName.Tests.csproj]

**Comment by MarcoRossignoli** [comment]
Hi Thomas,

Do you repro issue also in local or only on CI?

**Comment by thomasgalliker** [comment]
Hi Marco. I was spending the whole night to try to get it work - and it finally works now. I think it matters which tool I use to build the solution. The above error **only happens when I use `dotnet build`** to build the solution. Very tricky to reproduce because Visual Studio 2019 obviously uses its own build tools (based on `MSBuild`?) which definitly generates a different build output than what `dotnet build` generates.

So, my solution for this was to create a separate *.sln which does not contain any Xamarin app projects. This way I could remain with `dotnet build` in my azure-pipelines.yml:

```
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: build
    projects: 'ProjectName.Api.sln'
    arguments: '--no-restore --configuration $(buildConfiguration)'

```

**Comment by MarcoRossignoli** [comment]
yep AFAIK `dotnet build` and `msbuild` are different beast https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/#full-msbuild vs https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/#dotnet-msbuild

Feel free to close this issue if solved!

**Comment by thomasgalliker** [comment]
Yes, well, not that I‘m new to .net but these kind of things surprise me. Thanks for your support! :-)

**Comment by MarcoRossignoli** [comment]
Now worries!
Don't hesitate to re-open or ask if you need further support!
Happy coding!
