### ISSUE TITLE
How to programmatically collect coverage data?

### ISSUE THREAD

**Issue by ghost** [tonerdo/coverlet#599]
How can I get coverage when programmatically running tests (like xunit/xunit#542)?

**Comment by MarcoRossignoli** [comment]
close because I think it's an error...ghost user.

**Comment by selessshore** [comment]
Thanks for your quick reply @MarcoRossignoli! I believe this is a duplicate of #483, and further #212, right?

I see #212 was reopened recently. Did you change your mind to support this feature?

**Comment by MarcoRossignoli** [comment]
yep the idea is to expose a stable package with new apis, we need to merge/fix some stuff https://github.com/tonerdo/coverlet/pull/566 https://github.com/tonerdo/coverlet/issues/576 and after that we could start with discussion on api design.
