### ISSUE TITLE
No output generated

### ISSUE THREAD

**Issue by Structed** [tonerdo/coverlet#6]
I have installed the package to my test project, ran `dotnet test /p:CollectCoverage=true` as well as `dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover`, but no code coverage report was generated.

dotnet SDK: 1.0.4
Taregt Framework: netcoreapp1.1
xunit: 2.3.1
coverlet.msbuild: 1.0.0

**Comment by tonerdo** [comment]
@Structed pls target `netcoreapp2.0` and let me know if you still don't see an output

**Comment by SchneiderPatrick** [comment]
@tonerdo Hey :) I have the same problem targeting netcoreapp2.0.

**Comment by tonerdo** [comment]
What's the output of `dotnet --info`?

**Comment by tonerdo** [comment]
Also, what test framework are you using?

**Comment by SchneiderPatrick** [comment]
I also tried the latest stable version of the .net core sdk.
I used xunit and mstest. same result with both of these.

.NET Command Line Tools (2.1.300-preview1-008174)

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64

**Comment by tonerdo** [comment]
So my only thought is Coverlet is unable to find a suitable assembly to instrument. 
Couple of questions:

What's the structure of your solution?
Are your tests in the same project with the classes you're testing?
Does the assembly you're trying to get coverage for have a PDB?

**Comment by lukasz-ciura-neyber** [comment]
Hi, I have similar problem, but I get error in output:

 Calculating coverage result...
C:\Users\username\.nuget\packages\coverlet.msbuild\1.0.0\build\netstandard2.0\coverlet.msbuild.targets(19,5): error : **Could not find file 'C:\Users\username\AppData\Local\Temp\ProjectName.Common_6c1a88f4-0f61-4510-827b-a26cc32ae3a4'.** [C:\Users\username\Projects\ProjectName\ProjectName\src\Tests\ProjectName.GatewayCommon.UnitTests\ProjectName.GatewayCommon.UnitTests.csproj]

But file exists with extension .dll:
C:\Users\username\AppData\Local\Temp\ProjectName.Common_6c1a88f4-0f61-4510-827b-a26cc32ae3a4.**dll**

Can you advice?

**Comment by mihasic** [comment]
If you want to check on failing project: https://github.com/mihasic/LuceneSearch/tree/coverlet

**Comment by jeankedotcom** [comment]
Hi, I am having the same problem as @lukasz-ciura-neyber 

Using **dotnet 2.1.203**

![error](https://user-images.githubusercontent.com/8275811/37888008-4d66b6ba-30c5-11e8-9c7d-ee412250b05d.png)

![file](https://user-images.githubusercontent.com/8275811/37888009-4d828a8e-30c5-11e8-854e-e824022e8686.png)

**Comment by tonerdo** [comment]
Try a out the new NuGet package and let me know how it goes https://www.nuget.org/packages/coverlet.msbuild/1.0.1

**Comment by mihasic** [comment]
works for me, thank you

**Comment by jeankedotcom** [comment]
With version 1.0.1 I get another error

![coverlet-error](https://user-images.githubusercontent.com/8275811/37903876-e0b0c4f4-30f9-11e8-8452-790f948dad70.png)

**Comment by tonerdo** [comment]
@jeankedotcom I think that happens when calculating the summary result. The coverage results file should still have been generated

**Comment by jeankedotcom** [comment]
@tonerdo you are right, the coverage file exists.

But if the "dotnet test" command fails it will break my CI build on GitLab. Can I disable the summary report?

**Comment by tonerdo** [comment]
Hmmm... there's currently no way to disable summary, I should probably add that option. Is there a way for you to ignore that error?

**Comment by jeankedotcom** [comment]
I will check if I can ignore the error.
Or maybe you could check for totalLines to be 0 in line 35 of CoverageSummary.cs.

Something like this?
```csharp
result.Add(System.IO.Path.GetFileNameWithoutExtension(mod.Key), totalLines == 0 ? totalLines : (linesCovered * 100) / totalLines);
```

**Comment by tonerdo** [comment]
@jeankedotcom new NuGet release which should completely fix this isse: https://www.nuget.org/packages/coverlet.msbuild/1.0.2. Feel free to reopen if any more errors show up
