### ISSUE TITLE
allow customization of CoverletOutput output name as to avoid overwrites when redirecting output to another path

### ISSUE THREAD

**Issue by dmccaffery** [tonerdo/coverlet#60]
https://github.com/tonerdo/coverlet/blob/c04fc782af3a77426e449f2b33c4c36fa738dd28/src/coverlet.msbuild/coverlet.msbuild.props#L7

^^ should have a condition as to not overwrite user provided values.

**Comment by dmccaffery** [comment]
@tonerdo : I put in a PR for this already, just in case you want to accept it ;-)

**Comment by tonerdo** [comment]
New release here: https://www.nuget.org/packages/coverlet.msbuild/2.0.0
