### ISSUE TITLE
how to use coverlet as project in a solution  

### ISSUE THREAD

**Issue by Nitin5acc** [tonerdo/coverlet#600]
Hello,

we would like to use this source code and create coverlet .net core projects in our application (sln) which can be used on other projects to check coverage. 
We have taken the code from this repo and added it in our solution. However, no coverage is generated.

**Comment by MarcoRossignoli** [comment]
Hi Nitin, 

it's not clear to me your question...would you like to have a coverage of your test projects?
You need to follow the guide https://github.com/tonerdo/coverlet#installation
Why you download sources?

**Comment by Nitin5acc** [comment]
Hello, we would not like to use coverlet as package. We want to bring source code into our solution, build the same and use that as dll to check the coverage on other projects.

**Comment by MarcoRossignoli** [comment]
As I've said above you can copy .net tool usage https://github.com/tonerdo/coverlet/blob/master/src/coverlet.console/Program.cs#L64 we don't have an example on codebase 
Maybe @Shargon can help here, they used coverlet by code.

**Comment by MarcoRossignoli** [comment]
At the moment we're blocked on vstest bug, after that fix we can go on with hiding all class and design a stable api to expose internal features https://github.com/microsoft/vstest/pull/2221

**Comment by shargon** [comment]
You have an example in github.com/red4sec/TuringMachine

**Comment by MarcoRossignoli** [comment]
@Nitin5acc feel free to close if solved, thanks @shargon for the sample!

**Comment by MarcoRossignoli** [comment]
@Nitin5acc related PR https://github.com/tonerdo/coverlet/pull/628
