### ISSUE TITLE
The test project itself is not included into code coverage.

### ISSUE THREAD

**Issue by Tum4ik** [tonerdo/coverlet#603]
I have this NetStandard2.0 class library and tests for it.

![image](https://user-images.githubusercontent.com/21317790/68077606-49d0f780-fdcf-11e9-8ce9-2bf1b808db2f.png)

But when I run `dotnet test /p:CollectCoverage=true`, the test project itself is not included into code coverage.

![image](https://user-images.githubusercontent.com/21317790/68077629-90265680-fdcf-11e9-9044-76b184703144.png)

Should not be so, right? Could you help me to fix that.

**Comment by MarcoRossignoli** [comment]
Try with `/p:IncludeTestAssembly=true`

**Comment by Tum4ik** [comment]
Perfect! Thanks.
