### ISSUE TITLE
AutoGeneratedProgram included into coverage

### ISSUE THREAD

**Issue by Tum4ik** [tonerdo/coverlet#604]
I've included the test project itself into code coverage via `/p:IncludeTestAssembly=true`, but there is strange file generated `AutoGeneratedProgram` and it breaks the real coverage results.

Here is how it looks in the report:

![image](https://user-images.githubusercontent.com/21317790/68091497-2ff3eb00-fe89-11e9-93f9-31972abb2dd1.png)

Here are the datails:

![image](https://user-images.githubusercontent.com/21317790/68091504-531e9a80-fe89-11e9-8ba1-90606f6db89f.png)

The question is: how could I avoid that?
Thanks.

**Comment by MarcoRossignoli** [comment]
yep you can exclude types using filter https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#attributes

I think that in your case you can use ` /p:ExcludeByAttribute="TestSDKAutoGeneratedCode"`

**Comment by Tum4ik** [comment]
Nice! Thanks a lot.
