### ISSUE TITLE
Question: What is modules?

### ISSUE THREAD

**Issue by Orwel** [tonerdo/coverlet#606]
Hi,

When I run coverlet, I have the next result :
```
+-----------------+--------+--------+--------+
| Module          | Line   | Branch | Method |
+-----------------+--------+--------+--------+
| MyProject | 85.78% | 78.94% | 84.61% |
+-----------------+--------+--------+--------+
```

Can you explain the module notion?
Can you detail what is Line, Branch and Method?

**Comment by MarcoRossignoli** [comment]
Hi @Orwel 

Module are simpy assemlby dll files https://github.com/tonerdo/coverlet/blob/f3cce5ded8b735735ff49bf01cf7b77c505c88d2/src/coverlet.core/Helpers/InstrumentationHelper.cs#L67

Line are your source code lines of code, for instance for c# is a simple code line and are reported thank's to pdb/source mappings generated by compiler.

Branch are all "conditional branch" operation do by code(for instance a simple `br` https://en.wikipedia.org/wiki/List_of_CIL_instructions) https://github.com/tonerdo/coverlet/blob/f3cce5ded8b735735ff49bf01cf7b77c505c88d2/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L77
if,switch etc...

Method are all all IL member defined as "method" i.e. `.method private hidebysig static void Main() cil managed` present in classes in IL `.class`

```il
.class public Foo
{
    .method public static int32 Add(int32, int32) cil managed
    {
        .maxstack 2
        ldarg.0 // load the first argument;
        ldarg.1 // load the second argument;
        add     // add them;
        ret     // return the result;
    }
}
```

**Comment by Orwel** [comment]
Thank you for these explanations.
