### ISSUE TITLE
Multiple command options with "v"

### ISSUE THREAD

**Issue by satheeshds** [tonerdo/coverlet#609]
When i run 
`coverlet /path/to/test-assembly.dll --target "dotnet" --targetargs "test /path/to/test-project --no-build" -v normal`

console gives output 

> Multiple options with name "v" found. This is usually due to nested options.

checked the doc, "v" is assigned for version as well as verbosity

**Comment by MarcoRossignoli** [comment]
Should work with `--verbosity normal` , right?

**Comment by MarcoRossignoli** [comment]
any news?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation.

Feel free to re-open if needed.
