### ISSUE TITLE
TeamCity output only shows summary

### ISSUE THREAD

**Issue by msnelling** [tonerdo/coverlet#617]
I don't see any line, branch or method level output when using under teamcity as documented [here](https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md).
I am using the following command to generate test coverage data `dotnet test UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=teamcity`

I can see in [this](https://github.com/tonerdo/coverlet/pull/493/files) pull request that outputting line an method coverage service messages was removed?

**Comment by MarcoRossignoli** [comment]
@dijitle you did that PR can you take a look?
Actually I see `CodeCoverageL` and `CodeCoverageM` can you explain why?

**Comment by msnelling** [comment]
@MarcoRossignoli yes I see those values. I think this might be my misunderstanding of expected output if what you say is correct about the `CodeCoverageB, CodeCoverageL, CodeCoverageM, CodeCoverageC` lines.

**Comment by MarcoRossignoli** [comment]
TeamCity should work with service message as explained https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#Reporting-Build-Statistics
Do you see "empty" results or are these "unexpected" in values?

**Comment by MarcoRossignoli** [comment]
@msnelling let me know of feel free to close if it's conform to team city specifications.

**Comment by msnelling** [comment]
@MarcoRossignoli no I see the correct values, I think this was just my misunderstanding. I thought the `CodeCoverageB, CodeCoverageL, CodeCoverageM, CodeCoverageC` would give me detailed coverage like in a report.

Feel free to close the issue.
