### ISSUE TITLE
Runsettings file failing with error "Data collection : Could not find data collector 'XPlat Code Coverage"

### ISSUE THREAD

**Issue by dougiejay** [tonerdo/coverlet#619]
Hi,
I can successfully run coverlet in our build tests on Azure DevOps using netcore 2.2, but as soon as I try to use a runsettings file I get an error.
Data collection : Could not find data collector 'XPlat Code Coverage'

Im using a file based on what I saw in your point 2 of Known Issues to include the datacollector information, and have made sure we have upgraded our prerequisites. The full file is below.

`<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage">
        <Configuration>
          <CodeCoverage>
		    <Functions>
				<Exclude>
				  <Function>.*get_.*</Function>
				  <Function>.*set_.*</Function>
			      <Function>^CarWebServiceReference\..*</Function>
			</Exclude>
			</Functions>
            <ModulePaths>
              <Exclude>
                <ModulePath>.*framework.dll</ModulePath>
                <ModulePath>.*framework.model.dll</ModulePath>
                <ModulePath>.*framework.mvc.dll</ModulePath>
                <ModulePath>.*test.dll</ModulePath>
                <ModulePath>.*microsoft.windowsazure.storage.dll</ModulePath>
                <ModulePath>.*fluentassertions.dll</ModulePath>                
                <ModulePath>.*fluentassertions.core.dll</ModulePath>
                <ModulePath>.*Moq.dll</ModulePath>
                <ModulePath>.*newtonsoft.json.dll</ModulePath>
              </Exclude>
            </ModulePaths>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
    <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector assemblyQualifiedName="Coverlet.Collector.DataCollection.CoverletInProcDataCollector, coverlet.collector, Version=2.7.0.0, Culture=neutral, PublicKeyToken=null"
                     friendlyName="XPlat Code Coverage"
                     enabled="True"
                     codebase="coverlet.collector.dll" />
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
</RunSettings>`

I hope you can help me?

**Comment by MarcoRossignoli** [comment]
First of all at the moment inproc collector version is 1.1.0 https://www.nuget.org/packages/coverlet.collector/
You can try with this sample [collectors.zip](https://github.com/tonerdo/coverlet/files/3854037/collectors.zip) launch run inside `XUnitTestProject1`

FYI there is also a preview release of vstest plat https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/ if you use this version you can remove `InProcDataCollectionRunSettings` section, I did some test and now inproc collector is loaded correctly cc: @vagisha-nidhi 

I left new package inside a comment in project file of `XUnitTestProject1` if you can use preview in prod.

**Comment by dougiejay** [comment]
OK so in all my test projects I added this reference:
<PackageReference Include="coverlet.msbuild" Version="2.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
Your sample adds coverlet.collector
I will change my project and see if that fixes it.

**Comment by dougiejay** [comment]
Yes that fixed the error thank you. However the runsettings file seems to still being ignored as it is not excluding the CarWebServiceReference namespace. Can you check if that part looks correct please?

**Comment by dougiejay** [comment]
OK I spotted your samples for settings file and I have this working now! Thanks!

**Comment by MarcoRossignoli** [comment]
Coverlet is used through 3 different drivers, msbuild, .net tools and vstest integration...`XPlat Code Coverage` is the way to indicate that you want to load coverlet collectors...msbuild work only with `dotnet test /p:CollectCoverage=true` check the guide https://github.com/tonerdo/coverlet#quick-start
