### ISSUE TITLE
Q: Possible to re-use resharpers [ExcludeFromCodeCoverage]?

### ISSUE THREAD

**Issue by eriklilljequist** [tonerdo/coverlet#62]
I'm brand new to coverlet and are having some issues with understanding how to exclude from coverage, the Readme.MD is not self explanatory and I have been unable to find any other doc.
In my project some are working with resharper to get coverage. 

Hence, 2 things:
* Example on how to exclude e.g. a class from coverage with Coverlet
* Is it possible to reuse resharpers [ExcludeFromCodeCoverage]-markings?

currently I have set up VS codes testtask to run coverlet and are using Coverage Gutters to decorate the editor, seems to working just fine. However I would like a way to view coverage as an html-report, any ideas?

Thank you and hopefully these questions are not too awkward as an issue.

/E

**Comment by mgw854** [comment]
Excluding classes from coverage is easy. Just decorate it with an attribute (either ExcludeFromCoverage or ExcludeFromCodeCoverage should work):

```csharp
[ExcludeFromCoverage]
internal sealed class NotParticularyInterestingClass
{
}
```

For HTML reports, I've had good luck with [ReportGenerator](https://github.com/danielpalme/ReportGenerator).

**Comment by tonerdo** [comment]
Thanks for answering @mgw854. In addition @eriklilljequist, you'll need to create the `ExcludeFromCoverage` attribute somewhere in your project:

```
using System;

namespace AnyoneIsFine
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor)]
    public class ExcludeFromCoverageAttribute : Attribute { }
}
```

#34 contains work to support `ExcludeFromCodeCoverage` present in `System.Diagnostics.CodeAnalysis` and like you mention Resharper

**Comment by eriklilljequist** [comment]
*Regarding HTML-reports:*
 Thank you, I will then continue looking into report generator. 

*Regarding Coverage:*
`[ExcludeFromCoverage]` renders a compile-time error, dunno where this class is supposed to be found, not within my installed assemblies at least. `[ExcludeFromCodeCoverage]` is found in `System.Diagnostics.CodeAnalysis` but does not seem to be considered when i run dotnet test. 

fyi: I run dotnet test with and without `[ExcludeFromCodeCoverage]` on a class and either way i receive 62,3% coverage.

**Comment by tonerdo** [comment]
@eriklilljequist like I mentioned in my last comment you'll have to add the `ExcludeFromCoverage` class to your project

**Comment by eriklilljequist** [comment]
@tonerdo 

Ok, so I'll add the `ExcludeFromCoverage` class and can work from that.

And when #34 gets merged Coverit will understand `ExcludeFromCodeCoverage` and hence be compatible with Resharper-based projects? Where-upon I can remove `ExcludeFromCoverage`?

Have I got i right?

**Comment by tonerdo** [comment]
@eriklilljequist That sounds about right. Let me know if you run into any other issues

**Comment by jcanady20** [comment]
I was under the impression that System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute was a standard attribute, included in BCL.
I"m concerned that you have included a new Attribute that does the exact same thing.

**Comment by tonerdo** [comment]
Now available in https://www.nuget.org/packages/coverlet.msbuild/2.0.1
