### ISSUE TITLE
Incorrect branch coverage with async/await test

### ISSUE THREAD

**Issue by tfadler** [tonerdo/coverlet#623]
If I am under the wrong impression then please let me know.

But I expected scenarios like the below to have full branch coverage.

Reproduced with .net core 3.0 and coverlet 2.7.0

**Code**

```

namespace ClassLibrary1
{
	public class Class1
	{
		public async Task<int> DoAsync()
		{
			await Task.Delay(100);
			return 42;
		}
	}
}
```

**Test Code**

```
namespace ClassLibrary1Test
{
	public class Class1Test
	{
		[Fact]
		public async Task Test1()
		{
			var objectToTest = new Class1();

			var result = await objectToTest.DoAsync().ConfigureAwait(false);

			Assert.Equal(42, result);
		}
	}
}
```

I run

dotnet test /p:CollectCoverage=true

And here is my contents of my coverage.json

I did not expect the branches.  

In our real code base we are using /p:CoverletOutputFormat=opencover  and reportgenerator and the results for branch is less than a 100%

I expected full branch coverage.

```
{
  "ClassLibrary1.dll": {
    "C:\\Users\\name1\\source\\repos\\ClassLibrary1\\ClassLibrary1\\Class1.cs": {
      "ClassLibrary1.Class1/<DoAsync>d__0": {
        "System.Void ClassLibrary1.Class1/<DoAsync>d__0::MoveNext()": {
          "Lines": {
            "8": 1,
            "9": 1,
            "10": 1,
            "11": 1
          },
          "Branches": [
            {
              "Line": 9,
              "Offset": 35,
              "EndOffset": 37,
              "Path": 0,
              "Ordinal": 0,
              "Hits": 1
            },
            {
              "Line": 9,
              "Offset": 35,
              "EndOffset": 101,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 1
            }
          ]
        }
      }
    }
  }
}
```

**Comment by MarcoRossignoli** [comment]
Hi @tfadler!

> I did not expect the branches.

Actually there is a generated state machine by c# compiler so that branch exists(c# lie)

We recently did some improvements to async/await to remove unexpected branches without risk too much https://github.com/tonerdo/coverlet/pull/549 and will be available on next release

BTW I did some test with your code and it's reported 100% to me on report generator(you can also check by yourself...lines and branches has got 1 in "Hits" element, so I expect full coverage(also with compiler generated branch noise).

![image](https://user-images.githubusercontent.com/7894084/69525965-82e12f80-0f69-11ea-9981-378d7119f284.png)

My command line
```bash
C:\git\coverletissue\Issue549
λ dotnet test --collect:"XPlat Code Coverage"
Test run for C:\git\coverletissue\Issue549\XUnitTestProject1\bin\Debug\netcoreapp3.1\XUnitTestProject1.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Attachments:
  C:\git\coverletissue\Issue549\XUnitTestProject1\TestResults\e97f793e-8e40-4508-8316-429ed36d972a\coverage.cobertura.xml
Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 3,3677 Seconds
...
C:\git\coverletissue\Issue549
λ reportgenerator -reports:C:\git\coverletissue\Issue549\XUnitTestProject1\TestResults\e97f793e-8e40-4508-8316-429ed36d972a\coverage.cobertura.xml -targetdir:C:\git\coverletissue\Issue549\XUnitTestProject1\TestResults\e97f793e-8e40-4508-8316-429ed36d972a
```

**Comment by tfadler** [comment]
Many thanks @MarcoRossignoli 

You are right.  I saw the branches in the result and I thought I had reproduced my issue.  That example does display correctly.

I tried and tried and I have narrowed down my real problem.

In our production code we are looping through test projects and each get a coverageresults file.  Each production code project has its own test project and some (not many) of the production code projects will have a reference to another production code project.  No circular dependencies, mind you.  It appears to be a problem when reportgenerator takes all those result files into together to make one report.  The await calls are said to miss a 1 branch.  

Example

Projects
Library1
Library2 (with a dependence on Library1)

Test Projects
Library1Test
Library2Test

The build script loops through all Test projects and creates coverageresult files and then those are given to reportgenerator.   Seems that code with await in say Library1 will have missing branches.  

At least that is what I have narrowed down.

I have added an argument to the build script to only include for that given library namespace when we are making code coverage and the problem went away.  

Note I believe we are building the coverage report this way since we have multiple solutions.  

I'll see if I can reproduce with a smaller spike.

**Comment by MarcoRossignoli** [comment]
Understood...if you can provide a repro could be great.
Try to check all reports file(xml) to understand if all has got a hit 1 one that branch...could be an "override" issue?One file report 1 the other 0 and 0 one is used.

**Comment by tfadler** [comment]
Thank you @MarcoRossignoli !

I was able to reproduce on a smaller scale.

https://github.com/tfadler/CoverletTest

I checked in the test result files and the report.  

Here was my command line

```

C:\Projects\tfadlerCoverage>cd ClassLibrary1Test

C:\Projects\tfadlerCoverage\ClassLibrary1Test>dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../testresults/ClassLibrary1Test.coverageresults"

...

C:\Projects\tfadlerCoverage\ClassLibrary1Test>cd ..\ClassLibrary2Test

C:\Projects\tfadlerCoverage\ClassLibrary2Test>dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../testresults/ClassLibrary2Test.coverageresults"

...

C:\Projects\tfadlerCoverage\ClassLibrary2Test>cd ..\ClassLibrary3Test

C:\Projects\tfadlerCoverage\ClassLibrary3Test>dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../testresults/ClassLibrary3Test.coverageresults"

...

C:\Projects\tfadlerCoverage\ClassLibrary3Test>dotnet reportgenerator -reports:"..\testresults\*" -targetdir:"..\reports"


```
![result](https://user-images.githubusercontent.com/42788888/69825944-a8bf3c00-11d6-11ea-9e8f-5727fe16ca1e.PNG)

![result2](https://user-images.githubusercontent.com/42788888/69825964-c4c2dd80-11d6-11ea-8295-270d3213e7e9.PNG)

I worked around the issue in our system by adding an include for just the executable that the given test project was supposed to test.  Preventing any overlap from happening in the coverage results.  

I'll try looking at the files to get an idea on what is going on next when I get a chance but I want to share this.

Thank you!

**Comment by MarcoRossignoli** [comment]
thank's for sharing I'll take a look asap
