### ISSUE TITLE
Query - Plans for expose it as Console runner

### ISSUE THREAD

**Issue by arpit-nagar** [tonerdo/coverlet#63]
Thanks for implementing the much-needed functionality.
Do you have any plans/timelines for implementing it as a console runner? so that we won't require adding nuget in all project and can be used as a tool to generate the coverage report.

**Comment by tonerdo** [comment]
Yes definitely. Once .NET Core 2.1 comes out of Preview and is publicly available

**Comment by snebjorn** [comment]
I assume that "Console runner" means dotnet global tool, if that's the case then ditto :)

**Comment by StephenMP** [comment]
@arpit-nagar If you're building a .NET Core project with CI or CD, there is a workaround that I'm doing that allows me to not have to install the NuGet package into my test projects.

Basically, I just add the NuGet package on the fly in my build server before running the tests. For example:

```
dotnet add path/to/test/project.csproj package coverlet.msbuild
dotnet restore
dotnet test path/to/test/project.csproj -p:CollectCoverage=true
```

When ran in my build server, the above adds Coverlet package on the fly, runs tests, and collects the code coverage results without the need for my test project to have the NuGet package installed initially :)

**Comment by tonerdo** [comment]
@arpit-nagar @snebjorn @StephenMP This now a mode of coverlet, find global tool package here: https://www.nuget.org/packages/coverlet.console/
