### ISSUE TITLE
For MSBuild integration multiple output formats does not work

### ISSUE THREAD

**Issue by lkurzyniec** [tonerdo/coverlet#630]
My unit test project contains `coverlet.msbuild` package. When I run `dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover,lcov` I received
```
MSBUILD : error MSB1006: Property is not valid.
Switch: lcov

For switch syntax, type "MSBuild -help"
```

![image](https://user-images.githubusercontent.com/5943484/70034406-6b312900-15b1-11ea-801f-51b7ff2f82e2.png)

**Comment by MarcoRossignoli** [comment]
It's a know issue with escaping try with `dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\"`

**Comment by MarcoRossignoli** [comment]
We should update documetation

**Comment by lkurzyniec** [comment]
For CMD works fine, but for `powershell` it won't work.
![image](https://user-images.githubusercontent.com/5943484/70050968-734c9100-15d0-11ea-9827-066bb937106d.png)

**Comment by MarcoRossignoli** [comment]
Ah ok sorry it was on guide try with `PS C:\git\coverlet> dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat="opencover%2clcov"` `%2c` is translated to comma.

**Comment by lkurzyniec** [comment]
Yeap, now it works. You can close the ticket, but please remember to update the documentation.

**Comment by MarcoRossignoli** [comment]
Is already present...but yes a bit cryptic and hidden

`To exclude or include multiple assemblies when using Powershell scripts or creating a .yaml file for a VSTS build %2c should be used as a separator. Msbuild will translate this symbol to ,`
