### ISSUE TITLE
.net core 3.1 with global installation not working

### ISSUE THREAD

**Issue by StefanKoenigMUC** [tonerdo/coverlet#637]
Hi,

today we upgraded to .net core 3.1, since then coverlet does not generate coverage statistics anymore:

`Hits file:'MyLib_b975cdba-959a-4def-b0dd-cc2fbcc567ba' not found for module: 'Ariskon.PortfolioManagement.Objects'`

Do you have any idea how to fix that issue? All other output looks fine so far.

Thanks in advance,

**Comment by MarcoRossignoli** [comment]
What driver are you using?msbuild/.net tool/vs test integration?

**Comment by StefanKoenigMUC** [comment]
´´´
coverlet \bin\Debug\netcoreapp3.0\PortfolioManagementObjectsUnitTests.dll --verbosity detailed --target "dotnet" --targetargs "test --logger "nunit;LogFilePath=../../BuildReports\-test-result.xml" PortfoliomanagementBackend\PortfolioManagementObjectsUnitTests\PortfolioManagementObjectsUnitTests.csproj --no-build" -f=cobertura --output BuildReports\Coverage\
´´´

that's how i call it, but with resepect to your question - i think thats the .net tool with nunit.

**Comment by MarcoRossignoli** [comment]
Ok can you attach the console log?with verbosity you should see how many libs are instrumented for coverage

**Comment by MarcoRossignoli** [comment]
Ah also FYI https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#1-vstest-stops-process-execution-earlydotnet-test

**Comment by StefanKoenigMUC** [comment]
``` 
c:\jenkins\workspace\Develop>coverlet Backend\UnitTests\bin\Debug\netcoreapp3.0\UnitTests.dll --verbosity detailed  --target "dotnet" --targetargs "test --logger "nunit;LogFilePath=../../BuildReports\UnitTests\UnitTests-test-result.xml" Backend\UnitTests\UnitTests.csproj --no-build" -f=cobertura --output BuildReports\Coverage\ 

Instrumented module: 'Backend\UnitTests\bin\Debug\netcoreapp3.0\Objects.dll'
Excluded module: 'Backend\UnitTests\bin\Debug\netcoreapp3.0\Dapper.dll'
Test run for c:\jenkins\workspace\Develop\Backend\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Results File: c:\jenkins\workspace\Develop\BuildReports\UnitTests\UnitTests-test-result.xml
Test Run Successful.
Total tests: 530
     Passed: 530
 Total time: 30,4863 Seconds

Calculating coverage result...
Hits file:'C:\Users\tu_adbatch\AppData\Local\Temp\Objects_b975cdba-959a-4def-b0dd-cc2fbcc567ba' not found for module: 'Objects'
  Generating report 'BuildReports\Coverage\coverage.cobertura.xml'
+-------------------------------------+------+--------+--------+
| Module                              | Line | Branch | Method |
+-------------------------------------+------+--------+--------+
| Objects | 0%   | 0%     | 0%     |
+-------------------------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
```

i don't see the link above reflected within this output?

thanks for your help!

**Comment by MarcoRossignoli** [comment]
> i don't see the link above reflected within this output?

Yes in issue 1 you get as possible warning similar to your...do your test use RabbitQ or some other third party platform that need a "initialize" and "shutdown" process?
If not can you generate a small "repro" with the issue?
If not can your try to use vstest integration?  https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md with know issue(fixed and in preview) https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#2-upgrade-coverletcollector-to-version--100

**Comment by StefanKoenigMUC** [comment]
aaaaah, gave me the right hint - after updating 

NUnit3TestAdapter
Microsoft.NET.Test.Sdk

it's working again.

Thanks for your help!

**Comment by MarcoRossignoli** [comment]
Glad to hear!Feel free to close this issue if solved!
