### ISSUE TITLE
Add support to manually select instrumented assemblies instead of project references

### ISSUE THREAD

**Issue by aliendev3096** [tonerdo/coverlet#640]
Can you add support manually select instrumented assemblies instead of project references.

Say you have an app with its references assemblies in a separate folder "App" and you want to run your test from a different folder that executes code in the "App folder". This would be good for integration testing in .Net Core products.

**Comment by MarcoRossignoli** [comment]
> Can you add support manually select instrumented assemblies instead of project references.

We already  have "filters" to select which asm instrument and cover https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings `Include` ...can you explain better?Which "driver" are you using msbuild(dotnet test) .net tool(coverlet) or vstest (--collect:"XPlat Code Coverage")?Can you write a sample?

**Comment by aliendev3096** [comment]
I am using the the msbuild driver. I've provided my own runsettings file as suggested but then I run dotnet test --collect:"XPlat code coverage" test.dll --settings coverlet.runsettings I get the following error: Data collection : Could not find data collector 'XPlat code coverage'

I've also specified  --collect:"XPlat Code Coverage" but no luck there as well.
The nuget package is installed in my test project. I'm obviously missing something.

**Comment by MarcoRossignoli** [comment]
Do you respect the requirements https://github.com/tonerdo/coverlet#requirements?
Can you attach your command line image o generate a small "repro" with the issue?
I think that's only a syntax error...I'll attach a running sample...launch `run.cmd` after unzip 
[VsTestIntegration.zip](https://github.com/tonerdo/coverlet/files/3940402/VsTestIntegration.zip)

**Comment by aliendev3096** [comment]
Essentially want I want to be doing is start the API on a separate process and run the tests that include filters on the assemblies used to start the API. I've switched to the dotnet global tool with this command:

coverlet tests/IntegrationTests/bin/Release/netcoreapp3.1/IntegrationTests.dll --target "dotnet" --targetargs "test tests/IntegrationTests/IntegrationTests.csproj --no-build -c Release" --include-directory "src/Test.API/bin/Release/netcoreapp3.1"

Here I'm including the directory where started the API from. The tests make a call to the API for which I would expect coverage on but now I am getting zero coverage. My guess is because The API has been started before the instrumentation happens.

Sorry for switching tools on you haha I've really just trying to learn this neat tool.

**Comment by MarcoRossignoli** [comment]
> Here I'm including the directory where started the API from. The tests make a call to the API for which I would expect coverage on but now I am getting zero coverage. My guess is because The API has been started before the instrumentation happens.

You code seem correct....net tool before instrument dll in your case `IntegrationTests.dll` and after simply invoke `dotnet test` on project without rebuild, so we should load "instrumented" libs.
Can you try to produce a small repro with this behaviour?
Also add a vebosity log so we can check what is instrumented, follow the guide https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#coverlet-global-tool

**Comment by aliendev3096** [comment]
I am going to close this issue. Coverlet obviously allows for manual select through filters.
