### ISSUE TITLE
In coverlet.collector, allow repeating configuration elements in runsettings

### ISSUE THREAD

**Issue by EricStG** [tonerdo/coverlet#641]
When excluding multiple elements, the current format can make things a bit unwieldy (and makes the changes much harder to track
```
<Exclude>[lib]ns1.*,[lib]ns2.*</Exclude>
```
It would be nice if we could specify multiple items on different Exclude nodes:
```
<Exclude>[lib]ns1.*</Exclude>
<Exclude>[lib]ns2.*</Exclude>
```
Same goes for the other colon separated settings

**Comment by MarcoRossignoli** [comment]
It's technically doable, btw I'm not a huge fan of this, to me seem more clear and compact a "command line args" format where I've all "fragments" of an options close each other, also a config become less clear(less compact).

BTW I defer to community thought and we'll wait for more "thumbs up" to consider the implementation.

Thank's fort the idea!

**Comment by EricStG** [comment]
Another option would be to allow line breaks or whitespace between each item, this way we can still split it on multiple lines:
```xml
<Exclude>
  [lib]ns1.*,
  [lib]ns2.*
</Exclude>
```

**Comment by MarcoRossignoli** [comment]
> Another option would be to allow line breaks or whitespace between each item, this way we can still split it on multiple lines

Does it works?Have you tried?

**Comment by EricStG** [comment]
It doesn't work, but it should be easy enough to make it work

**Comment by MarcoRossignoli** [comment]
Can you attach the error?Is msbuild error or coverlet error?

**Comment by EricStG** [comment]
Sorry, when I said it doesn't work, I meant the exclusions are not being applied. I can't see any errors in the output.

**Comment by MarcoRossignoli** [comment]
Ah ok... I'll take a look to understand what's going on

**Comment by EricStG** [comment]
I think adding `?.Trim() after the `Split` at https://github.com/tonerdo/coverlet/blob/f24b9d567cb84c314cde46dd336f1919db73c5e4/src/coverlet.collector/DataCollection/CoverletSettingsParser.cs#L130 would do it

**Comment by MarcoRossignoli** [comment]
Yup could work, would you like to offer a PR?
If you don't want no problem, I'll work on it!

**Comment by EricStG** [comment]
I sure can

**Comment by MarcoRossignoli** [comment]
Check here and let me know if something is not clear https://github.com/tonerdo/coverlet/blob/master/CONTRIBUTING.md
