### ISSUE TITLE
How to exclude a website?

### ISSUE THREAD

**Issue by ranouf** [tonerdo/coverlet#665]
Hi,

I have a folder "./src/client/" which is an angular project.
I tried many ways to execute the dotnet test command but I always get the same error:

> Solution file error MSB4249: Unable to build website project "client". The ASP.NET compiler is only available on the .NET Framework version of MSBuild.

Include only the test project.
dotnet test   /p:CollectCoverage=true   /p:CoverletOutputFormat=cobertura /p:Include="[My.*.tests?]*"

Exclude folder client
dotnet test   /p:CollectCoverage=true   /p:CoverletOutputFormat=cobertura /p:ExcludeByFile=\"src/client/**"

How could I exclude the website project "client"?

Thanks

**Comment by MarcoRossignoli** [comment]
Hi Cedric, 

I'm not sure that is an issue related to "coverlet". Coverlet doesn't build project but instrument artifacts generated by compilation(dlls) so I don't know if I can help, it seem something unrelated to instrumentation but related to build. Include/Exclude parameters are only used to include/skip file(dll) from instrumentation.

Let me know if I understood the problem or if you can provide a "small" repro with issue with and without coverlet(/p:CollectCoverage=true/false) could be very useful.

**Comment by MarcoRossignoli** [comment]
@ranouf  any news?
Feel free to close if solved.

**Comment by MarcoRossignoli** [comment]
Close for stale conversation.

Feel free to re-open if needed.
