### ISSUE TITLE
Don't Append Framework to File if -f is Specified

### ISSUE THREAD

**Issue by abbotware** [tonerdo/coverlet#667]
my output file name is being mangled when I specify -f (for framework)

in the below use case it is only running the one framework not multiple

`dotnet test $Source --filter $TestFilter -f $Framework -c $Configuration /p:NetCoreSdk=$NetCoreSdk --logger:"trx;LogFileName=$TrxFile" --results-directory:$TestResultsPath /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$TestResultsPath$CoverageDataFile /p:CollectCoverage=true /p:ExcludeByAttribute="Obsolete%2cGeneratedCodeAttribute%2cCompilerGeneratedAttribute" -nodeReuse:false`

where `$CoverageDataFile=project.Release.linux-x64.netcoreapp3.1.coverage.xml`
and for some reason the output file is actually: 
`project.Release.linux-x64.netcoreapp3.1coverage.netcoreapp3.1.xml.cobertura.xml`

i believe this is related to #636

**Comment by MarcoRossignoli** [comment]
Sorry I meant the coverage issue https://github.com/tonerdo/coverlet/issues/649#issuecomment-568300617 

not the `-f` that isn't a bug, but a correct behaviour

**Comment by MarcoRossignoli** [comment]
The "append file type extension" was fixed in https://github.com/tonerdo/coverlet/pull/668
