### ISSUE TITLE
Enhanced Branch Coverage

### ISSUE THREAD

**Issue by hunterjm** [tonerdo/coverlet#67]
## Expected Result

When running code coverage on a project, all branches in a method will be determined, and their targets will be instrumented.

## Actual Result

Currently, only sequence points that are targets of branches are instrumented.

## Proposed Solution

Implement a branch point/target search using logic similar to [OpenCover.Framework.Symbols.CecilSymbolManager](https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/Symbols/CecilSymbolManager.cs#L421).  This would allow us to:

- Track Branches separately from Sequence Points.
- Instrument all Branch Targets.
- Provide more detailed branch information to the supported reporters.

## Discussion

I've already taken an initial stab at this functionality in my fork and everything seems to be working.  I am in the process of cleaning up the code and adding tests, but wanted to open this issue before opening a PR.

Major high-level changes to the structure are as follows:

- Removed `IsBranchTarget` from `Line` and `LineInfo` as branches are now tracked separately from sequence points.
- Changed `InstrumenterResult`
  - Added `Branch` which extends `Line` and adds additional properties such as `Path`
  - Changed `Document` to have both `Lines` and `Branches`
- Changed `CoverageResult`
  - Updated `Methods` to be a Dictionary with a new class `Method` as the Value
  - `Method` contains `Lines` and `Branches`
- Changed all supporting code (Instrumenter, CoverageSummary, Reporters) to handle the new model structure.

**Comment by tonerdo** [comment]
@hunterjm Thanks for opening this issue and taking a stab at fixing it. I look forward to your PR. Cheers

**Comment by tonerdo** [comment]
New release here: https://www.nuget.org/packages/coverlet.msbuild/2.0.0
