### ISSUE TITLE
Coverlet Console does not work with --filter

### ISSUE THREAD

**Issue by cheenamalhotra** [tonerdo/coverlet#684]
I'm trying to calculate code coverage with Coverlet Console, by using below command:

`coverlet "bin\<path>\Product.dll" --target "dotnet" --targetargs "test src\<path>\Product.Tests.csproj --no-build -v n --filter category!=category1&category!=failing&category!=category3" --output "bin\TestResults" -f cobertura`

Tests run but the filters are not applied even if providing 1 filter at a time, but the same works fine with `dotnet test` command as below:

`dotnet test src\<path>\Product.Tests.csproj --no-build -v n --filter "category!=category1&category!=failing&category!=category3"`

**Comment by MarcoRossignoli** [comment]
Hi Cheena,

can tell me SO?
I did some test on win and I cannot repro the issue.

This is my test, can you try on you side?
[issue_684.zip](https://github.com/tonerdo/coverlet/files/4044952/issue_684.zip)

Is this an open source project that I can debug?

**Comment by MarcoRossignoli** [comment]
Same result on my WSL

**Comment by cheenamalhotra** [comment]
Hi Marco,

I'm a bit surprised this issue isn't happening again, I'm also running on Windows.
But thanks for the repro and looking into it. I'll reach back if I see this issue again!

**Comment by MarcoRossignoli** [comment]
Keep this open until we'll be sure that is not a coverlet issue, my experience on this stuff teached me that small difference could be great one :smiley:

**Comment by MarcoRossignoli** [comment]
Ops sorry misread is instead of isn't!

Feel free to re-open if needed!
