### ISSUE TITLE
Simple `if` expression coverage not recorded in some cases

### ISSUE THREAD

**Issue by SteveGilham** [tonerdo/coverlet#690]
This is another change in behaviour observed when upgrading the collector to v1.2, but I don't have a simple cut-down version of this -- it stops when I remove any significant amounts of code.

Consider [this function](https://github.com/SteveGilham/altcover/blob/221a60bed4c5d73b58103395de58231da8eb72f9/AltCover.Recorder/Base.fs#L156-L159)
```
  let internal MinTime (t1:DateTime) (t2:DateTime) =
    if t1 < t2
    then t1
    else t2
```
with [unit tests](https://github.com/SteveGilham/altcover/blob/221a60bed4c5d73b58103395de58231da8eb72f9/Tests/Runner.Tests.fs#L48-L58)
```
    [<Test>]
    let MinTimeFirst () =
      let now = DateTime.Now
      let ago = now - TimeSpan(1,0,0,0)
      test <@ (Base.Counter.Uncoverlet.MinTime ago now) = ago @>

    [<Test>]
    let MinTimeLast () =
      let now = DateTime.Now
      let ago = now - TimeSpan(1,0,0,0)
      test <@ (Base.Counter.Uncoverlet.MinTime now ago) = ago @>
```
One would expect this to give 100% line and branch coverage, and indeed it does when stripped down anywhere close to just this part of the code, or when the previous version of the collector is used.

In the full context, for some reason, the `then` branch never shows as covered.

The code decompiles to
```
internal DateTime MinTime (DateTime t1, DateTime t2)
{
  if (LanguagePrimitives.HashCompare.GenericLessThanIntrinsic(t1, t2))
  {
    return t1;
  }
  return t2;
}
```
I have two other examples, one the obvious `MaxTime` counterpart, and [the other](https://github.com/SteveGilham/altcover/blob/221a60bed4c5d73b58103395de58231da8eb72f9/AltCover/Visitor.fs#L238-L243) 
```
  let Sampling() =
    let sampling () =
      if single
      then Base.Sampling.Single
      else Base.Sampling.All
    () |> sampling |> int
```
with similarly [exhaustive test](https://github.com/SteveGilham/altcover/blob/221a60bed4c5d73b58103395de58231da8eb72f9/Tests/Tests.fs#L788-L797)
```
    [<Test>]
    let CanSwitchSampling() =
      let save = Visitor.single
      try
        Visitor.single <- true
        test <@ Visitor.Sampling() = 1 @>
        Visitor.single <- false
        test <@ Visitor.Sampling() = 0 @>
      finally
        Visitor.single <- save
```
Again, in both cases, the `then` path is not recorded.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this

**Comment by SteveGilham** [comment]
False alarm -- while trying to cut this down to a simple repro today, I spotted the subtle mistake I'd made.

**Comment by MarcoRossignoli** [comment]
Thank's for the investigation!
