### ISSUE TITLE
Zero Coverage Reported coverlet.msbuild

### ISSUE THREAD

**Issue by przerull** [tonerdo/coverlet#717]
So I run

`dotnet test /p:CollectCoverage=true /p:CoverletOutput=./coverage_report/raw_coverage_results.xml /p:CoverletOutputFormat=cobertura`

I see that my tests ran successfully

```
Test run for C:\blahblah\Test\bin\Debug\netcoreapp3.0\Test.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 28
     Passed: 28
 Total time: 1.4392 Minutes

Calculating coverage result...
  Generating report '.\coverage_report\raw_coverage_results.xml'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+
```

But my resulting file (.\coverage_report\raw_coverage_results.xml) ends up having no information. Just the following:

```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1580346044" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

Here's my result of `dotnet list package`

```
Project 'Test' has the following package references
   [netcoreapp3.0]:
   Top-level Package                                Requested   Resolved
   > coverlet.msbuild                               2.8.0       2.8.0
   > Microsoft.NET.Test.Sdk                         16.4.0      16.4.0
   > nunit                                          3.12.0      3.12.0
   > NUnit3TestAdapter                              3.13.0      3.13.0
   > System.Configuration.ConfigurationManager      4.5.0       4.5.0
   > System.Json                                    4.5.0       4.5.0
```

I have a feeling this may have to do with me upgrading to .net core 3.0.   I was previously running my main application under the .net framework version 4.7.2 and I was getting coverage results back then.

Any help would be greatly appreciated.

**Comment by MarcoRossignoli** [comment]
Maybe you're hitting https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#1-vstest-stops-process-execution-earlydotnet-test
Can you try to use collectors https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md?

**Comment by przerull** [comment]
Hey thanks for the quick response.

I attempted to use collectors by installing coverlet.collector then running `dotnet test --collect:"XPlat Code Coverage"`

The xml file was produced in the TestResults\guid folder but it had the same results as when I used coverlet.msbuild.

I also updated Microsoft.NET.Test.Sdk to 16.5.0-preview-20200116-01 and still got the same result

```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1580398604" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

**Comment by MarcoRossignoli** [comment]
Can you share a repro?Or project is on github?

**Comment by MarcoRossignoli** [comment]
You can try to enable logs and check if the lib you want to instrument is skipped for some reason https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration

**Comment by przerull** [comment]
Ah the log.datacollector.datetimestamp.txt file appears to provide some useful information.

I filtered out for coverlet messages, and only included the ones I thought were immediately relevent

```
TpTrace Information: 0 : 5108, 1, 2020/01/30, 10:52:25.617, 684066289697, datacollector.dll, [coverlet]Initializing CoverletCoverageDataCollector with configuration: '<Configuration><Framework>.NETCoreApp,Version=v3.0</Framework></Configuration>'
TpTrace Verbose: 0 : 5108, 1, 2020/01/30, 10:52:25.618, 684066298348, datacollector.dll, [coverlet]CoverletCoverageDataCollector: SessionStart received
TpTrace Information: 0 : 5108, 1, 2020/01/30, 10:52:25.618, 684066302637, datacollector.dll, [coverlet]CoverletCoverageDataCollector: TestModules: 'C:\blahblah\Test\bin\Debug\netcoreapp3.0\Test.dll'
TpTrace Verbose: 0 : 5108, 1, 2020/01/30, 10:52:25.621, 684066330882, datacollector.dll, [coverlet]CoverletCoverageDataCollector: Initializing coverlet process with settings: "TestModule: 'C:\blahblah\Test\bin\Debug\netcoreapp3.0\Test.dll', IncludeFilters: '', IncludeDirectories: '', ExcludeFilters: '[coverlet.*]*', ExcludeSourceFiles: '', ExcludeAttributes: '', MergeWith: '', UseSourceLink: 'False'SingleHit: 'False'IncludeTestAssembly: 'False'"
TpTrace Verbose: 0 : 5108, 1, 2020/01/30, 10:52:25.658, 684066700672, datacollector.dll, [coverlet]Excluded module filter '[coverlet.*]*'
TpTrace Verbose: 0 : 5108, 1, 2020/01/30, 10:52:25.701, 684067125179, datacollector.dll, [coverlet]Unable to instrument module: C:\blahblah\Test\bin\Debug\netcoreapp3.0\assembly_im_trying_to_test.dll, pdb without local source files, [C:\blahblah\assembly_im_trying_to_test\obj\Debug\netcoreapp3.0\Common.cs]
TpTrace Verbose: 0 : 5108, 1, 2020/01/30, 10:53:52.705, 684937168811, datacollector.dll, [coverlet]CoverletCoverageDataCollector: SessionEnd received
```

Now in the root folder of the project of the assembly I'm trying to test, there is a common.cs file (lower cased).  It's interesting that the c# files which weren't generated due to use of xaml don't appear to have been copied to the obj folder at build time.

**Comment by MarcoRossignoli** [comment]
you need to skip that source from coverage like https://github.com/tonerdo/coverlet/issues/714#issuecomment-579704498

**Comment by przerull** [comment]
Ah, thanks again for the help.  You're doing an outstanding job supporting this tool.

I reviewed the code and yes, my common.cs file uses [Fody/PropertyChanged](https://github.com/Fody/PropertyChanged), which injects code into some of the classes in that file to deal with OnPropertyChanged events, making it autogenerated.

It makes perfect sense. Trying to measure coverage on code which gets modified dynamically prior to compilation is a quixotic task.  Thank you so much for helping me come to this conclusion.

**Comment by MarcoRossignoli** [comment]
Glad to hear! thanks for using coverlet!
