### ISSUE TITLE
BUG: (Completely) Missing Coverage

### ISSUE THREAD

**Issue by nopara73** [tonerdo/coverlet#72]
Maybe related: https://github.com/tonerdo/coverlet/issues/39

# Behavior.

![image](https://user-images.githubusercontent.com/9156103/39472085-3d11d312-4d71-11e8-8765-549932ddbd8d.png)

# What I do

1. Add coverlet.msbuild NuGet to my test project.
2. Run Tor (needed for my tests to successfully complete.)
3. Run `dotnet test /p:CollectCoverage=true`.  

I also tried creating a new project and everything works fine, however with my current project (https://github.com/zkSNACKs/WalletWasabi/) it silently fails.

**Comment by nopara73** [comment]
Note: Neither the `coverage.xml`, nor the `coverage.json` files are generated.

**Comment by nopara73** [comment]
And travis (both on Linux and OSX) is even stranger:

https://travis-ci.org/zkSNACKs/WalletWasabi/jobs/373441646
https://travis-ci.org/zkSNACKs/WalletWasabi/jobs/373441646

![image](https://user-images.githubusercontent.com/9156103/39472792-b15a7a86-4d75-11e8-9b39-5b61d5e757f1.png)

**Comment by nopara73** [comment]
For the record, here are the commands for only doing one file.

```
dotnet restore && dotnet build && cd WalletWasabi.CodeCoverage
dotnet minicover instrument --workdir . --assemblies ../WalletWasabi.Tests/bin/**/*.dll --sources ../WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
dotnet minicover reset
cd ../WalletWasabi.Tests && dotnet test --no-build
cd ../WalletWasabi.CodeCoverage
dotnet minicover uninstrument --workdir .
dotnet minicover report --workdir . --threshold 50
```

**Comment by tonerdo** [comment]
Thanks for reporting this. I'll take a look at your sample project and see if I can figure it out

**Comment by nopara73** [comment]
@tonerdo Thanks! I put together some build instructions for Windows so to not get stuck:

1. Get .NET Core
2. Download the Tor Experd Bundle (Not the browser.) https://www.torproject.org/download/download
3. Run `tor.exe`
4. Fire up command line:
```
git clone https://github.com/zkSNACKs/WalletWasabi
cd WalletWasabi
dotnet restore && dotnet build
cd WalletWasabi.Tests
dotnet test
```

Notes:

1. `dotnet test` takes about 3 minutes, the first time it'll take 1-2 minutes longer, because it downloads `bitcoind`. This daemon is used by the tests in regression test mode to simulate the Bitcoin network.  

2. Tests are using `%appdata%\WalletWasabi` folder to log and for other things, so you can delete it after you no longer wish to do anything with the software anymore.

**Comment by SteveGilham** [comment]
Having tried this, the first obvious problem is that there's an assembly being (indirectly) referenced that's in ~/.nuget, but is not copied locally.  That manifests as an assembly resolution failure when trying to write an instrumented assembly -- the process then just carries on obliviously.+
```
05/04/2018 07:52:09>dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
Build started, please wait...
Build completed.

Test run for C:\Users\steve\Documents\GitHub\WalletWasabi\WalletWasabi.Tests\bin\Debug\netcoreapp2.0\WalletWasabi.Tests.dll(.NETCoreApp,Version=v2.0)
C:\Users\steve\.nuget\packages\coverlet.msbuild\1.2.0\build\netstandard2.0\coverlet.msbuild.targets(14,5): error : Failed to resolve assembly: 'NBitcoin, Version=4.1.1.3, Culture=neutral, PublicKeyToken=null' [C:\Users\steve\Documents\GitHub\WalletWasabi\WalletWasabi.Tests\WalletWasabi.Tests.csproj]
```

**Comment by nopara73** [comment]
@SteveGilham I actually tried it. Copying the assembly manually only solved the problem in `altcover`, but not in `coverlet`, it still silently fails.

**Comment by pwelter34** [comment]
My project is also not getting code coverage results.  Its not covering all the dependent assemblies.  My project is located here.  https://github.com/loresoft/FluentCommand

Is there a way to setup debug local?

**Comment by Drag13** [comment]
I think I have related bug. On Windows all is ok, but on Linux with Travis I have 0 coverage report. 

```cmd
dotnet build CIDemo.sln -c Release
dotnet test -c Release test/test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
```

<img width="377" alt="0coverage" src="https://user-images.githubusercontent.com/8222114/40217420-4f9e3c9e-5a75-11e8-9e81-54b1ba48a2b3.PNG">

Any idea?

PackageReference Include="coverlet.msbuild" Version="2.0.0"
[Demo repository](https://github.com/Drag13/CIDemo/tree/AddCoverageBadge)
[Travis report](https://travis-ci.org/Drag13/CIDemo/builds/380537670)

**Comment by Drag13** [comment]
Downgrading to 1.2.0 Fixed problem. But for 2.0 it still exists

**Comment by coenm** [comment]
I'm experiencing the same issue. 

2.0 -> Travis = no coverage
2.0 -> Local windows => has coverage
1.2 -> Travis => has coverage

**Comment by n00j** [comment]
Have you tried adding the following to your test.csproj? 
```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
I was running into problems with coverlet not being able to locate dll's and seems to fix it.

**Comment by varsnotwars** [comment]
@nopara73, this works correctly now after adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` 
Thanks @n00j 👍

**Comment by n00j** [comment]
@varnotwars no problem! It would be useful if this was added to the documentation as I believe it solves a lot of the 0% coverage issues and errors

**Comment by tonerdo** [comment]
Will keep this open until I add it to the documentation, thanks @n00j

**Comment by asbjornu** [comment]
Just as a FYI, [my test project](https://github.com/linked-data-dotnet/json-ld.net/blob/feature/travis/test/json-ld.net.tests/json-ld.net.tests.csproj#L9) is `netcoreapp2.1` and has `CopyLocalLockFileAssemblies` set to `true`, but `dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover` still produces no code coverage file on disk.

**Comment by abhurtun** [comment]
the same as @asbjornu no code coverage 👎

**Comment by abhurtun** [comment]
I found out if you run in Release mode is doesn't cover all the dlls but if you do Debug it works

**Comment by nopara73** [comment]
@asbjornu @abhurtun Neither the trick works for us anymore.

**Comment by asbjornu** [comment]
I can't remember exactly what I did, but [I managed to generate a code coverage report and upload it to Codecov](https://codecov.io/gh/linked-data-dotnet/json-ld.net/branch/feature%2Ftravis) in linked-data-dotnet/json-ld.net#38.

**Comment by nopara73** [comment]
Also it might be helpful for someone who's looking at this issue for alternative's: @SteveGilham's altcover is still working for .NET Core projects. It's less straightforward to use but at least it works:

Install `altcover` NuGet to the `WalletWasabi.Tests` project and Coverage Glutters extension to vscode.

```sh
dotnet build
dotnet C:\Users\user\.nuget\packages\altcover\5.0.663\tools\netcoreapp2.0\altcover.dll --save --inplace "-i=bin\Debug\netcoreapp2.2"
dotnet test
dotnet C:\Users\user\.nuget\packages\altcover\5.0.663\tools\netcoreapp2.0\altcover.dll runner --collect "-r=bin\Debug\netcoreapp2.2" "-l=lcov.info"
```

Run vscode and click on "Watch":

![](https://i.imgur.com/W4hXXda.png)

**Comment by SteveGilham** [comment]
Just interjecting to remark that doing 
```
dotnet test /p:AltCover=true /p:AltCoverLcovReport=lcov.info
```
to have the same effect has been supported since early last summer.

**Comment by MarcoRossignoli** [comment]
Hi guys I saw a lot of activity on this issue..I would like to know if this issue is still relevant, if so I would like to repro on my local and in case fix or update documentation accordingly.
Do you have some repro that still fails?

**Comment by MarcoRossignoli** [comment]
close for stale...further discussion on similar issue https://github.com/dotnet/cli/issues/12705#issuecomment-535150372
With 3.0 all assets will be copied so should resolve by design this issue...for shared framework at the moment we don't have an elegant solution, only manually copy dll to output folder https://github.com/dotnet/cli/issues/12705#issuecomment-536686785

**Comment by PSanetra** [comment]
We are still facing this issue. The workarounds mentioned here did not help.

**Comment by MarcoRossignoli** [comment]
@PSanetra can you file an new issue with you case?
