### ISSUE TITLE
Coverage exclusion does not seem to work :(

### ISSUE THREAD

**Issue by svenskmand** [tonerdo/coverlet#722]
Hi :)

I cannot get coverage exclusion as described [here](https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage) to work. If I include the `ExcludeByAttribute` property in my `*.Tests.csproj` file and add a property `GeneratedCode` to my generated code project then Coverlet still computes coverage for the generated code. Similarly if I add the property `ExcludeFromCoverage` or `ExcludeFromCodeCoverage` to my generated code project, coverage is again still computed for the project.

Here is my `*.Tests.csproj` file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>lcov</CoverletOutputFormat>
    <CoverletOutput>./Datahub/lcov.info</CoverletOutput>
    <ExcludeByAttribute>GeneratedCode</ExcludeByAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="2.8.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.collector" Version="1.0.1" />
    <PackageReference Include="FluentAssertions" Version="5.10.0" />
  </ItemGroup>

  <ItemGroup>
    ... project references ...
  </ItemGroup>
</Project>
```

and here is my `ProtoBuf.csproj` file for the generated code:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GeneratedCode>GeneratedCode</GeneratedCode>
    <ExcludeFromCoverage/>
    <ExcludeFromCodeCoverage/>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.11.2" />
    <PackageReference Include="Grpc" Version="2.26.0" />
    <PackageReference Include="Grpc.Tools" Version="2.26.0" PrivateAssets="All">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="**/*.proto" />
  </ItemGroup>
</Project>
```

Am I missing something or what is wrong?

Thanks :)

**Comment by MarcoRossignoli** [comment]
>  file and add a property GeneratedCode

What do you mean for "property"?

>  my generated code project

Do you want to skip coverage for all compiled assembly?I mean you generate all code of one project and you want to exlude that lib(generated.dll) from coverage?

**Comment by svenskmand** [comment]
I have a project that only consists of files generated from a ProtoBuf speciation. I want to exclude that project from code coverage. I tried doing that by adding properties/attributes to the `PropertyGroup` partb of my `ProtoBuf.csproj` file. Unfortunately none of my attempts worked. The way I am reading the documentation I am doing it correctly, or can you see what I am doing wrong?

**Comment by MarcoRossignoli** [comment]
> I have a project that only consists of files generated from a ProtoBuf speciation.

If you want to exclude all project(generated.dll) you can simply add an assembly level attribute(you create a custom file and add to it, will be compiled) `System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage` like in our test sample https://github.com/tonerdo/coverlet/blob/master/test/coverlet.tests.projectsample.excludedbyattribute/SampleClass.cs 

Coverlet will skip to instrument that assembly.

**Comment by MarcoRossignoli** [comment]
You don't have to update csproj for the dll `ProtoBuf.csproj`, so remove 

```xml
 <ExcludeFromCoverage/>
 <ExcludeFromCodeCoverage/>
```

Coverlet get parameters from console `/p:...` or from test csproj.

BTW I advice to use collectors integration https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md  
This doesn't change the `System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage` story, will work in the same way.

**Comment by svenskmand** [comment]
Ok, cool I will try that. I am not very familiar with MSBuild, so from the documentation I throught I should add a property to my MSBuild project file since the documentation was already taking about passing properties to MSBuild when calling `dotnet test` to exclude stuff from having coverage measured.

**Comment by MarcoRossignoli** [comment]
No worries, let me know...you can check our hello word samples https://github.com/tonerdo/coverlet/tree/master/Documentation/Examples

If your project is oss I can land on your repo and take a look.

**Comment by MarcoRossignoli** [comment]
Feel free to ask I'll drive you to goal.

**Comment by svenskmand** [comment]
I now added a file `coverage.cs` to my ProtoBuf project with the following content:
```
using System.Diagnostics.CodeAnalysis;

[assembly: ExcludeFromCodeCoverage]
```
and now that project is not included in the coverage :) Thanks for the help :D

I think that it would clear up the [documentation](https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage), if a more explicit explanation is added for how to ignore a class/module/assembly. I misunderstood C# attributes with MSBuild properties so I guess others could also do that :)

**Comment by MarcoRossignoli** [comment]
Glad to head!
Thank you for the advice.

Feel free to close if solved!

**Comment by svenskmand** [comment]
I just want to give a small update to this that I just discovered. You do not have to create a C# file with the attribute above, the same thing can be done in the `csproj` file like this:
```
<Project Sdk="Microsoft.NET.Sdk">
    <!-- ... -->
    <ItemGroup>
        <!-- ... -->
        <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage"/>
    </ItemGroup>
</Project>
```

**Comment by MarcoRossignoli** [comment]
Oh yes you're right!
