### ISSUE TITLE
Lambdas in a method marked ExcludeForCodeCoverage are showing up in report

### ISSUE THREAD

**Issue by acgritt** [tonerdo/coverlet#724]
**Issue:**
Code that is in a function that has the `[ExcludeFromCodeCoverage]` attribute but contains a lambda is getting picked up in the coverage when it should not be due to the attribute.

![image](https://user-images.githubusercontent.com/10471937/74043382-e25ab300-498e-11ea-82fa-84b7398e0135.png)

**Toolset:**
- .NET Core: 3.1
- Coverlet.Collector: 1.2.0
- ReportGenerator: 4.4.6
- Command: `dotnet test --collect:"XPlat Code Coverage" --settings code-coverage.runsettings`

**code-coverage.runsettings**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute</ExcludeByAttribute>
          <SingleHit>false</SingleHit>
          <UseSourceLink>true</UseSourceLink>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

**Comment by MarcoRossignoli** [comment]
Should be fixed on master, can you try with our nightly build https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md?

**Comment by MarcoRossignoli** [comment]
cc: @matteoerigozzi

**Comment by matteoerigozzi** [comment]
I agree. Should be fixed

**Comment by acgritt** [comment]
The nightly build does fix the issue.

**Comment by acgritt** [comment]
@MarcoRossignoli Any idea when a build with this fix will be pushed to NuGet?

**Comment by MarcoRossignoli** [comment]
We should release at end of month https://github.com/tonerdo/coverlet/blob/master/Documentation/ReleasePlan.md#release-calendar
