### ISSUE TITLE
Code coverage stops working with SSL enabled RabbitMQ

### ISSUE THREAD

**Issue by dozer75** [tonerdo/coverlet#737]
I have a strange situation when using the coverlet in a project together with RabbitMQ, it simply stops working and no code coverage information is returned at all when RabbitMQ is initialized.

I have stripped down my code to what's needed to reproduce the issue, and this is attached as a zip file [here](https://github.com/tonerdo/coverlet/files/4224272/test.zip).

To be able to run this example, you’ll need to have a SSL enabled RabbitMQ service. This Docker command will start a RabbitMQ with SSL support and self-signed certificates:

`docker run -it --rm --hostname test-rabbit --name test-rabbitmq -p 15671:15671 -p 5671:5671 -v <path to certs>:/rabbit-certs -e RABBITMQ_SSL_CACERTFILE=/rabbit-certs/ca_certificate.pem -e RABBITMQ_SSL_CERTFILE=/rabbit-certs/server_certificate.pem  -e RABBITMQ_SSL_KEYFILE=/rabbit-certs/server_key.pem -e RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=false -e RABBITMQ_SSL_VERIFY=verify_none -e RABBITMQ_CTL_ERL_ARGS="-proto_dist inet_tls" rabbitmq:3-management`

Replace `<path to certs>` with the path of the certificates available in the certs folder in the project.

When the RabbitMQ is up a running, extract the zip file and run `dotnet test Logic.IntegrationTest.csproj /p:CollectCoverage=true` and the code coverage shows 0%. Comment the line `LogicExtensions.cs:22` and it will show the correct code coverage (100%).

I have tried to trace the usage of the SSL configuration on `LogicExtensions.cs:22` to see what it does, but it’s far down in some `SslStream` class in the .NET Core framework.

I really need this to work to get an effective code coverage of my solution.

**Comment by MarcoRossignoli** [comment]
You're probably hitting a know issue you should try to use collectors check here https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#1-vstest-stops-process-execution-earlydotnet-test
vstest integration https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by dozer75** [comment]
Thanks, for the answer and it seems to work. 

However, my problem is then that today I use a script that merges several code coverage results for different test project and uses reportgenerator to display the result (Based on this example: https://gist.github.com/lira92/29aca1c01661a8de30890a6538c0ba5c).

So, how can I do anything similar by using `dotnet test --collect:"XPlat Code Coverage"`? Can't find any documentation about any merge logic?

**Comment by dozer75** [comment]
I found a solution by adjusting the -reports parameter of reportgenerator. Closing this issue since it's known and it has a workaround that is acceptable for me.

**Comment by MarcoRossignoli** [comment]
Yep sorry for late reply, reportgenerator as you saw can picks up more reports and merge together thanks to @danielpalme!
