### ISSUE TITLE
Incorrectly partially covered method line

### ISSUE THREAD

**Issue by tbeswick96** [tonerdo/coverlet#739]
Coverlet is reporting a method line (not first line of method, but the actual method line itself, although it did previously do that) as partially covered.

Versions:
```
dotnetcore: 3.1
Microsoft.NET.Test.Sdk: 16.5.0
coverlet.collector: 1.2.0
coverlet.msbuild: 2.8.0
xunit: 2.4.1
```

I'm running my code coverage locally with:
`dotnet test ./UKSF.Api.sln /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info /p:Exclude="[UKSF.Api.Signalr]*%2c[UKSF.PostMessage]*"`

And then I generate an html report with ReportGenerator.

The report shows the same result in coveralls, so I know this isn't a ReportGenerator issue.

<details>
<summary>My report shows this</summary>

![image](https://user-images.githubusercontent.com/11049179/74869459-e5bb4a80-534f-11ea-85fc-185f007f632e.png)

</details>

And the yellow lines report: 
`Partially covered (x visits, 1 of 2 branches are covered)`

I was previously having this same issue but it was actually reporting the first line, regardless of the code, as the partially covered line. I browsed some issues here and changed the test to use debug build instead and this is what it now reports.
For example even with a handful of console writelines as the first few lines of each method, the first one was always reported as partially covered.

<details>
<summary>That looked like this</summary>

![image](https://user-images.githubusercontent.com/11049179/74870494-b9a0c900-5351-11ea-9d25-e67dcb6ff2b1.png)

</details>

Am I missing something here? Perhaps to do with the async method? This is strange because I have other tests that cover other async methods that don't report this at all. It is so far just this class that has this issue.

**Comment by MarcoRossignoli** [comment]
Can you try with master version?We fixed some coverage issue in these weeks, please try with our nightly build https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by tbeswick96** [comment]
Thanks that has worked
No longer reporting partially covered in both Debug and Release configurations

**Comment by MarcoRossignoli** [comment]
Glad to head!Feel free to use nightly, this version will be released and the end of March as planned https://github.com/tonerdo/coverlet/blob/master/Documentation/ReleasePlan.md#release-calendar

Feel free to close this if solved!

**Comment by tbeswick96** [comment]
Thanks for your help!
