### ISSUE TITLE
Question about excluding strategy

### ISSUE THREAD

**Issue by suadev** [tonerdo/coverlet#743]
Hi,

It look like coverlet exclude enums, html files, classes that  consist of only const strings(like Constants.cs)   etc..  

I wanted to see whole excluded list but could not able to find.  

Also, how coverlet exclude .html files from code coverage? I could not find related code. 

Thanks.

**Comment by MarcoRossignoli** [comment]
> Also, how coverlet exclude .html files from code coverage? I could not find related code.

Coverlet is a code coverage tool only for .NET IL, so for instance for a asp.net project it can only instrument and cover main dll assembly generated

> It look like coverlet exclude enums, html files, classes that consist of only const strings(like Constants.cs) etc..
I wanted to see whole excluded list but could not able to find.

Can you provide a repro?As I said above that cs files will be compiled inside a dll(in form of IL, intermediate language) so should be covered if used by tests

**Comment by suadev** [comment]
@MarcoRossignoli 

Under src/Common folder there is a folder named 'Mail' that include 2 interfaces, 1 enum (EmailType.cs) and 2 classes. (first image)

But in the opencover xml, i see only two .cs files. (second image). 

So, interfaces and enum types are excluded by coverlet?


![image](https://user-images.githubusercontent.com/5918811/75579271-7a235c80-5a76-11ea-95d6-76c242643c82.png)

![image](https://user-images.githubusercontent.com/5918811/75579405-c7073300-5a76-11ea-8274-c25045c084a9.png)

**Comment by MarcoRossignoli** [comment]
I think it's correct...you cannot cover "interface" but only code that uses interface...interface doesn't have code, or do you have default interface implementation(https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions(?

**Comment by suadev** [comment]
Interfaces and enums should be excluded, i am ok with that. I just wanted to know how coverlet do this. I mean, i was expecting to see a 'excluded stuff lists' in the code. But i could not find it in source code of coverlet. How coverlet exclude enums?

**Comment by suadev** [comment]
Between, i do not have default implementation of theses interfaces.

**Comment by MarcoRossignoli** [comment]
> I just wanted to know how coverlet do this.

Coverlet instruments branches and sequence point...enum and interface doesn't have branch/sequence point(that are described inside pdb) so coverlet cannot instrument these members.
After instrumentation and tests run coverlet gather and persist hits to file, hits are "place where your test run is passsed" and we do a match between this point and branches/sequence point.
This is how coverlet works https://github.com/tonerdo/coverlet#how-it-works

**Comment by suadev** [comment]
@MarcoRossignoli thank you for you time!

**Comment by MarcoRossignoli** [comment]
You're welcome!

Feel free to close this issue if solved.
