### ISSUE TITLE
[ExcludeFromCodeCoverage] attribute does not work on methods

### ISSUE THREAD

**Issue by ssztangierski** [tonerdo/coverlet#746]
Hi,

I've been struggling with adding `[ExcludeFromCodeCoverage] ` attribute . For some reason, coverlet ignores it when I decorate any method for exclusion. However, it seems to be working fine when I add it to a class. I've created a project on github that reproduces this issue.

https://github.com/ssztangierski/coverlet-exclude-attribute

command when I run test from "WeatherControllerTests" folder:  

`dotnet test WeatherController.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura`

I'd like to exclude `CreateHostBuilder `method from `Program.cs`
Is this intended or am I doing something wrong? There is also   coverage.cobertura.xml file in the repo.

```
  <class name="CoverageTest.Program/&lt;&gt;c" filename="Program.cs" line-rate="0" branch-rate="1" complexity="1">
          <methods>
            <method name="&lt;CreateHostBuilder&gt;b__1_0" signature="(Microsoft.AspNetCore.Hosting.IWebHostBuilder)" line-rate="0" branch-rate="1">
              <lines>
                <line number="25" hits="0" branch="False" />
                <line number="26" hits="0" branch="False" />
                <line number="27" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="25" hits="0" branch="False" />
            <line number="26" hits="0" branch="False" />
            <line number="27" hits="0" branch="False" />
          </lines>
        </class>
```

**Comment by MarcoRossignoli** [comment]
Hi @ssztangierski can you try with nightly build?We fixed some similar bug recently and maybe we've the soluton ready on master https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by MarcoRossignoli** [comment]
cc: @matteoerigozzi

**Comment by ssztangierski** [comment]
Hi @MarcoRossignoli, it does work like it should with nightly build. Could you please tell me when can I expect nightlybuild to be officially released?

**Comment by MarcoRossignoli** [comment]
1 April more or less https://github.com/tonerdo/coverlet/blob/master/Documentation/ReleasePlan.md

**Comment by MarcoRossignoli** [comment]
Feel free to close this issue.

**Comment by ssztangierski** [comment]
Thanks a lot!

**Comment by MarcoRossignoli** [comment]
FYI current changelog https://github.com/tonerdo/coverlet/blob/master/Documentation/Changelog.md
