### ISSUE TITLE
Support for generating multiple output formats from single test run

### ISSUE THREAD

**Issue by patros** [tonerdo/coverlet#75]
The back story to this is that I use VSTS for builds. There is out of the box functionality for reporting code coverage totals in the build summary when using the cobertura format. However I'd also like to use the tool [fdesjardins/coverage-viewer](https://github.com/fdesjardins/coverage-viewer) to generate a nice html report and it requires the standard json output.

I'm happy to do some work in this space but before I start I wanted to see what your opinion was on this.

I figure a nice way to access this functionality would be to allow comma separated values for CoverletOutputFormat. So in my case that would look like `/p:CoverletOutputFormat=json,cobertura`.

Looking at the code it should be pretty straight forward to implement.

**Comment by patros** [comment]
@tonerdo you're welcome. I have a pending pull request with fdesjardins to add support for Windows (and a couple of other minor issues), but short of that it's pretty good.

**Comment by tonerdo** [comment]
@patros all merge in!

**Comment by tonerdo** [comment]
New release here: https://www.nuget.org/packages/coverlet.msbuild/2.0.0
