### ISSUE TITLE
Code coverage by each file

### ISSUE THREAD

**Issue by sachithanandhampalaniswamy** [tonerdo/coverlet#756]
Request code coverage by each file name , this will help a lot

**Comment by MarcoRossignoli** [comment]
> Request code coverage by each file name , this will help a lot

Do you mean file filter like `ExcludeByFile` but for inclusion?

**Comment by sachithanandhampalaniswamy** [comment]
Can you show code coverage by file like NPM or yarn does please.

**Comment by MarcoRossignoli** [comment]
Ah ok now I understand what you mean, coverlet goal is to generate a coverage file is not a coverage report tool for that functionality there are better tool for instance:

ReportGenerator(my choice) https://github.com/danielpalme/ReportGenerator
https://coveralls.io/
https://codecov.io/

and other.
