### ISSUE TITLE
Code of Conduct is missing email address

### ISSUE THREAD

**Issue by senox13** [tonerdo/coverlet#758]
As the title says, the file `CODE_OF_CONDUCT.md` is missing the contact email of the project team in the second to last section, titled Enforcement. The first paragraph still has the placeholder `[INSERT EMAIL ADDRESS]` from the Contributor Covenant template.

**Comment by MarcoRossignoli** [comment]
Thank's for reporting this.

Hi @senox13 at the moment we don't have a team mail.
Ask to @tonerdo(owner) what he thinks about.

@senox13 if you need to report something important in private mode feel free to contact me with twitter DM or gitter private chat.

**Comment by clairernovotny** [comment]
CoC links shoiuld all go to the .NET Foundation conduct@dotnetfoundation.org.

**Comment by MarcoRossignoli** [comment]
Thanks Claire!
