### ISSUE TITLE
Branch coverage is not completely exported in OpenCover format

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [tonerdo/coverlet#769]
When using the **OpenCover** format (`--format opencover`) the `bec` (branch exit count) and `bev` (branch exit visits) are not populated and this will prevent other tools to properly read the branch coverage details.

**Current behavior:**

As far as I can tell these are hard-coded to `0`: https://github.com/tonerdo/coverlet/blob/0cc2548b27c6d7f030095d40d81517d4457fcc80/src/coverlet.core/Reporters/OpenCoverReporter.cs#L124

**Expected behavior:**

`bec` and `bev` are contain the branch exit counts and visits.

**Comment by MarcoRossignoli** [comment]
Hi Costin, I didn't work on open cover report so at the moment I'm not an expert on the format, can you link some guide on these fields, the meaning?
If you already know how to fix feel free to propose a PR!

**Comment by costin-zaharia** [comment]
Hi @MarcoRossignoli 

You can find my PR here: https://github.com/tonerdo/coverlet/pull/772

As far as I can tell OpenCover doesn't have documentation for their format but the code provides a lot of details 😄. 

The code for the model which gets serialized can be found here: https://github.com/OpenCover/opencover/blob/94c7e572a907ac1873b8f48324d0cbc0cf1e7456/main/OpenCover.Framework/Model/SequencePoint.cs#L49
