### ISSUE TITLE
Adding a Filter property to include/exclude assemblies/types

### ISSUE THREAD

**Issue by MarcoRossignoli** [tonerdo/coverlet#77]
# Rationale

Coverlet currently allow to ignore methods/classes using [attribute](https://github.com/tonerdo/coverlet#excluding-from-coverage) or specific source files using [/p:Exclude](https://github.com/tonerdo/coverlet#source-files) property.

It would be useful filter(include/exclude) assembly/types in a "similar" way of popular [OpenCovers](https://github.com/opencover/opencover/wiki/Usage#understanding-filters) framework.

# Proposal

Some examples

To Include assembly but exclude all classes of particular namespace.
``` 
dotnet test /p:CollectCoverage=true /p:Filter="+[AssemblyName] -[AssemblyName]Namespace.*"
```
To include only one class
```
dotnet test /p:CollectCoverage=true /p:Filter="+[AssemblyName]Namespace.ClassName"
```

To include all classes ends with "ClassNameSuffix" of AssemblyName
```
dotnet test /p:CollectCoverage=true /p:Filter="+[AssemblyName]*ClassNameSuffix"
```

# Details

Filters can be inclusive and exclusive represented by + and – prefix respectively, where exclusive (-) filters take precedence over inclusive (+) filters.
Assembly here is like a module, 99.9% we have a [single file assembly](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-build-a-single-file-assembly).

# Open Questions

* Add also `/Include=[*]*`, does it make sense?

cc: @tonerdo @abe545  @ido-namely @ryanmvt @coenm @mathnogueira

**Comment by MarcoRossignoli** [comment]
I'll keep issue updated with our discussion!

**Comment by tonerdo** [comment]
I intend to look into this over the weekend

**Comment by MarcoRossignoli** [comment]
Copied from [Merged PR](https://github.com/tonerdo/coverlet/pull/94#issuecomment-388748476) comments for clarity:

I'm thinking maybe we could have also an /Include= and say that default for coverlet if attributes are missing is /Include=[*]* this could address one of my coverage scenario where i need to be sure that only 2/3 of my tens of class are covered for > 95% or fail! This may appear strange but in my scenario i "host" these classes on more "environment host" and i don't need to be sure that all are "well covered", but would be great if i could "enforce" my devs to cover well what i think is very important. What do you think?

**Comment by tonerdo** [comment]
#94 merged in an released https://www.nuget.org/packages/coverlet.msbuild/2.0.0. Thanks for your patience guys
