### ISSUE TITLE
MSBuild: async method reports uncovered branch on opening bracket

### ISSUE THREAD

**Issue by ssa3512** [tonerdo/coverlet#770]
I have an async method that I am trying to test, and it is showing an uncovered branch on the opening bracket of the method. Using an async test, or a sync test calling the task's `.Result` property produce the same result.

.NET Core 3.1
Both coverlet.msbuild 2.8.0 and coverlet.collector 1.2.0 report the same missed branches

This seems like it could be related to #623 but that should be fixed with these versions of coverlet.

![image](https://user-images.githubusercontent.com/1991399/77186200-e824d780-6aa8-11ea-9876-91d1bec3c790.png)

**Comment by MarcoRossignoli** [comment]
Hi Steve,

can you try with our nightly build so we understand if we already fixed? https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by ssa3512** [comment]
Yes, it looks like this is fixed in the nightly build. Sorry about that - should have tried that first.

**Comment by MarcoRossignoli** [comment]
No worries, feel free to close.
