### ISSUE TITLE
Data Collector not found when executed over a solution file

### ISSUE THREAD

**Issue by NPadrutt** [tonerdo/coverlet#779]
Since my coverage collection via MSBuild crashes from time to time I try to switch my build to collection via the test collector. I use the following command:

When I navigate to the csproj of a test project I can execute the following command and get a coverage result: 

`dotnet test --collect:"XPlat Code Coverage" --no-build`

However when I try to execute that over my solution file it seems that it doesn't find the collector:

`dotnet test ASK.UnitTests.sln --collect:"XPlat Code Coverage" --no-build`

`Data collection : Unable to find a datacollector with friendly name 'XPlat Code Coverage'.`

Do I have to make a different call when executed via the solution file?

**Comment by NPadrutt** [comment]
On further investigation it seems that this message is actually not for a test project but probably for a helper project. The coverage is calculate correctly. I'm sorry for the false alert! :)

**Comment by MarcoRossignoli** [comment]
No probs
