### ISSUE TITLE
Multiple output formats fails using Linux MSBuild

### ISSUE THREAD

**Issue by tillig** [tonerdo/coverlet#790]
This isn't a problem with Coverlet but maybe something to add to the documentation.

If you want to specify multiple output formats, the docs say you need to escape the quotes around the formats

`/p:CoverletOutputFormat=\"json,cobertura\"`

so in MSBuild it'd look like

```xml
<Exec Command="dotnet test MySolution.sln -c $(Configuration) /p:CollectCoverage=true /p:CoverletOutput=log /p:MergeWith=log/coverage.json /p:CoverletOutputFormat=\&quot;json,cobertura\&quot; -m:1" />
```

Unfortunately, [there's an issue with Linux MSBuild](https://github.com/microsoft/msbuild/issues/3468) that translates escape backslashes `\` to slashes `/` on the fly. Thus on, say Azure DevOps where you're running on an Ubuntu agent, you'll get an error like:

```text
MSBUILD : error MSB1006: Property is not valid. [/home/vsts/work/1/s/default.proj]
  Switch: cobertura/
```
The quotes aren't escaped and the command line gets parsed wrong.

On Windows this works as expected, and if you use `dotnet msbuild` on Linux it also works as expected. You'll see the error if you're on Linux and:

- You call the binary Linux MSBuild rather than `dotnet msbuild` OR
- You're in Azure DevOps on a Linux agent and use the `MSBuild` task (which uses the binary Linux MSBuild)

And maybe this issue is enough, something folks can search for and find later. I just know I spent like two hours trying to figure out why things worked fine on my Mac using `dotnet msbuild` but the Ubuntu agent was failing every time.

**Comment by MarcoRossignoli** [comment]
Thank's Travis to reporting this!
