### ISSUE TITLE
Cyclomatic complexity at method level is missing

### ISSUE THREAD

**Issue by dannyBies** [tonerdo/coverlet#797]
I'm trying to generate a report showing the Cyclomatic complexity of my methods, unfortunately the complexity is always empty:
![image](https://user-images.githubusercontent.com/3967506/78633883-c627b380-78f6-11ea-8cc3-997021b534b2.png)

In my coverage.cobertura.xml I can see that the complexity is calculated on the class level but not a method level:
```
<class name="<omitted>" filename="<omitted>" line-rate="1" branch-rate="1" complexity="5">
    <methods>
        <method name="<omitted>" signature="(System.Guid)" line-rate="1" branch-rate="1">
```

I was looking through the source code and noticed that in the [CoberturaReporter](https://github.com/NorekZ/coverlet/blob/7258b73d947840348b5ec93f1d5e78ff3782e2a9/src/coverlet.core/Reporters/CoberturaReporter.cs#L69) we're not calculating the complexity and thus the value won't show up.

Is this a bug or is there something else I'm missing?

**Comment by MarcoRossignoli** [comment]
Hi @dannyBies than's for reporting this.
I think it's a missing piece right from the start, I don't know why(I started to work on coverlet after that).
Would you like to provide a PR ti fill the gap?No obligated at all.

cc: @tonerdo

**Comment by dannyBies** [comment]
I've opened a PR with the fix + test validation.
