### ISSUE TITLE
Coverlet's abstraction of transparency is (inevitably) leaky

### ISSUE THREAD

**Issue by SteveGilham** [tonerdo/coverlet#80]
I have a system of `UnitTest.dll` which links against `SystemUnderTest.dll` and `SampleCode.dll`; my unit test instructs the system under test to use Mono.Cecil to read symbol data for the sample code.

This fails when run under coverlet with
```
Error Message:
 System.InvalidOperationException : Operation is not valid due to the current state of the object.
Stack Trace:
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
```

I'd be happy enough with a solution that went "if (running under coverlet) then (look in this deterministic named folder instead for the unaltered code)", but the folder to test for the existence of to look in is not even documented.

I expect similar problems might occur for code using the Microsoft.Cci facilities from FxCop, but haven't yet tested that.

**Comment by tonerdo** [comment]
This is definitely something that's bound to happen. Considering that coverlet rewrites assemblies I can imagine that an assembly trying to rewrite another assembly that coverlet has already instrumented will be a problem. There are two approaches I currently see to fix this:

* #77 when fixed will allow the developer to simply ignore the assembly his code wishes to rewrite
* Update the assembly PDB to match the changes made to the assembly. This comes with the added benefit of making code within instrumented assemblies debuggable during tests

The first approach is currently being worked on, the second one will make it into coverlet sometime in the future

**Comment by SteveGilham** [comment]
This affects even read-only operations that want to match IL with source (e.g. static analysis); #77, however will be an entirely satisfactory resolution

**Comment by tonerdo** [comment]
#77 fixed and merged in. See new release here: https://www.nuget.org/packages/coverlet.msbuild/2.0.0
