### ISSUE TITLE
Coverlet not detecting correctly line visits

### ISSUE THREAD

**Issue by ramoncarrascom** [tonerdo/coverlet#812]
Hi,
I'm relatively new to Coverlet, but I'm facing an issue that has been struggling me during the last two days. Although I've tests for all lines in a class, Coverlet report doesn't show a 100% line coverage. I'm going to try to detail all the steps I've done.
First of all, you can see all the entire project here: https://github.com/ramoncarrascom/BoringGames/tree/develop

My problem is that not all lines are detected as "visited", although I've made sure that I've got specific tests for these lines. Let me show you an example:

On `BoringGames.Shared\Models\Player.cs`, I've got an overriden method called `GetHashCode`. Coverlet says that its line is not covered:

![image](https://user-images.githubusercontent.com/24667318/79081526-8f023980-7d1e-11ea-8fd4-dc7182e2d681.png)

But in fact, I've a test in `BoringGames.Shared.Test\Models\PlayerTest.cs`:

![image](https://user-images.githubusercontent.com/24667318/79081546-c53fb900-7d1e-11ea-9614-d1c1ddb05b4c.png)

Even Visual Studio info detects this test passing the method:

![image](https://user-images.githubusercontent.com/24667318/79081567-f5875780-7d1e-11ea-8329-2ab1ddd9ae3f.png)

This same thing is happening with same class/testing class in several lines, and through several classes all across the solution. I've detected that this issue is more frequent with inheritance-related lines (overriden methods, methods in overriden classes, base classes whose methods are called using base.<method>....). But there are other tests in the same failing testing/tested classes whose coverage is correctly detected.

Although I've linked the complete project, I've zipped here the Player testing class, the tested Player class and the generated report.
[data.zip](https://github.com/tonerdo/coverlet/files/4467304/data.zip)

I've got the following SonarQube script:

```
SET BASEPATH=C:\git\BoringGames
dotnet tool install -g dotnet-reportgenerator-globaltool
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=%BASEPATH%\TestResults\ %BASEPATH%\BoringGames.Core.Test\BoringGames.Core.Test.csproj
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=%BASEPATH%\TestResults\ %BASEPATH%\BoringGames.Shared.Test\BoringGames.Shared.Test.csproj
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=%BASEPATH%\TestResults\ %BASEPATH%\TicTacToe.Test\TicTacToe.Test.csproj
reportgenerator -reports:%BASEPATH%\TestResults\coverage.opencover.xml -targetdir:%BASEPATH%\TestResults\Reports\ -reportTypes:"Cobertura"
dotnet C:\utils\sonarqube\netcore\SonarScanner.MSBuild.dll begin /k:"boringames" /d:sonar.cs.opencover.reportsPaths=%BASEPATH%\TestResults\coverage.opencover.xml /d:sonar.coverage.exclusions=”**Test*.cs”
dotnet build %BASEPATH%\BoringGames.sln
dotnet C:\utils\sonarqube\netcore\SonarScanner.MSBuild.dll end
```

But if I run coverlet standalone, I'got the same issue. I've used the following command line:

```
coverlet .\bin\Debug\netcoreapp3.1\boringames.shared.test.dll --target "dotnet" --targetargs "test ./ --no-build --verbosity normal"
```
Any idea why is this happening? Any comment will be appreciated. Thanks in advance.

**Comment by MarcoRossignoli** [comment]
Thank's for reporting this and for repro, I'll take a look asap.

**Comment by mbright77** [comment]
Hi!
I have a similiar problem when i have methods taking actions as in parameters.
In the following lines of code the action is not reported as covered after updating to the latest version. The action is invoked in a base class.

`  await _myService.UpdateAsync(existingObject, parentId, () =>
                       {
                           existingObject.UserID = userId;
                           existingObject.CreateDATE = createDate;
                           existingObject.ObjectID = objectId;
                    });`

I'm currently running version 2.7.0 where the lines are reported as covered,

**Comment by MarcoRossignoli** [comment]
@ramoncarrascom cannot repro, I cloned your branch https://github.com/ramoncarrascom/BoringGames/tree/develop
and run 
```
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover BoringGames.Shared.Test
```
after I generated report
```
reportgenerator -reports:C:\git\coverletissue\BoringGames\BoringGames.Shared.Test\coverage.opencover.xml -targetdir:C:\git\coverletissue\BoringGames\BoringGames.Shared.Test\Cover
```
![image](https://user-images.githubusercontent.com/7894084/79593500-d6504780-80db-11ea-89a0-9f722de50b5d.png)

**Comment by MarcoRossignoli** [comment]
Just a moment you're running 3 different test project in same folder so the last one override the others, you need to use different file name for every project o use merge feature https://github.com/tonerdo/coverlet/blob/master/Documentation/Examples/MSBuild/MergeWith/HowTo.md

**Comment by ramoncarrascom** [comment]
@MarcoRossignoli , that's right, the problem was that results weren't merging!! I've followed the rules shown in the link that you've shared, and everything is working perfectly fine now.

Thank you very much for your excellent support, for your time, and for all the good work done!
