### ISSUE TITLE
MSBuild Integration not throwing exit code in docker

### ISSUE THREAD

**Issue by jrperron88** [tonerdo/coverlet#817]
When running dotnet test in a dockerfile, I can see the threshold failing and throwing a text error. However, no exit code is thrown and it continues as normal.

If I use the coverlet console, exit codes get thrown correctly.

**Comment by lcsanchez** [comment]
@jrperron88 Were you able to solve this? I seem to be running into a verify similar issue. Will see if I can reproduce in a small sample app.

**Comment by lcsanchez** [comment]
Updating to the latest .net core sdk solved the issue for me
