### ISSUE TITLE
ExcludeFromCoverage method annotation does not exclude common forms of compiler generated code

### ISSUE THREAD

**Issue by SteveGilham** [tonerdo/coverlet#82]
In the following C# class I exercise the static method `Normal` and exclude pretty much everything else with `[ExcludeFromCoverage]`; the annotation takes for the simple method `Canary`, but essentially none of the other methods. In the F# code below it (linking the same coverage exclusion attribute), nested functions, lambdas and computation expressions are all still included.

![cv82](https://user-images.githubusercontent.com/7460854/39586311-ab9b35fc-4eee-11e8-8cd4-db9827638c85.png)

![cv82-bis](https://user-images.githubusercontent.com/7460854/39586937-440d4b12-4ef0-11e8-96ad-fa6b6bc04407.png)
![cv82a](https://user-images.githubusercontent.com/7460854/39590461-e09fbaf2-4ef8-11e8-9c1a-401c13468ac5.png)

**Comment by SteveGilham** [comment]
It should also come as no surprise that C#7.0 local functions are similarly not excluded even if the enclosing method is.

**Comment by tonerdo** [comment]
Thanks for reporting this. Definitely an oversight, will look into a fix. Any ideas you might have a welcome

**Comment by SteveGilham** [comment]
In the C# case, at least, the synthetic name contains the name of the lexically surrounding function in angle-brackets.  Where there isn't an overload of that method name, that will do the job. Overloads are going to be trickier to resolve.
