### ISSUE TITLE
Document Error

### ISSUE THREAD

**Issue by marsen** [tonerdo/coverlet#826]
Hi 
On your site https://discoverdot.net/projects/coverlet
this link is broken
https://discoverdot.net/projects/Documentation/VSTestIntegration.md

**Comment by MarcoRossignoli** [comment]
> On your site https://discoverdot.net/projects/coverlet

Hi @marsen that isn't "our" site, it's a site gathers(automatically) projects/blogs and in general useful information on .net ecosystem, it's not under our control, our primary guide is readme of this repo.

The right link is https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by marsen** [comment]
learn the new things ，thank you
