### ISSUE TITLE
Excluding Assemblies

### ISSUE THREAD

**Issue by JasonBock** [tonerdo/coverlet#85]
When I used coverlet to analyze code coverage, I got this:
```
| Module                     | Coverage |
|----------------------------|----------|
| EditorConfigGenerator.Core | 97.5%    |
| NUnit3.TestAdapter         | 30.7%    |
```
I don't want NUnit3.TestAdapter to show up. But I don't own this code, so I can't put attributes on their classes or exclude code files from then as I don't have that either.

Is there a way to say **only** include specific assemblies during analysis, or exclude certain ones? Either way would work (though I'd prefer the former as I don't have to keep blacklisting any that may show up in the future).

**Comment by MarcoRossignoli** [comment]
you can join our discussion on #77

**Comment by JasonBock** [comment]
Sounds good, I'll close this.

**Comment by tonerdo** [comment]
@JasonBock New release with fix now available: https://www.nuget.org/packages/coverlet.msbuild/2.0.0

**Comment by bpaczkowski** [comment]
Is there a way to accomplish this without having to manually include/exclude assemblies? Coverlet should exclude references by default IMO.

**Comment by MarcoRossignoli** [comment]
@bpaczkowski Coverlet at the moment exclude by design assembly for which doesn't have local source code.
What does mean "exlude reference"?
Can you explain better your use case, maybe opening a new issue?This is very old a lot of improvement was done since 2018.

**Comment by mehdihadeli** [comment]
@MarcoRossignoli I think it is more cleaner result if we can exclude local references as default instead of using exclude. usually we have separated tests and coverage for local references projects.
