### ISSUE TITLE
multiple classes/files with same name not covered

### ISSUE THREAD

**Issue by OneCyrus** [tonerdo/coverlet#9]
it looks like we don't get coverage reports for files which have same name and classes. For some APIs we we have multiple versions which only differ in a versioned namespace.. At the moment it looks like we get coverage report for the file ion namespace version1 but not in version2. Could there be some mapping issues when only the namespace is different?

**Comment by tonerdo** [comment]
This is weird because the fully qualified name is used and since the namespace is different, it should be unique. Will take a look

**Comment by OneCyrus** [comment]
may be it's a side effect of #7. I'll keep you updated once the updated nuget package is released.

**Comment by tonerdo** [comment]
@OneCyrus you can try out the new NuGet package https://www.nuget.org/packages/coverlet.msbuild/1.0.1

**Comment by OneCyrus** [comment]
still same issue with 1.0.1. Also tested if it depends on the other issue with the async tests. but even changing a test back to synchronous doesn't change the coverage.

**Comment by tonerdo** [comment]
Noted. Will look into this next as it seems fairly easy to repro

**Comment by tonerdo** [comment]
I just tried to repro this and was unable to. I had the same class name in the same file name in two different namespaces, in two different folders and both of them were in the coverage results. Can you explain your current structure?

**Comment by OneCyrus** [comment]
with the changes in 1.2.0 and 2.0.0 it looks good now. thanks!
