### ISSUE TITLE
Add html report as an output format

### ISSUE THREAD

**Issue by patros** [tonerdo/coverlet#90]
Is this an option that you would like added @tonerdo? I'd be happy to do some work in this space. I quite like the reports generated by coverage-viewer. It is written in node.js so it would need to be ported over to avoid the node.js dependency.

Edit: And I just double checked the licence for coverage-viewer and it is MIT as well.

**Comment by patros** [comment]
@hunterjm good point about having to maintain the html report generation. With a few good options maintained outside of this project the next question is whether Toni wants to include human readable output formats or to let the user choose their html generator of choice.

**Comment by tonerdo** [comment]
@patros I'm currently leaning towards letting the user choose their html generator of choice. But definitely something to think about

**Comment by patros** [comment]
@tonerdo I'll close this issue. It can always be reopened if you start to lean the other way.
