### ISSUE TITLE
xUnit console runner

### ISSUE THREAD

**Issue by karb0f0s** [tonerdo/coverlet#91]
Hi. 
We use `dotnet xunit` to run tests in our project. Is there a way to integrate `coverlet` in our pipeline?

**Comment by tonerdo** [comment]
Hi @karb0f0s, I'm not quite sure if that's possible out of the box. One method that comes to mind is to create an msbuild script that directly calls the various coverlet msbuild [targets](https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild/coverlet.msbuild.targets) before invoking `dotnet xunit --no-build`

**Comment by karb0f0s** [comment]
thanks for the info. hope i’ll come around with some solution and post it here
