### ISSUE TITLE
Documentation doesn't match current release version

### ISSUE THREAD

**Issue by patros** [tonerdo/coverlet#96]
Just realised this while trying to get filter by assembly working.

**Comment by patros** [comment]
You've been busy, my notifications keep filling up with coverlet related stuff :)

**Comment by tonerdo** [comment]
New version released: https://www.nuget.org/packages/coverlet.msbuild/2.0.0

**Comment by patros** [comment]
Hi @tonerdo. I raised this because it will keep happening without a dev/next-release branch that only gets merged into master when released (or some other indication to the user). It's not really an issue for someone familiar with coverlet but for new users it could cause frustration. Although I think this will largely be resolved when you have a nightly build pipeline set up.
